fix(editors/later-binding) Resolve absent prefix in ExtRef for later binding subscription
openscd/open-scd pull request #1026
Opened 2022-10-01 05:21 UTC by danyill

Partially resolves #1005

2022-10-02 21:57 UTC, JakobVogelsang commented
Very nice! Thanks for tracing back the issue. Would it be possible to add a regression test?

2022-10-03 05:53 UTC, dlabordus requested changes

2022-10-03 05:53 UTC, dlabordus commented on src/editors/subscription/later-binding/ext-ref-later-binding-list.ts
> +      (this.sameAttributeValue(extRefElement, 'prefix') || extRefElement.getAttribute('prefix') === null) &&
I don't think this is the full solution, because if the value of 'this.currentSelectedFcdaElement' is not null they are not the same.
I think the solution is to see if we can make the function 'sameAttributeValue also handle null values correctly.

2022-10-03 05:55 UTC, dlabordus commented on src/editors/subscription/later-binding/ext-ref-later-binding-list.ts
> +      (this.sameAttributeValue(extRefElement, 'prefix') || extRefElement.getAttribute('prefix') === null) &&
Maybe this implementation of sameAttributeValue will work better

```
  private sameAttributeValue(
    extRefElement: Element,
    attributeName: string
  ): boolean {
    return (
      extRefElement.getAttribute(attributeName) ?? '' ===
      this.currentSelectedFcdaElement?.getAttribute(attributeName) ?? ''
    );
  }```

2022-10-03 08:46 UTC, danyill commented on src/editors/subscription/later-binding/ext-ref-later-binding-list.ts
> +      (this.sameAttributeValue(extRefElement, 'prefix') || extRefElement.getAttribute('prefix') === null) &&
Thank you both for this review. I will add a few regression tests.

>I don't think this is the full solution, because if the value of 'this.currentSelectedFcdaElement' is not null they are not the same.
>I think the solution is to see if we can make the function 'sameAttributeValue also handle null values correctly.

:+1: You are correct, `prefix` is optional on both the FCDA and the ExtRef.

But I am less sure about the solution. This is not generally true for all attributes in the FCDA or ExtRef and isn't it "sloppy parsing" to allow this through in general?

Shouldn't we require that the SCL files are well-formed and apply this only to optional attributes by exception?

So at risk of overcomplicating things:

```js
(this.sameAttributeValue(extRefElement, 'prefix') || extRefElement.getAttribute('prefix') === null || this.getAttribute('prefix') === null) 
```

?

2022-10-04 05:23 UTC, dlabordus approved these changes

2022-10-04 06:25 UTC, danyill commented
Please don't merge I must do more here...

On Tue, 4 Oct 2022, 18:23 Dennis Labordus, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openscd/open-scd/pull/1026#pullrequestreview-1129312255>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFEXX6UIYC4BY6UOL6SMBDWBO5NNANCNFSM6AAAAAAQ2JKYXI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-04 08:09 UTC, danyill commented
Thank you for the review, I understand better now, despite this being quite trivial :wink: :cry: 

In preparing the tests I ran the scd file through OpenSCD which is why there is some whitespace diff.

Without this:

```diff
@@ -71,6 +71,9 @@
                                                <Inputs>
                                                        <ExtRef intAddr="Pos;CSWI1/Pos/stVal" desc="Interlocking.Input"/>
                                                        <ExtRef intAddr="Pos;CSWI1/Pos/q" desc="Interlocking.Input" iedName="GOOSE_Publisher" serviceType="GOOSE" ldInst="QB2_Disconnector" lnClass="CSWI" lnInst="1" prefix="" doName="Pos" daName="q" srcLDInst="QB2_Disconnector" srcPrefix="" srcLNClass="LLN0" srcCBName="GOOSE2"/>
+                                                       <ExtRef intAddr="Pos;CILO/EnaOpn/stVal" desc="Interlocking.Input2" iedName="GOOSE_Publisher" serviceType="GOOSE" ldInst="QB1_Disconnector" lnClass="CILO" lnInst="1" prefix="" doName="EnaOpn" daName="stVal" srcLDInst="QB2_Disconnector" srcPrefix="" srcLNClass="LLN0" srcCBName="GOOSE2"/>
+                                                       <ExtRef intAddr="Pos;CILO/EnaCls/stVal" desc="Interlocking.Input3" iedName="GOOSE_Publisher" serviceType="GOOSE" ldInst="QB1_Disconnector" lnClass="CILO" lnInst="1" doName="EnaCls" daName="stVal" srcLDInst="QB2_Disconnector" srcPrefix="" srcLNClass="LLN0" srcCBName="GOOSE2"/>
+                                                       <ExtRef intAddr="Pos;CILO/EnaOpn2/stVal" desc="Interlocking.Input4" iedName="GOOSE_Publisher" serviceType="GOOSE" ldInst="QB2_Disconnector" lnClass="CILO" lnInst="1" doName="EnaOpn" daName="stVal" srcLDInst="QB2_Disconnector" srcPrefix="" srcLNClass="LLN0" srcCBName="GOOSE2"/>
                                                </Inputs>
                                        </LN>
                                        <LN prefix="" lnClass="CSWI" inst="1" lnType="Dummy.CSWI">
@@ -94,6 +97,9 @@
                                                <DataSet name="GOOSE2sDataSet">
                                                        <FCDA ldInst="QB2_Disconnector" prefix="" lnClass="CSWI" lnInst="1" doName="Pos" daName="stVal" fc="ST"/>
                                                        <FCDA ldInst="QB2_Disconnector" prefix="" lnClass="CSWI" lnInst="1" doName="Pos" daName="q" fc="ST"/>
+                                                       <FCDA ldInst="QB1_Disconnector" lnClass="CILO" lnInst="1" doName="EnaOpn" daName="stVal" fc="ST"/>
+                                                       <FCDA ldInst="QB1_Disconnector" prefix="" lnClass="CILO" lnInst="1" doName="EnaCls" daName="stVal" fc="ST"/>
+                                                       <FCDA ldInst="QB2_Disconnector" lnClass="CILO" lnInst="1" doName="EnaOpn" daName="stVal" fc="ST"/>
                                                </DataSet>
                                                <DataSet name="GOOSE1sDataSet">
                                                        <FCDA ldInst="QB1_Disconnector" prefix="" lnClass="CSWI" lnInst="1" doName="Pos" daName="stVal" fc="ST"/>
```

I have added CILO LN subscriptions with the following combinations, which I think cover the relevant cases.

```
FCDA        ExtRef
No prefix   Prefix
Prefix      No prefix
No prefix   No prefix
```

2022-10-05 05:21 UTC, dlabordus approved these changes

2022-10-05 06:35 UTC, merged