Added sub-equipment to Sub-Station editor
openscd/open-scd pull request #1030
Opened 2022-10-04 07:02 UTC by pascalwilbrink

Signed-off-by: Pascal Wilbrink <pascal.wilbrink@alliander.com>

2022-10-04 14:06 UTC, dlabordus requested changes

2022-10-04 14:06 UTC, dlabordus commented on test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
> +snapshots[
Don't understand why these kind of formatting changes are made.

2022-10-04 14:06 UTC, dlabordus commented on src/editors/substation/sub-equipment-editor.ts
> +      this.element.getAttribute('desc') ?? 'UNDEFINED'
Maybe also create different snapshot tests for this to show what happens when these attributes are empty.

2022-10-17 12:12 UTC, pascalwilbrink commented on test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
> +snapshots[
Fixed

2022-10-17 13:27 UTC, JakobVogelsang requested changes

2022-10-17 13:27 UTC, JakobVogelsang commented on src/editors/substation/sub-equipment-editor.ts
> +  render(): TemplateResult {
Methods that are used in another methods are usuaelly on top of each other. Here
```
...renderEqFunction

...renderLNodes

...render
```

2022-10-17 13:27 UTC, JakobVogelsang commented on src/foundation.ts
> +      'SubEquipment',
Thanks we missed that!

2022-10-17 13:27 UTC, JakobVogelsang commented on src/foundation.ts
> +      'SubEquipment',
Thanks we missed that!

2022-10-17 13:27 UTC, JakobVogelsang commented on src/foundation.ts
> +      'ConductingEquipment',
Thanks we missed that!

2022-10-17 13:27 UTC, JakobVogelsang commented on test/testfiles/valid2007B4.scd
> +			<PowerTransformer xmlns="http://www.iec.ch/61850/2003/SCL" name="pTrans" type="PTR">
I would not mess around in already existing test files too much. Here for example you cannot guarantee that it is still schema valid. I would work with the test file I gave you.

2022-10-17 13:27 UTC, JakobVogelsang commented on test/testfiles/valid2007B4withSubstationXY.scd
> -					<LN lnClass="XCBR" inst="1" lnType="Dummy.XCBR1">
Same here!

2022-10-17 13:27 UTC, JakobVogelsang commented on test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
> +snapshots[
No it is not. You system is makeing `"` to `'`. When I have to touch that file it is again indicated as a change. There should not be any diff in this snapshot

2022-10-17 13:27 UTC, JakobVogelsang commented on test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
> -snapshots["conducting-equipment-editor rendered as action pane looks like the latest snapshot"] =
Same here

2022-10-17 13:27 UTC, JakobVogelsang commented on test/unit/editors/substation/sub-equipment-editor.test.ts
> +    await expect(element).shadowDom.to.equalSnapshot();
There are test missing. How do I see that all the valid child elements are rendered as well when they are in the file.

2022-10-19 18:57 UTC, JakobVogelsang reviewed
I cannot explain myself one snapshot. Other than that LGTM

2022-10-19 18:57 UTC, JakobVogelsang commented on test/unit/editors/substation/__snapshots__/voltage-level-editor.test.snap.js
> +  <div class="actionicon ptrContent">
Where is this coming from? Changed test file?

2022-10-20 12:12 UTC, JakobVogelsang approved these changes
LGTM

2022-10-21 07:49 UTC, merged