feat(editor/subscriber): Added plugin for Subscriber Logical Nodes (GOOSE)
openscd/open-scd pull request #1036
Opened 2022-10-10 11:09 UTC by dlabordus

closes #935 
closes #936

2022-10-12 11:54 UTC, JakobVogelsang requested changes
I think there is something still incorrect. Also provided translations and some code style bla bla

2022-10-12 11:54 UTC, JakobVogelsang commented on test/unit/editors/subscription/later-binding/ext-ref-ln-binding-list.test.ts
> +        expect(element['getAvailableLNElements']().length).to.be.equal(5);
I am wondering why this sum (1, 5) is different to the once in the previous test sum (0, 8). Here, the `CSWI` is missing.

2022-10-12 11:54 UTC, JakobVogelsang commented on test/unit/editors/subscription/later-binding/ext-ref-ln-binding-list.test.ts
> +      expect(element['getSubscribedLNElements']().length).to.be.equal(3);
Same here thesum is 6, but the file of all subscribers have in sum 8 logical nodes

2022-10-12 15:09 UTC, dlabordus commented on test/unit/editors/subscription/later-binding/ext-ref-ln-binding-list.test.ts
> +        expect(element['getAvailableLNElements']().length).to.be.equal(5);
I think it has to do with Later Binding records that are in some cases not displayed.

2022-10-12 15:09 UTC, dlabordus commented on test/unit/editors/subscription/later-binding/ext-ref-ln-binding-list.test.ts
> +      expect(element['getSubscribedLNElements']().length).to.be.equal(3);
I think it has to do with Later Binding records that are in some cases not displayed.

2022-10-12 15:21 UTC, dlabordus commented on src/editors/SMVSubscriberDataBinding.ts
> +/** An editor [[`plugin`]] for Subscribe Later Binding (SMV). */
Changed it.

2022-10-12 15:32 UTC, dlabordus commented on src/editors/subscription/later-binding/ext-ref-ln-binding-list.ts
> +              <mwc-icon slot="graphic">swap_horiz</mwc-icon>
Fixed.

2022-10-12 15:33 UTC, dlabordus commented on src/translations/de.ts
> +        noAvailableLNs: '???',
Thanks

2022-10-12 15:33 UTC, dlabordus commented on src/translations/de.ts
> +        noSubscribedLNs: '???',
Thanks

2022-10-12 15:33 UTC, dlabordus commented on src/translations/de.ts
> +        noSelection: '???',
Thanks

2022-10-13 05:23 UTC, dlabordus commented on test/unit/editors/GooseSubscriberDataBinding.test.ts
> +    doc = await fetch('/test/testfiles/valid2007B4ForSubscription.scd')
Fixed

2022-10-13 05:24 UTC, dlabordus commented on test/unit/editors/subscription/later-binding/ext-ref-ln-binding-list.test.ts
> +        expect(element['getAvailableLNElements']().length).to.be.equal(5);
Will fix this in PR #1040, because of the refactoring of this part of the code for the counters.

2022-10-13 05:24 UTC, dlabordus commented on test/unit/editors/subscription/later-binding/ext-ref-ln-binding-list.test.ts
> +      expect(element['getSubscribedLNElements']().length).to.be.equal(3);
Will fix this in PR #1040, because of the refactoring of this part of the code for the counters.

2022-10-13 06:57 UTC, JakobVogelsang approved these changes
LGTM

2022-10-13 09:11 UTC, merged