feat(general-equipment-editor.ts):Remove_added_and_test
openscd/open-scd pull request #1107
Opened 2022-12-12 10:40 UTC by marcvanraalte

2022-12-19 09:47 UTC, JakobVogelsang requested changes

2022-12-19 09:47 UTC, JakobVogelsang commented on src/editors/substation/general-equipment-editor.ts
> +        <mwc-icon-button
Using `action-icon` `mwc-icon-button` looks strange. That is why all other editor use `mwc-fab` instead.
Same is true for the edit button. Sorry that slipped through the review

2022-12-22 09:07 UTC, pascalwilbrink commented on src/editors/substation/general-equipment-editor.ts
> +        <mwc-icon-button
It looks like they're being mixed. sometimes mwc-icon-button, sometimes mwc-fab.
If you look at the function-editor (for example), that one is using mwc-icon button.
the powertransformer-editor (for example) is using the mwc-fab.

@JakobVogelsang, we can change it to mwc-fab for now, but maybe it's better to change it everywhere?

2022-12-22 09:22 UTC, pascalwilbrink commented on src/editors/substation/general-equipment-editor.ts
> +        <mwc-icon-button
We found out what you meant with action-icon > mwc-icon-button :) changed it in the code. should look good now

2022-12-22 10:41 UTC, JakobVogelsang commented on src/editors/substation/general-equipment-editor.ts
> +        <mwc-icon-button
Nice. Thx

2022-12-22 10:55 UTC, JakobVogelsang approved these changes
LGTM

2022-12-22 10:56 UTC, merged