Services wizard (WIP)
openscd/open-scd pull request #1109
Opened 2022-12-14 14:22 UTC by pascalwilbrink

Signed-off-by: Pascal Wilbrink <pascal.wilbrink@alliander.com>

2023-02-01 10:05 UTC, Sander3003 commented
@pascalwilbrink can you finish this pull-request? I would like get in into production.

2023-02-07 11:08 UTC, JakobVogelsang requested changes

2023-02-07 11:08 UTC, JakobVogelsang commented on test/integration/wizards/services-wizard.test.ts
> +    [13, 22, 22, 28].forEach((inputs, idx) => {
Nice idea!!

2023-02-07 11:08 UTC, JakobVogelsang commented on test/integration/wizards/services-wizard.test.ts
> +    [0, 1, 2, 3, 4].forEach(idx => {
I fear those snapshots are not enough. They cover not all inputs. The test file I gave you has per AccessPoint inputs activated. You are using "only" the one in the IED element.

2023-02-07 11:08 UTC, JakobVogelsang commented on test/unit/editors/ied/__snapshots__/access-point-container.test.snap.js
> +  <abbr
Please reverse this.

2023-02-10 10:39 UTC, JakobVogelsang commented on test/integration/wizards/services-wizard.test.ts
> +    [0, 1, 2, 3, 4].forEach(idx => {
At the moment, you are coveting 4 out of 6 pages with the snapshot by choosing the `Services` element in the `IED`. By adding additional tests, you can make the rest of the pages visible. @pascalwilbrink

2023-02-20 13:35 UTC, pascalwilbrink commented on test/integration/wizards/services-wizard.test.ts
> +    [0, 1, 2, 3, 4].forEach(idx => {
Fixed

2023-02-22 15:09 UTC, JakobVogelsang approved these changes
LGTM thx

2023-02-23 08:59 UTC, merged