Create network configuration plug in
openscd/open-scd pull request #111
Opened 2021-02-03 16:35 UTC by JakobVogelsang

The code is ready for review with missing units

2021-02-04 14:17 UTC, c-dinkel requested changes

2021-02-04 14:17 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +  static creatAction(parent: Element): WizardAction {
Don't be `UNIX` Ken Thompson, be `Plan 9` Ken Thompson!

> Ken Thompson was once asked what he would do differently if he were redesigning the UNIX system. His reply: "I'd spell creat with an e."
> Kernighan, Brian W.; Pike, Rob (1984). The UNIX programming environment. Prentice-Hall. ISBN 0139376992, p. 204.
>
> [in Plan 9, he got his wish ;-)](https://github.com/akavel/plan9/blob/master/sys/include/9p.h#L185)

2021-02-04 14:17 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +  static isEqualAddress(oldAddr: Element, newAdddr: Element): boolean {
Why are these `static` methods? Could some of them be hoisted outside of the class as functions or is this for testing?

2021-02-04 14:17 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +  static editAction(parent: Element): WizardAction {
This seems pretty complex, do you think you could refactor out a subroutine or two?

2021-02-04 14:17 UTC, c-dinkel commented on src/editors/communication/foundation.ts
> +    border-bottom: none !important;
Try to find a more specific `css` selector to use instead of `!important`, it's [considered bad style for pretty good reasons](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception)

2021-02-04 14:17 UTC, c-dinkel commented on src/editors/communication/subnetwork-editor.ts
> +        element: new DOMParser().parseFromString(
Please use `createElement` over `DOMParser` always in actions to get elements with the correct `ownerDocument`

2021-02-04 14:17 UTC, c-dinkel commented on src/foundation.ts
> +export const unique = (
This does not report whether `value` is unique within `self` (could be named `array`, `within`, or something like that?).

`indexOf(value) === `index` only tells you if `index` is the first place where `value` appers, not if it's the only one. If that's the intended behaviour, maybe rename the function to `first`?

Also, is this actually used anywhere? If so, are they few enough places that this could be inlined?

2021-02-04 21:36 UTC, JakobVogelsang commented on src/editors/communication/connectedap-editor.ts
> +import { Checkbox } from '@material/mwc-checkbox';
Good hint thank you. I totally agree. With web-componets we should make certain the components we need are importet within the web-component. I also rearanged the import statements to be better readable.

2021-02-04 21:39 UTC, JakobVogelsang commented on src/editors/communication/connectedap-editor.ts
> +function compare(a: itemDescription, b: itemDescription): number {
What about `compareListItemConnection`? Too long?

2021-02-04 21:41 UTC, JakobVogelsang commented on src/editors/communication/connectedap-editor.ts
> +  static creatAction(parent: Element): WizardAction {
:) Thank you Ken Thompson for appreciating the smaller things in live.

2021-02-04 21:49 UTC, JakobVogelsang commented on src/editors/communication/connectedap-editor.ts
> +  static isEqualAddress(oldAddr: Element, newAdddr: Element): boolean {
The pattern is used in all editors now. Initialy we used functions and switched to static method to better unit test.

2021-02-05 09:30 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +function compare(a: itemDescription, b: itemDescription): number {
Since the thing we're comparing are `itemDescription`s and not `Connection`s, `compareItemDescriptionByConnected` would be more accurate, but that absolutely seems too long for a non-exported local function. So if you want to repeat the types of the operands in the name rather than say what the function does, `compareItemDescriptions` might work e.g.  In general I think this is not that important and `compare` can stand.

However: Why is the type name `itemDescription` lowercase?

2021-02-05 09:33 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +  static isEqualAddress(oldAddr: Element, newAdddr: Element): boolean {
If it's necessary for testing we can absolutely keep doing this, but I wouldn't go so far as to call it a pattern, and I will continue to try to export regular functions instead of embedding them as static methods wherever possible, see e.g. [the first answer to this question about C++](https://stackoverflow.com/questions/1434937/namespace-functions-versus-static-methods-on-a-class).

2021-02-05 10:20 UTC, JakobVogelsang commented on src/editors/communication/foundation.ts
> +    border-bottom: none !important;
We don't need that anyway. `themes` covers it!

2021-02-08 08:30 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +        // INFO: We cannot use updateAction on address as bot address
That comment is really helpful, thanks! The all-caps word `INFO: ` in the beginning draws a lot of attention though. Could we leave it out?

2021-02-08 09:15 UTC, c-dinkel requested changes

2021-02-08 09:15 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +            reference: parent.firstElementChild?.nextElementSibling ?? null,
Why do we always want to use the second child element as reference? Is it correct not to use `oldAddress.nextElementSibling` here?

2021-02-08 09:15 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +        title: `Edit Address (${parent.getAttribute('iedName')})`,
This needs to be translated. Are there any other user visible English language strings in this commit that might still require translations?

2021-02-12 09:43 UTC, c-dinkel approved these changes
LOTM

2021-02-12 09:43 UTC, c-dinkel commented on src/editors/communication/connectedap-editor.ts
> +        // INFO: We cannot use updateAction on address as both address
👎

2021-02-12 09:46 UTC, merged