feat(../substation/sub-equipment-editor.ts):add_button_to_the_SubEqui…
openscd/open-scd pull request #1113
Opened 2023-01-05 12:01 UTC by marcvanraalte

…pment_editor

2023-01-10 14:46 UTC, JakobVogelsang requested changes

2023-01-10 14:46 UTC, JakobVogelsang commented on src/editors/substation/sub-equipment-editor.ts
> +  firstUpdated(): void {
This is not really your fault, but we are fixing an issue where the anchor gets lost on update. Therefore I would like you to change `firstUpdated` to `updated`

2023-01-11 11:40 UTC, pascalwilbrink commented on src/editors/substation/sub-equipment-editor.ts
> +  firstUpdated(): void {
Fixed

2023-01-11 14:43 UTC, merged

2023-01-11 14:45 UTC, marcvanraalte commented
961_add_button_SubEquipment closed