feat: Added sonarcloud Github Action
openscd/open-scd pull request #1243
Opened 2023-04-26 10:29 UTC by pascalwilbrink

feat: Added sonarcloud Github Action
fixes: #1242

2023-06-22 02:48 UTC, juancho0202 commented
@pascalwilbrink let's apply the same principle here of splitting the process into an unprivileged build workflow and a subsequent one triggered by `workflow_run` to have access to the Sonarcloud secret and analyze forked PRs

2023-06-22 08:51 UTC, Stef3st requested changes
Before implementing we might want to check what rules/boundries we'd like to apply here

2023-06-22 08:51 UTC, Stef3st commented on .github/workflows/sonarcloud.yml
> +      - 'develop'
There's no develop branch on open-scd. This can be removed

2023-06-22 08:51 UTC, Stef3st commented on .github/workflows/sonarcloud.yml
> +      - 'develop'
There's no develop branch on open-scd. This can be removed

2023-08-22 09:44 UTC, trusz commented
Is this PR still relevant?

2023-09-06 13:20 UTC, trusz commented
It is weird that sonarcloud did not find anything. We have to check the configs.

2023-09-11 07:32 UTC, juancho0202 commented
> It is weird that sonarcloud did not find anything. We have to check the configs.

@trusz it is weird because if you navigate to their analysis of the main branch there are 45 bugs detailed in there: https://sonarcloud.io/project/issues?resolved=false&id=openscd_open-scd

2024-07-18 08:03 UTC, trusz commented
The SonarCloud projects does not exist anymore. I will close this PR, but we can reopen it again if we want to proceed with SonarCloud

2024-07-18 08:03 UTC, closed without merging