fix: tooltip for ied-container's settings icon
openscd/open-scd pull request #1252
Opened 2023-05-08 09:09 UTC by juancho0202

2023-05-09 06:51 UTC, Sander3003 requested changes

2023-05-09 06:51 UTC, Sander3003 commented on src/translations/en.ts
> +    settings: 'Show Services the IED provides',
Suggestion: change "Show Services the IED provides" to "Show Services the IED/port provides"

Services can be applied to the IED and/or specific ports
![image](https://user-images.githubusercontent.com/7427358/237016579-20ab2882-65fd-4932-8f26-7ea48f1343ca.png)

![image](https://user-images.githubusercontent.com/7427358/237016730-5933226f-ee81-424e-a8d0-9554d073ca51.png)

2023-05-09 06:53 UTC, Sander3003 commented on src/translations/en.ts
> +    settings: 'Show Services the IED provides',
Does this pull-request closes an issue?

2023-05-09 08:25 UTC, juancho0202 commented on src/translations/de.ts
> +    settings: '?????',
@JakobVogelsang please suggest the appropiate german translation for _'Show Services the IED/port provides'_

2023-05-09 10:33 UTC, JakobVogelsang commented
lnFilter: 'Filter für logische Knoten'
settings: 'Services für IED or AccessPoint'

2023-05-10 05:58 UTC, danyill submitted a review, later dismissed
Just one little suggestion, thank you for attending to this :+1:

2023-05-10 05:58 UTC, danyill commented on src/translations/en.ts
> +    settings: 'Show Services the IED/port provides',
Rather than `port` should we match Jakob's translation and retain the SCL-specific name with:

```suggestion
    settings: 'Show Services the IED/AccessPoint provides',
```

2023-05-11 08:03 UTC, Sander3003 approved these changes

2023-05-11 09:12 UTC, merged