Add gesecontrol subscriber info
openscd/open-scd pull request #126
Opened 2021-02-16 00:11 UTC by JakobVogelsang

2021-02-16 14:14 UTC, c-dinkel requested changes

2021-02-16 14:14 UTC, c-dinkel commented on src/Importing.ts
> +          title: 'Import IED ' + ied.getAttribute('name'),
There seems to be a translation missing here. Are there also translations missing in other places?

2021-02-16 14:16 UTC, c-dinkel commented
This could use a rebase on the current main branch.

2021-02-17 06:27 UTC, JakobVogelsang commented on src/Importing.ts
> +          title: 'Import IED ' + ied.getAttribute('name'),
I found another one. Those were introduced with the importing mixin. Thanks for the hint!

2021-02-20 09:33 UTC, c-dinkel commented on test/integration/open-scd.test.ts
> +    it('throws dublicate ied name error', async () => {
this is actually spelt "duplicate" 😉

2021-02-20 09:34 UTC, c-dinkel approved these changes
Only a test spelling mistake left.

2021-02-20 09:37 UTC, c-dinkel commented
Closes #82 .

2021-02-20 09:44 UTC, c-dinkel commented
Sorry for the accidental premature closing of this request.

2021-02-20 23:12 UTC, merged