fix: Fix regular expression warnings in template editor
openscd/open-scd pull request #1273
Opened 2023-06-22 20:21 UTC by danyill

Closes #1271

2023-06-23 06:49 UTC, danyill commented
These tests pass locally but I am struggling to convince CI to agree with me.
I think the snapshots are regenerated and correct am surprised to see them failing.
I regenerated the `package-lock.json` because this seemed to help locally (I could make them fail with an `npm ci` but not an `npm i`).

2023-06-23 11:04 UTC, Stef3st commented
@danyill when snapshots are created prettier gets called and unfortunatly removes the escape characters. In the previous ticket I fixed this with a workaround by ignoring the patterns in the snapshots and test them individually. You can check it out in the closed PR (https://github.com/openscd/open-scd/pull/1266).

2023-06-23 11:58 UTC, ca-d commented
@Stef3st it looks like your pull request was merged, doesn't that make this pull request entirely superfluous?

2023-06-24 18:35 UTC, danyill commented
> @danyill when snapshots are created prettier gets called and unfortunatly removes the escape characters. In the previous ticket I fixed this with a workaround by ignoring the patterns in the snapshots and test them individually. You can check it out in the closed PR (https://github.com/openscd/open-scd/pull/1266).

That was exactly the hint I needed and should have noticed on that PR previously. Thanks!

2023-06-26 08:16 UTC, Stef3st requested changes

2023-06-26 08:16 UTC, Stef3st commented on test/integration/editors/templates/dotype-wizarding.test.ts
> +
For completion you can add the following in here:
```
 // work around, because the escapes get removed in snapshot by prettier
    it('should have correct pattern', async () => {
      expect(
        parent.wizardUI.dialog!.querySelectorAll('wizard-textfield[pattern]')!
          .length
      ).to.equal(2);
      expect(
        parent.wizardUI
          .dialog!.querySelectorAll('wizard-textfield[pattern]')[0]
          .getAttribute('pattern')
      ).to.equal(patterns.tRestrName1stL);

      expect(
        parent.wizardUI
          .dialog!.querySelectorAll('wizard-textfield[pattern]')[1]
          .getAttribute('pattern')
      ).to.equal(patterns.normalizedString);
    });
```

2023-06-26 08:57 UTC, danyill commented on test/integration/editors/templates/dotype-wizarding.test.ts
> +
Thanks, missed that one.

2023-06-26 09:29 UTC, Stef3st approved these changes
LGTM!

2023-06-26 10:47 UTC, merged

2023-06-26 10:47 UTC, danyill commented
Thanks for the review :clap: