Initalize ADR for the repository
openscd/open-scd pull request #1282
Opened 2023-07-26 20:33 UTC by trusz

2023-08-04 04:41 UTC, danyill reviewed
LGTM. 

I only didn't approve because I feel we need a "maintainer's approval" and that cannot reasonably be "everyone with admin rights" on this repo which is insufficient to give a architecturally harmonious outcome (recently referred to as the "wild west" :horse_racing: :cowboy_hat_face:)

2023-08-07 09:21 UTC, juancho0202 requested changes

2023-08-07 09:21 UTC, juancho0202 commented on docs/adr/0001-record-architecture-decisions.md
> +- It will be harder to track which decisions have to be taken into consideration
Wouldn't it be easier if everyone adheres to creating ADRs before making big changes to the project and we track those taken into consideration by looking at active PRs?

2023-08-07 10:12 UTC, trusz commented on docs/adr/0001-record-architecture-decisions.md
> +- It will be harder to track which decisions have to be taken into consideration
I'm not sure if I understand your point.
Yes big, architecture relevant changes should be a PR with an ADR
The problem is if we have a global ADR in the .github repo that applies to all the repo and projects in this organisation.

2023-08-22 08:51 UTC, pascalwilbrink approved these changes
LGTM!

2023-08-22 09:24 UTC, trusz commented on docs/adr/0001-record-architecture-decisions.md
> +- It will be harder to track which decisions have to be taken into consideration
I agree with your statement generally, but I think that is for another ADR or some other form of agreement, so I think there is no change needed in this PR in that regard.

2023-08-22 09:25 UTC, merged