Chore: Added ConfDataSet to the Services Wizard
openscd/open-scd pull request #1332
Opened 2023-10-18 13:58 UTC by pascalwilbrink

2023-10-31 08:13 UTC, Sander3003 commented
@JakobVogelsang can you review this?

2023-10-31 12:22 UTC, JakobVogelsang requested changes
Some settings seem to not be acc to the issue description

2023-10-31 12:22 UTC, JakobVogelsang commented on packages/open-scd/src/wizards/service-log-settingsgroup.ts
> +        parent.querySelector('ConfDataSet')?.getAttribute('modify') ?? null,
default is true acc to the issue description

2023-10-31 12:22 UTC, JakobVogelsang commented on packages/open-scd/src/wizards/service-log-settingsgroup.ts
> +            nullable: true,
should not be nullable acc to the issue description

2023-10-31 12:22 UTC, JakobVogelsang commented on packages/open-scd/src/wizards/service-log-settingsgroup.ts
> +            helper: 'The maximum number of data sets in this IED',
This was my mistake that I just noticed. The text should read:

`The maximum allow data sets in this IED`

2023-10-31 12:22 UTC, JakobVogelsang commented on packages/open-scd/src/wizards/service-log-settingsgroup.ts
> +            helper: 'Whether DataSet can be modified by SCT',
should be nullable as the attribute is not required in the SCL

2023-10-31 12:22 UTC, JakobVogelsang commented on packages/open-scd/test/integration/wizards/services-wizard.test.ts
> +    describe(`IED [${ied}]: define a Services wizards`, () => {
I am not sure whether these changes have anything to do with the linked issue. There seem to be an extra refactor be part of this PR. If so please give some description on this one in the description of the PR.

2023-10-31 12:59 UTC, pascalwilbrink commented on packages/open-scd/test/integration/wizards/services-wizard.test.ts
> +    describe(`IED [${ied}]: define a Services wizards`, () => {
I've just added a few more tests (instead of writing it manually, i'm looping over the Services that are inside the SCD File. `Services` was the old section that was tested. `Services2` doesn't have the max attribute, so it's basically just checking that that functionality works

2023-10-31 13:33 UTC, JakobVogelsang commented on packages/open-scd/test/integration/wizards/services-wizard.test.ts
> +    describe(`IED [${ied}]: define a Services wizards`, () => {
Thank you for the explanation. That will do it.

2023-11-02 08:19 UTC, JakobVogelsang commented on packages/open-scd/test/integration/wizards/dist/services-wizard.test.js
> +"use strict";
That looks like build output. Is this on purpose?

2023-11-02 08:20 UTC, JakobVogelsang reviewed
LGTM. 

some JavaScript files seem not to belong to this PR

2023-11-02 10:12 UTC, JakobVogelsang approved these changes
LGTM

2023-11-13 10:18 UTC, merged