Split logging
openscd/open-scd pull request #1334
Opened 2023-10-19 12:00 UTC by pascalwilbrink

2023-10-24 14:27 UTC, juancho0202 requested changes

2023-10-24 15:30 UTC, pascalwilbrink commented on packages/open-scd/src/Historing.ts
The onLog function is bound to the current instance, so the function that this function calls, are on the same instance.

I actually don't think that onLog needs to be bounded, but i left it as is

2023-10-25 14:19 UTC, juancho0202 approved these changes

2023-10-25 14:20 UTC, juancho0202 commented
LGTM!

2023-10-31 08:08 UTC, merged