fix: supervision updates after ied rename
openscd/open-scd pull request #1338
Opened 2023-10-24 13:05 UTC by Stef3st

closes #1224

2023-10-30 16:07 UTC, JakobVogelsang requested changes
I would have love to have the changes be separated somehow from the prettier changes. Them be in the same commit makes the review quite complicated.

2023-10-30 16:07 UTC, JakobVogelsang commented on packages/open-scd/test/unit/wizards/foundation/references.test.ts
> +        newName + valSuffix3
Why not using the `newValueName` that is defined in the beginning of the test?

2023-10-30 16:08 UTC, JakobVogelsang commented
I have not checked out yet and did not do the functional review.

2023-10-30 16:47 UTC, Stef3st commented on packages/open-scd/test/unit/wizards/foundation/references.test.ts
> +        newName + valSuffix3
oldValName and newValName were to static. Its something I ended up not using anymore but forgot to remove. Good catch!

2023-10-30 16:47 UTC, Stef3st commented on packages/open-scd/src/wizards/foundation/references.ts
> +          break extRefLoop;
I agree, I got in my head with too many corner case that I couldn't figure out how to deal with them all in 2 loops. Ill try to think of a better way if this is unacceptable

2023-10-30 16:48 UTC, Stef3st commented on packages/open-scd/src/wizards/foundation/references.ts
> +        `LN[lnClass="LGOS"] > DOI > DAI > Val, LN[lnClass="LSVS"] > DOI > DAI > Val[textContent*="${oldName}"]`
Will do!

2023-10-30 16:49 UTC, Stef3st commented on packages/open-scd/src/wizards/foundation/references.ts
> +  if (element.tagName === 'IED') updateVals(element, oldName, newName, actions);
Will do that!

2023-10-30 16:49 UTC, Stef3st commented on packages/open-scd/src/wizards/foundation/references.ts
> +  // Each IED will be checked for the extRef elements. So firstly all the IEDs will be gathered with the querySelectorAll function.
No its not, I just wanted to make this as clear as possible.

2023-10-30 16:51 UTC, Stef3st commented on packages/open-scd/src/wizards/foundation/references.ts
> +        `LN[lnClass="LGOS"] > DOI > DAI > Val, LN[lnClass="LSVS"] > DOI > DAI > Val[textContent*="${oldName}"]`
1. Good catch
2. Im not sure what you mean? I check if the textContent contains the oldName

2023-11-02 10:12 UTC, JakobVogelsang approved these changes
LGTM

2023-11-02 13:11 UTC, merged