fix(104): change options between different tis when selecting a doi
openscd/open-scd pull request #1380
Opened 2023-12-04 14:11 UTC by Stef3st

closes #1375

2023-12-05 15:41 UTC, juancho0202 requested changes

2023-12-05 15:41 UTC, juancho0202 commented on packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts
> +            }}
I would prefer if you move this chunk into a separate function for code readability, also verify that your querySelector has found something before trying to modify its disabled property to avoid a "cannot read property of undefined" scenario 👍

2023-12-05 15:41 UTC, juancho0202 commented on packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts
> +  const tiNumber = tiNumberInfo.split(' (')[0];
is this necessary? I thought the value in the dropdown was still set to only the tiNumber and that the split in your other PR was only to account for the maybeValue of the wizardtextfield

2023-12-05 15:41 UTC, juancho0202 commented on packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts
> +export function disableMonitorInvertedSwitch(
Why not fixing this faulty behavior for all cases using the disableInvertedSwitch? This seems like code duplication

2023-12-07 07:05 UTC, Stef3st commented on packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts
> +            }}
Good catch! Will add that in

2023-12-07 07:06 UTC, Stef3st commented on packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts
> +  const tiNumber = tiNumberInfo.split(' (')[0];
you're right, this really isn't necessary. Will remove that part!

2023-12-07 09:03 UTC, juancho0202 approved these changes
LGTM!

2023-12-07 09:04 UTC, merged