feat: implement wye and del cdc support
openscd/open-scd pull request #1390
Opened 2023-12-18 09:06 UTC by Stef3st

closes #1358

2024-01-10 08:18 UTC, pascalwilbrink requested changes

2024-01-11 08:14 UTC, Stef3st commented on packages/open-scd/src/editors/protocol104/foundation/cdc.ts
> +    console.log(daElement);
Good catch! Ill remove it

2024-01-11 08:29 UTC, Stef3st commented on packages/open-scd/test/unit/editors/protocol104/wizards/address.test.ts
> +      const cdc = element.wizardUI.dialog!.querySelector(
I dont understand what you mean with this comment. I cast it to a WizardTextField so that I can access the helper property value. What do you suggest?

2024-01-15 10:05 UTC, pascalwilbrink commented on packages/open-scd/test/unit/editors/protocol104/wizards/address.test.ts
> +      const cdc = element.wizardUI.dialog!.querySelector(
.querySelector is a generic, so `.querySelector<WizardTextField>` auto maps it to WizardTextField

2024-01-15 10:32 UTC, Stef3st commented on packages/open-scd/test/unit/editors/protocol104/wizards/address.test.ts
> +      const cdc = element.wizardUI.dialog!.querySelector(
aah right, but thats covered with the `as WizardTextField;` at the end of the queryselector.

2024-01-29 10:06 UTC, pascalwilbrink approved these changes

2024-01-29 10:06 UTC, merged