feat: support ldname attribute
openscd/open-scd pull request #1401
Opened 2023-12-21 15:41 UTC by Stef3st

closes #1326

2024-01-11 13:05 UTC, juancho0202 requested changes
Two very minor comments, it's pretty much all done. Nice!

2024-01-11 14:24 UTC, Stef3st commented on packages/open-scd/test/unit/wizards/ldevice.test.ts
> +    it('ConfLdName should be present in IED1 and therefore ldName should be readonly', async function () {
Oooh nice catch! Thats what you get for copy/pasting ☹️

2024-01-11 14:24 UTC, Stef3st commented on packages/open-scd/test/unit/wizards/ldevice.test.ts
> +  describe('Allowing ldName editing', () => {
Makes more sense as both cases are tested here. Will change it!

2024-01-11 15:22 UTC, DavoodSooran commented
I tested the updated Support LDname feature and it's great that we can now enable/disable the LDname section. However, there's a functionality improvement needed. When enabling LDname and Description, it should require user input before saving. Currently, it's possible to save without entering information, resulting in empty sections in the SCL file. I suggest implementing an error prompt for empty inputs when users try to save after enabling these sections.

![image](https://github.com/openscd/open-scd/assets/146732918/42893408-7777-4395-8675-94ee86bbe0bd)

![image](https://github.com/openscd/open-scd/assets/146732918/f47ca56b-111d-433f-95ba-377925c8781e)

2024-01-11 15:28 UTC, Stef3st commented
@DavoodSooran we then would be tampering with the entire wizarding functionality. If you don't want the elements to be in the SCL then you should disable the fields with the null switch.

2024-01-16 12:06 UTC, juancho0202 approved these changes

2024-01-16 12:08 UTC, merged