Glossary
openscd/open-scd pull request #1407
Opened 2024-01-10 14:48 UTC by DavoodSooran

closes #1345

2024-01-11 08:21 UTC, Sander3003 requested changes

2024-01-11 08:21 UTC, Sander3003 commented on GLOSSARY.MD
> +This is an opinionated glossary of terms developed by the OpenSCD community. Please note that terms specific to the SCL (Substation Configuration Language) fall outside the scope of this glossary, as
Relevant **IEC** standards; The goal of the glossary is helping to get a common understanding of the terms introduced into the OpenSCD project.  This to improve the communication.

2024-01-11 08:21 UTC, Sander3003 commented on GLOSSARY.MD
> +This plug-in is specifically crafted to verify or validate input, data, or code based on predefined rules or standards. Its primary role is to ensure that the information provided meets certain crite
You can keep the explanation to the context of the tool. This is an OpenSCD specifc golossary.

2024-01-11 08:21 UTC, Sander3003 commented on GLOSSARY.MD
> +In software development, distribution is the process of preparing a software application or tool for delivery to end-users. It involves packaging the software in a way that makes it easy to install o
In case of OpenSCD: OpenSCD-core with a selected set of plug-ins and settings (e.g. color scheme). This allows to tailer the OpenSCD to the organisational/individual needs (e.g. my collegues are only allowed to use plug-in X/Y/Z)

2024-01-11 08:21 UTC, Sander3003 commented on GLOSSARY.MD
> +## Plug-in
OpenSCD plug-in needs to comply with Core api's in order to work

2024-01-11 08:21 UTC, Sander3003 commented on GLOSSARY.MD
> +## Menu plug-in
@DavoodSooran maybe you can create an issue to use the term consistant within the OpenSCD UI.

2024-01-11 08:39 UTC, Sander3003 commented
After this first iteration, maybe you can also share it in the slack chat for more review comments / improvement points.

2024-01-31 22:10 UTC, trusz commented
When we are finished, I think squashing the commits would be good.

2024-02-01 07:30 UTC, Sander3003 commented on GLOSSARY.MD
> +This is an opinionated glossary of terms developed by the OpenSCD community. Please note that terms specific to the SCL (Substation Configuration Language) fall outside the scope of this glossary, as
Agree

2024-02-01 15:47 UTC, DavoodSooran commented
@Sander3003 @trusz I have just modified the glossary file based on your comments. you can double check that.

2024-02-05 14:59 UTC, Sander3003 approved these changes
Looks good to me

2024-02-06 12:03 UTC, merged