feat: allow for plugins being passed down as props to `<open-scd>`
openscd/open-scd pull request #1486
Opened 2024-04-03 04:56 UTC by juancho0202

Closes #1418

2024-04-03 14:20 UTC, pascalwilbrink requested changes
The `.plugins` property is not adhering to the `.plugins` property structure of OpenSCD/core

2024-04-04 09:29 UTC, Stef3st requested changes
This PR does met the acceptance criteria described in issue #1418 but most of the tasks described there have not been done. The Plugging mixin was supposed to be removed and a plugin interface should be exported in the Core's foundation file. 

If these tasks are still valid then these changes need to be made. Otherwise the issue needs to be revised.

2024-04-12 07:46 UTC, Stef3st requested changes
Looks good, got a few (small) remarks and a few questions. As stated in the meetings, this PR will have a follow up to no longer merge the 2 plugin interfaces (#1503)

2024-04-15 20:43 UTC, juancho0202 commented on packages/open-scd/.eslintrc.cjs
> +  env: {
<img width="455" alt="Screenshot 2024-04-15 at 22 34 56" src="https://github.com/openscd/open-scd/assets/843030/e364d8d7-f6da-4173-b4d5-1ee8c81c99d5">
I get these lint errors when not specifying the browser as the target environment for the files being linted

2024-05-03 08:14 UTC, pascalwilbrink approved these changes

2024-05-06 15:47 UTC, juancho0202 commented
I added a reactive property __sortedStoredPlugins_ in order to overcome a lifecycle problem I was experiencing by passing down to the Layout addon the _sortedStoredPlugins_ getter like this:

```jsx
<oscd-layout
  .host=${this}
  .doc=${this.doc}
  .docName=${this.docName}
  .editCount=${this.editCount}
  .plugins=${this.sortedStoredPlugins} // <-- When plugins were added to the localStorage this getter wouldn't force a rerender
>
</oscd-layout>
```

I ended up moving the _storePlugins_ function into the OpenSCD class and triggering a change to the reactive prop after the localStorage is updated like this:

```ts
private get sortedStoredPlugins(): Plugin[] {
  return this.storedPlugins
    .map(plugin => {
      if (!plugin.official) return plugin;
      const officialPlugin = (officialPlugins as Plugin[])
        .concat(this.parsedPlugins)
        .find(needle => needle.src === plugin.src);
      return <Plugin>{
        ...officialPlugin,
        ...plugin,
      };
    })
    .sort(compareNeedsDoc)
    .sort(menuCompare);
}

@state()
_sortedStoredPlugins: Plugin[] = [];

private storePlugins(plugins: Array<Plugin | InstalledOfficialPlugin>) {
  localStorage.setItem('plugins', JSON.stringify(plugins.map(withoutContent)));
  this._sortedStoredPlugins = this.sortedStoredPlugins;
}
```

And then the reactive property __sortedStoredPlugins_ is passed down to the Layout like this:

```jsx
<oscd-layout
  .host=${this}
  .doc=${this.doc}
  .docName=${this.docName}
  .editCount=${this.editCount}
  .plugins=${this._sortedStoredPlugins}
>
</oscd-layout>
```

@pascalwilbrink let me know if you agree with my approach here, these were some tricky merge conflicts. Thanks for the review.

2024-05-07 15:46 UTC, merged