chore: create oscd-layout addon
openscd/open-scd pull request #1510
Opened 2024-04-24 07:35 UTC by juancho0202

Some decisions taken here that I think award a discussion:

- former Plugging mixin rendering functionality was separated into the oscd-layout addon
  - snapshot test which kept track of the hosting UI and plugins is now under a separate snapshot test for the layout addon
- a "position: absolute; top: 0" style was added to the mwc-drawer to stick it to the top
- the private get plugins array was awarded a @state annotation and a setter in order to use Lit's reactivity (plus I added a requestUpdate on the open-scd tag whenever someone adds a new external plugin)

2024-04-29 07:14 UTC, pascalwilbrink requested changes

2024-04-29 07:14 UTC, pascalwilbrink commented on packages/open-scd/test/mock-open-scd.ts
> +    ${this.renderHosting()}
RenderHosting can be removed, already being called by `super.render()`

2024-04-29 07:14 UTC, pascalwilbrink commented on packages/open-scd/src/open-scd.ts
> +                .docName=${this.docName}
.editCount should also be added if doc is being passed down

2024-05-01 06:44 UTC, juancho0202 commented on packages/open-scd/test/mock-open-scd.ts
> +    ${this.renderHosting()}
renderHosting does not exist in the OpenSCD class anymore only in mock-open-scd, that's why it's needed in this case. Maybe we can do without `renderHosting` and just have:

```ts
render(): TemplateResult {
    return html`
    <slot></slot>
    ${super.render()}`;
}
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { Drawer } from '@material/mwc-drawer';
```suggestion
import type { Drawer } from '@material/mwc-drawer';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { ActionDetail, List } from '@material/mwc-list';
```suggestion
import type { ActionDetail, List } from '@material/mwc-list';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { ListItem } from '@material/mwc-list/mwc-list-item';
```suggestion
import type { ListItem } from '@material/mwc-list/mwc-list-item';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { Dialog } from '@material/mwc-dialog';
```suggestion
import type { Dialog } from '@material/mwc-dialog';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { MultiSelectedEvent } from '@material/mwc-list/mwc-list-foundation.js';
```suggestion
import type { MultiSelectedEvent } from '@material/mwc-list/mwc-list-foundation.js';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { Select } from '@material/mwc-select';
```suggestion
import type { Select } from '@material/mwc-select';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { Switch } from '@material/mwc-switch';
```suggestion
import type { Switch } from '@material/mwc-switch';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +import { TextField } from '@material/mwc-textfield';
```suggestion
import type { TextField } from '@material/mwc-textfield';
```

2024-05-01 13:45 UTC, pascalwilbrink commented on packages/open-scd/src/addons/Layout.ts
> +
```suggestion

import '@material/mwc-drawer';
import '@material/mwc-list';
import '@material/mwc-dialog';
import '@material/mwc-switch';
import '@material/mwc-select';
import '@material/mwc-textfield';

```

2024-05-02 09:43 UTC, pascalwilbrink approved these changes
LGTM!

2024-05-02 10:01 UTC, merged