Feat: Added XML Package for OpenSCD
openscd/open-scd pull request #1536
Opened 2024-05-24 11:50 UTC by pascalwilbrink

2024-06-03 15:39 UTC, juancho0202 requested changes
Everything looks well executed in the extraction, my only concern is that the migrated tests from `packages/open-scd` to `packages/xml` are not being executed because there is no test script and no devDependency on "@web/test-runner" at the `@openscd/xml` project.
If you add that missing bit this is complete imo.

2024-06-06 14:49 UTC, juancho0202 approved these changes
I am approving because I think it's done, just needs the removal of the duplicated CONTRIBUTING guide but functional and code wise it's done.

2024-06-06 14:49 UTC, juancho0202 commented on packages/xml/CONTRIBUTING.md
I don't think this CONTRIBUTING guide goes in `packages/xml`

2024-06-07 07:50 UTC, pascalwilbrink commented on packages/xml/CONTRIBUTING.md
Deleted

2024-06-07 10:16 UTC, merged