feat(communicationmapping): add commMappingWizard and cbConnectionWizard
openscd/open-scd pull request #169
Opened 2021-04-03 22:39 UTC by JakobVogelsang

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/editors/communicationmapping.test.ts
> +      expect(getControlBlockConnection(doc, 'ReportControl')).to.have.length(2);
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      expect(getControlBlockConnection(doc, "ReportControl")).to.have.length(2);
```

2021-04-03 22:41 UTC, c-dinkel commented on src/filtered-list.ts
> +        '\n' +
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
        "\n" +
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/editors/communicationmapping.test.ts
> +  describe('getConnectionIndexOf', () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
  describe("getConnectionIndexOf", () => {
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/foundation.test.ts
> +    it('returns empty array if input not FCDA', () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("returns empty array if input not FCDA", () => {
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/editors/communicationmapping.test.ts
> +          ':root > IED[name="IED1"] LDevice[inst="CircuitBreaker_CB1"] DataSet > FCDA[lnClass="XCBR"][lnInst="1"][doName="Pos"]'
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
          ":root > IED[name=\"IED1\"] LDevice[inst=\"CircuitBreaker_CB1\"] DataSet > FCDA[lnClass=\"XCBR\"][lnInst=\"1\"][doName=\"Pos\"]"
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/foundation.test.ts
> +    it('returns an array of ExtRef connected to the FCDA', () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("returns an array of ExtRef connected to the FCDA", () => {
```

2021-04-03 22:41 UTC, c-dinkel commented on src/filtered-list.ts
> +          .join('\n');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
          .join("\n");
```

2021-04-03 22:41 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +import { LitElement } from 'lit-element';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
import { LitElement } from "lit-element";
```

2021-04-03 22:41 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +    it('indicates the control block type with mwc-list graphic slot', () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("indicates the control block type with mwc-list graphic slot", () => {
```

2021-04-03 22:41 UTC, c-dinkel commented on src/triggered/wizards.ts
> +    if (extRef.getAttribute('serviceType'))
Codacy has a fix for the issue: [Expected { after 'if' condition.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    if (extRef.getAttribute('serviceType'))
```

2021-04-03 22:41 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +      .then(str => new DOMParser().parseFromString(str, 'application/xml'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      .then(str => new DOMParser().parseFromString(str, "application/xml"));
```

2021-04-03 22:41 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +        match.source.closest('IED')?.getAttribute('name') &&
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
        match.source.closest("IED")?.getAttribute('name') &&
```

2021-04-03 22:41 UTC, c-dinkel commented on src/triggered/wizards.ts
> +        '.' +
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
        "." +
```

2021-04-03 22:41 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +    it('removes selected ExtRefs in case no intAddr is present', async () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("removes selected ExtRefs in case no intAddr is present", async () => {
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/filtered-list.test.ts
> +      element.searchField.value = 'item2sec';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      element.searchField.value = "item2sec";
```

2021-04-03 22:41 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +        parent.wizardUI.dialog?.querySelectorAll('mwc-check-list-item').length
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
        parent.wizardUI.dialog?.querySelectorAll("mwc-check-list-item").length
```

2021-04-03 22:41 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +    const goose = getDataConnection(this.doc, 'GSEControl');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    const goose = getDataConnection(this.doc, "GSEControl");
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/foundation.test.ts
> +        ':root > IED[name="IED2"] > AccessPoint > Server > LDevice[inst="CBSW"] > LN0 > DataSet > FCDA[daName="stVal"]'
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
        ":root > IED[name=\"IED2\"] > AccessPoint > Server > LDevice[inst=\"CBSW\"] > LN0 > DataSet > FCDA[daName=\"stVal\"]"
```

2021-04-03 22:41 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +    .flatMap(controlBlock => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    .flatMap((controlBlock) => {
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/filtered-list.test.ts
> +    { prim: 'item1', sec: 'item1sec' },
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    { prim: "item1", sec: 'item1sec' },
```

2021-04-03 22:41 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +    it('updates selected ExtRefs in case intAddr is present', async () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("updates selected ExtRefs in case intAddr is present", async () => {
```

2021-04-03 22:41 UTC, c-dinkel commented on test/unit/filtered-list.test.ts
> +  describe('onFilterInput', () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
  describe("onFilterInput", () => {
```

2021-04-03 22:41 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +    data.map(fcda => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    data.map((fcda) => {
```

2021-04-03 22:47 UTC, c-dinkel commented on src/triggered/wizards.ts
> +    if (extRef.getAttribute('intAddr'))
Codacy has a fix for the issue: [Expected { after 'if' condition.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    if (extRef.getAttribute('intAddr'))
```

2021-04-03 22:47 UTC, c-dinkel commented on src/triggered/wizards.ts
> +import { html } from 'lit-element';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
import { html } from "lit-element";
```

2021-04-03 22:47 UTC, c-dinkel commented on test/unit/filtered-list.test.ts
> +    it('filteres within twoline mwc-list-item', async () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("filteres within twoline mwc-list-item", async () => {
```

2021-04-03 22:47 UTC, c-dinkel commented on test/unit/editors/communicationmapping.test.ts
> +        getDataConnection(doc, 'SampledValueControl')[3].sink
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
        getDataConnection(doc, "SampledValueControl")[3].sink
```

2021-04-03 22:47 UTC, c-dinkel commented on test/unit/filtered-list.test.ts
> +    it('uses space as logic AND ', async () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("uses space as logic AND ", async () => {
```

2021-04-03 22:47 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +        parent.wizardUI.dialog?.querySelectorAll('mwc-list-item').length
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
        parent.wizardUI.dialog?.querySelectorAll("mwc-list-item").length
```

2021-04-03 22:47 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +  LogControl: 'ClientLN',
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
  LogControl: "ClientLN",
```

2021-04-03 22:47 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +      list[i].source.getAttribute('name') ===
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      list[i].source.getAttribute("name") ===
```

2021-04-03 22:47 UTC, c-dinkel commented on test/unit/filtered-list.test.ts
> +      expect(element.items[2].style.display).to.equal('');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      expect(element.items[2].style.display).to.equal("");
```

2021-04-03 22:47 UTC, c-dinkel commented on test/unit/editors/communicationmapping.test.ts
> +      expect(getControlBlockConnection(doc, 'ReportControl')[0]).to.deep.equal({
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      expect(getControlBlockConnection(doc, "ReportControl")[0]).to.deep.equal({
```

2021-04-03 22:47 UTC, c-dinkel commented on src/triggered/wizards.ts
> +    items.forEach(index => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    items.forEach((index) => {
```

2021-04-03 22:47 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +    it('updates selected ExtRefs in case intAddr is present', async () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("updates selected ExtRefs in case intAddr is present", async () => {
```

2021-04-03 22:47 UTC, c-dinkel commented on src/filtered-list.ts
> +      const terms: string[] = this.searchField.value.split(' ');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      const terms: string[] = this.searchField.value.split(" ");
```

2021-04-03 22:47 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +    it('opens on Connection item click', async () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("opens on Connection item click", async () => {
```

2021-04-03 22:47 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +    it('indicates the control block type with mwc-list graphic slot', () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    it("indicates the control block type with mwc-list graphic slot", () => {
```

2021-04-03 22:47 UTC, c-dinkel commented on src/triggered/wizards.ts
> +import '../filtered-list.js';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
import "../filtered-list.js";
```

2021-04-03 22:47 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +      await new Promise(resolve => setTimeout(resolve, 100)); // await animation
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      await new Promise((resolve) => setTimeout(resolve, 100)); // await animation
```

2021-04-03 22:47 UTC, c-dinkel commented on src/triggered/CommunicationMapping.ts
> +      list[i].source.closest('IED')?.getAttribute('name') ===
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      list[i].source.closest("IED")?.getAttribute('name') ===
```

2021-04-03 22:47 UTC, c-dinkel commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +            '[doName="Pos"][daName="stVal"][intAddr="./stVal"][serviceType="GOOSE"][desc="testDesc"]' +
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
            "[doName=\"Pos\"][daName=\"stVal\"][intAddr=\"./stVal\"][serviceType=\"GOOSE\"][desc=\"testDesc\"]" +
```

2021-04-03 22:48 UTC, c-dinkel commented on src/triggered/wizards.ts
> +    if (extRef.getAttribute('desc'))
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
    if (extRef.getAttribute("desc"))
```

2021-04-03 22:48 UTC, c-dinkel commented on test/unit/filtered-list.test.ts
> +      element.searchField.value = 'item item3sec';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
      element.searchField.value = "item item3sec";
```

2021-04-03 22:48 UTC, c-dinkel commented on test/unit/editors/communicationmapping.test.ts
> +  describe('getControlBlockConnection', () => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/openscd/open-scd/pullRequest?prid=7203429)
```suggestion
  describe("getControlBlockConnection", () => {
```

2021-04-07 10:35 UTC, c-dinkel requested changes
I have not looked at `CommunicationMapping.ts` or `triggered/wizards.ts` yet, review of these will follow.

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +  //HACK: tfContainer only for CSS width adjustment 100% does not work
This seems to explain itself, the comment isn't really needed.

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +  static styles = css`
This css does not include `suber.styles` : how is this even working?

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +    #tfContainer {
CSS selectors are case insensitive, mixed case attributes are generally not a great idea, see e.g. [this SE answer](https://stackoverflow.com/questions/1236856/in-the-dom-are-node-ids-case-sensititve#29864886) .

I suggest always using something other than `id`, like e.g. `class`, to identify elements for the sole purpose of CSS styling.

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +        ? item.setAttribute('style', 'display:none;')
Would it be cleaner to use `item.classList.add('hidden')` and `item.classList.remove('hidden')` and do the styling in the static CSS below?

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +        .some(item => item === false)
Calling this `item` shadows `item` from the level above and reads confusingly. How about writing it `.some(isMatch => !isMatch)`?

At that point, why not skip the `map` above and go straight for `.some(term => !value.includes(term)`?

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +        .map(term => value.toUpperCase().includes(term.toUpperCase()))
We could save on calling `toUpperCase` on both the text and the term so often if we upperCase both beforehand.

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +      const value: string =
If we really do not want to include the list item's `value` attribute here, `text` may be a more descriptive name for this constant. It could also be upperCased right here.

2021-04-07 10:35 UTC, c-dinkel commented on src/filtered-list.ts
> +          .map(child => child.innerHTML)
Why do we need `innerHTML` here when `innerText` is good enough above?

2021-04-07 10:35 UTC, c-dinkel commented on src/translations/de.ts
> +    'comm-map': { wizard: { title: 'Kommunikationszuordnung' } },
Could we come up with a more idiomatic key than 'comm-map' for this translation, more in line with other translation keys?

Also, if there are not many more translations coming, do we need such a deep structure here?

2021-04-07 19:21 UTC, JakobVogelsang commented on src/filtered-list.ts
> +          .map(child => child.innerHTML)
Because `innerText` is not defined on `Element`. I wanted to avoid a type cast. We could also use `textContent` to avoid a type cast.

2021-04-11 16:46 UTC, merged