feat(communicationmapping): move to ied-editor
openscd/open-scd pull request #270
Opened 2021-07-27 15:30 UTC by JakobVogelsang

Closes #225

2021-07-29 14:13 UTC, ca-d requested changes
A move Substation button is the only thing that's obviously missing, UX feedback will be forthcoming as soon as I've done manual testing.

2021-07-29 14:13 UTC, ca-d commented on src/zeroline/substation-editor.ts
>          ${this.renderHeader()}
Since we support multiple `Substation` sections now, the header could probably use a `move` button.

2021-07-29 14:17 UTC, ca-d commented on src/zeroline/bay-editor.ts
>          ${until(
Do you think it would be worth trying this synchronously again now that we have a faster algorithm for placing IEDs? If the performance is acceptable, this would remove the flickering when manually requesting Updates, e.g. in wizards.

2021-07-29 14:39 UTC, ca-d commented
The `ied-editor` doesn't appear clickable because of the following typo:

```css
 #container:hover > .icom {
 ```
 
 (should be `.icon` instead of `.icom`)

2021-07-29 14:44 UTC, ca-d commented
I suggest we use two separate `mwc-icon-button`s in the `zeroline-pane` for connecting and disconnecting reports, in order to save a click and remove the "connect report" primary action from the "Communication Mapping" wizard.

Then we would have:
* One button in `zeroline-pane` for disconnecting any report (like it is now, but without the "connect" action)
* One button per `ied-editor` for disconnecting reports involving it (like it is now, but without the "connect" action)
* One button in `zeroline-pane` for connecting any two IEDs with reports (to be refactored into per-`ied-editor` buttons later)

2021-07-29 14:45 UTC, ca-d commented
The `ied-editor` currently still displays the default text caret [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) and allows [user selection](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) of the icon text (developer_board).

2021-07-29 14:49 UTC, ca-d commented on test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
> +      await element.commmap.click();
We don't actually need to `await` a `click()`, since it doesn't return a `Promise`.

2021-07-29 14:55 UTC, ca-d commented on test/unit/wizards/clientln.test.ts
> +        await new Promise(resolve => setTimeout(resolve, 100)); // await animation
Could we try to await something like `parent.wizardUI.updateComplete` and then `parent.wizardUI.dialog.updateComplete` instead of these timeouts? The more of these setTimeout promises we use, the longer the test suite takes, and I have some hope that the actual animation may be slightly (~20ms) quicker than we guess here. It's not a huge difference in the individual case, but here we have many timeouts, so it might add up to a significant fraction of a second.

2021-07-29 14:57 UTC, ca-d commented on test/unit/wizards/controlwithiedname.test.ts
> +  it('updates selected ExtRefs in case intAddr is present', async () => {
Again, great tests, but a few extra empty lines would help me in reading.

2021-07-29 14:58 UTC, ca-d commented on src/translations/en.ts
> +  commmap: {
Was there a particular reason to change this back to `commap`, or just taste?

2021-07-29 14:59 UTC, ca-d commented on src/translations/en.ts
> -  commMap: {
Was there a particular reason to change this back to `commap`, or just taste?

2021-07-29 15:03 UTC, ca-d commented on src/wizards/commmap-wizards.ts
> +                evt.target!.dispatchEvent(
😍  This is much more readable than the original from the plugin, great job!

2021-07-29 18:18 UTC, JakobVogelsang commented on test/unit/wizards/clientln.test.ts
> +        await new Promise(resolve => setTimeout(resolve, 100)); // await animation
This was not really necessary after rewriting the tests. :)

2021-07-29 18:19 UTC, JakobVogelsang commented on src/translations/en.ts
> -  commMap: {
Just a taste. I found it strange to use an upper case letter in such a short word.

2021-07-29 18:20 UTC, JakobVogelsang commented on src/wizards/commmap-wizards.ts
> +                evt.target!.dispatchEvent(
:)

2021-07-29 18:24 UTC, JakobVogelsang commented
> 
> 
> I suggest we use two separate `mwc-icon-button`s in the `zeroline-pane` for connecting and disconnecting reports, in order to save a click and remove the "connect report" primary action from the "Communication Mapping" wizard.
> 
> Then we would have:
> 
>     * One button in `zeroline-pane` for disconnecting any report (like it is now, but without the "connect" action)
> 
>     * One button per `ied-editor` for disconnecting reports involving it (like it is now, but without the "connect" action)
> 
>     * One button in `zeroline-pane` for connecting any two IEDs with reports (to be refactored into per-`ied-editor` buttons later)

Your suggestion sounds already very good. The only thing that I have saved is the disconnecting on the IED level. Access to it is the communication anyway, and the extra effort and complexity on IED level seemed to be too much for the benefits.

2021-07-30 05:51 UTC, JakobVogelsang commented on __snapshots__/clientln connection wizards.md
> +          style="height:56px"
This wizard is deleted now!

2021-07-30 08:19 UTC, ca-d approved these changes
LGTM 🥳

2021-07-30 11:25 UTC, merged