feat(abstractda): add val manipulation capability
openscd/open-scd pull request #275
Opened 2021-07-31 11:14 UTC by JakobVogelsang

Closes #274

2021-08-02 11:36 UTC, ca-d requested changes
This looks and reads extremely well. The only thing that sticks out to me is the `foundation.ts` directory name which looks like a TypeScript file.

2021-08-02 11:36 UTC, ca-d commented on src/wizard-select.ts
> -      this.setCustomValidity(get('textfield.unique'));
Great change 🎉 ! Does this mean we could also get rid of the `textfield.unique` translation, or do we still need it in the `wizard-textfield`?

2021-08-02 11:36 UTC, ca-d commented on src/wizards/abstractda.ts
> +export function getValAction(
Do you generally prefix functions like this with `get` or would

```ts
export function valAction(
```

also work for you?

2021-08-02 11:36 UTC, ca-d commented on src/wizards/bda.ts
> +      else newElement.setAttribute('valImport', valImport);
Maybe we could think about refactoring blocks like this into a helper function in our `foundation` in the future. How common do you think these if/else blocks are going to be?

2021-08-02 11:36 UTC, ca-d commented on src/wizards/foundation.ts/enums.ts
> +export const functionalConstraintEnum = [
Why does the `wizards/foundation` directory carry a `.ts` extension?

2021-08-03 09:02 UTC, JakobVogelsang commented on src/wizard-select.ts
> -      this.setCustomValidity(get('textfield.unique'));
At the moment, we still use it to check for name attribute duplication.

2021-08-03 09:10 UTC, JakobVogelsang commented on src/wizards/abstractda.ts
> +export function getValAction(
We do this at the moment for `Voltage` for example and will do so for `MinTime`, `MaxTime` ....
Those are child elements  that in our wizards appear as attributes. 

Working on the wizards, I found that we should talk about a naming convention here. I would therefore postpone this to [Issue](https://github.com/openscd/open-scd/issues/281)

2021-08-03 09:13 UTC, JakobVogelsang commented on src/wizards/bda.ts
> +      else newElement.setAttribute('valImport', valImport);
This is very true. This pattern is very common and can be avoided with a simple function [Issue](https://github.com/openscd/open-scd/issues/282)

2021-08-03 09:13 UTC, JakobVogelsang commented on src/wizards/foundation.ts/enums.ts
> +export const functionalConstraintEnum = [
This is a typo, sorry :)

2021-08-03 12:41 UTC, ca-d approved these changes
LGTM

2021-08-03 12:42 UTC, merged