feat(menu/UpdateDescritionABB): update ExtRef with internal signal description
openscd/open-scd pull request #374
Opened 2021-11-12 19:47 UTC by JakobVogelsang

2021-11-16 15:43 UTC, ca-d commented
Does this pull request have an associated issue? If not, should we add Assignee (JakVog), Labels, and Project directly here? Do we even have an appropriate project or don't we want to track this work on our boards?

2021-11-16 15:57 UTC, ca-d requested changes
I request a change only to the new translation introduced, the pull request refactor is more of a suggestion.

2021-11-16 15:57 UTC, ca-d commented on src/foundation.ts
> +        srcLNClass ?? ''
Should these two fixes (this and line 692) maybe go into their own pull request with their own associated issue and regression test?

2021-11-16 15:57 UTC, ca-d commented on src/translations/de.ts
> +    updatedesc: 'Signalbeschreibungen zu {{manufacturer}} IEDs hinzugefügt',
I think `menu` should probably only contain built-ins, plugin translations should go into their own namespaces. (Also, this translation is for a log entry, not a menu entry.)

In my opinion it would be worth it to replicate this translation effort vendor dependently for each plugin.

2021-11-16 15:57 UTC, ca-d commented on src/translations/en.ts
> +    updatedesc: 'Add signal descriptions to {{manufacturer}} IEDs',
This says "add" (like a menu entry), the German translation says "added" (like a log entry, which is how this is actually being used as far as I can see).

2021-11-16 16:00 UTC, ca-d commented on src/menu/UpdateDescriptionABB.ts
> +    const items = Array.from(this.doc.querySelectorAll('IED')).flatMap(ied =>
Should this say `':root > IED'` just to be safe?

2021-11-16 21:44 UTC, JakobVogelsang commented on src/translations/de.ts
> +    updatedesc: 'Signalbeschreibungen zu {{manufacturer}} IEDs hinzugefügt',
Agreed!

2021-11-16 21:45 UTC, JakobVogelsang commented on src/translations/en.ts
> +    updatedesc: 'Add signal descriptions to {{manufacturer}} IEDs',
Agreed

2021-11-16 21:45 UTC, JakobVogelsang commented on src/menu/UpdateDescriptionABB.ts
> +    const items = Array.from(this.doc.querySelectorAll('IED')).flatMap(ied =>
Agreed!

2021-11-16 22:00 UTC, JakobVogelsang commented on src/foundation.ts
> +        srcLNClass ?? ''
Yes we should. I would love to do that when refactoring identity and selector out of the foundation and with it write more and more specific tests especially for the more complex element like `ExtRef`. What do you think about this?

2021-11-18 17:53 UTC, ca-d commented on src/foundation.ts
> +        srcLNClass ?? ''
Sounds good.

2021-11-18 17:54 UTC, ca-d approved these changes
LGTM

2021-11-18 17:54 UTC, merged