First version IED editor
openscd/open-scd pull request #423
Opened 2021-12-10 13:56 UTC by Flurb

2021-12-16 09:40 UTC, JakobVogelsang requested changes

2021-12-16 09:40 UTC, JakobVogelsang commented on src/editors/IEDEditor.ts
> +        ${Array.from(this.doc?.querySelectorAll(this.query) ?? []).map(
I think querySelectorAll always returns an array so the ?? [] is not necessary.

2021-12-16 09:40 UTC, JakobVogelsang commented on src/editors/IEDEditor.ts
> +    #iedSearch {
Maybe iedselect would be fit better.

2021-12-16 09:40 UTC, JakobVogelsang commented on src/editors/IEDEditor.ts
> +      transition: background-color 150ms linear;
This CSS rule is not necessary. SORRY, I know this is used in another plugin and our codebase is not consistent :(
This rule is used when we do transition. E.g. to hovered or to focused rules. This is not the case here.

2021-12-16 09:40 UTC, JakobVogelsang commented on src/editors/IEDEditor.ts
> +                value="${getNameAttribute(ied)}"
value consumes strings only and getNameAttribute returns string | null

2021-12-16 09:40 UTC, JakobVogelsang commented on src/editors/IEDEditor.ts
> +  query:string = IEDSelector.IED;
I would suggest using a more specific name. I was confused, looking at it for the first glance.

2021-12-16 09:40 UTC, JakobVogelsang commented on public/js/plugins.js
> +    src: '/src/editors/IEDEditor.js',
may `IED` would fit better to the current naming for editor type plugins

2021-12-16 09:40 UTC, JakobVogelsang commented on src/editors/ied/ldevice-container.ts
> +import '../../action-pane.js';
Order of imports. Sorry very picky

2021-12-16 09:40 UTC, JakobVogelsang commented on src/editors/ied/ln-container.ts
> +import './do-container.js';
Remove for now

2021-12-16 09:40 UTC, JakobVogelsang commented on test/integration/editors/ied/IEDEditor.test.ts
> +  customElements.define(
A check before definition is necessary here. This might lead to crashing tests if we do the same definition in e.g. uni tests some day

2021-12-16 09:40 UTC, JakobVogelsang commented on test/integration/editors/ied/IEDEditor.test.ts
> +    it('it initially contains 1 rendered IED container', () => {
Spaces between test are very beneficial for readability. Again, sorry I know this is inconsistent in the code base, but I do it in my latest commits.

2021-12-16 09:40 UTC, JakobVogelsang commented on test/integration/editors/ied/IEDEditor.test.ts
> +  describe('with a doc loaded including IED sections', () => {
A snapshot capturing the structure of the IED editor with a loaded doc might be nice. Whenever we change something by mistake, we will see it then.

2021-12-16 09:40 UTC, JakobVogelsang commented on test/unit/editors/ied/ln-container.test.ts
> +      // TODO: Need to test both LN and LN0!
This I would say is realy important to test. The structure shall be used for both the two elements

2021-12-16 10:24 UTC, JakobVogelsang commented on src/editors/ied/ldevice-container.ts
> +  static styles = css``;
Maybe rendering ln-container elements into a grid would be beneficial. We do the same thing with bay-editor like so

```
#bayContainer {
      display: grid;
      grid-gap: 12px;
      box-sizing: border-box;
      grid-template-columns: repeat(auto-fit, minmax(316px, auto));
    }

    @media (max-width: 387px) {
      #bayContainer {
        grid-template-columns: repeat(auto-fit, minmax(196px, auto));
      }
    }
```

2021-12-16 10:46 UTC, Flurb commented on src/editors/ied/do-container.ts
> +import {
True, this is for the next story :)

2021-12-16 11:18 UTC, Flurb commented on src/editors/IEDEditor.ts
> +/** An editor [[`plugin`]] for editing the `IED Editor` section. */
I meant an IED XML section (indirect reference), but IED makes more sense then yes :)

2021-12-16 11:22 UTC, Flurb commented on src/editors/IEDEditor.ts
> +    .sort((a,b) => (getNameAttribute(a)! > getNameAttribute(b)!) ? 1 : -1);
It does! Thanks!

2021-12-16 11:26 UTC, Flurb commented on src/editors/IEDEditor.ts
> +  get alphabeticOrderedIeds() : Element[] {
I didn't know private was a thing in Typescript!
Of course we make this private! :D

2021-12-16 11:29 UTC, Flurb commented on src/editors/IEDEditor.ts
> +        ${Array.from(this.doc?.querySelectorAll(this.query) ?? []).map(
Yes, my bad. If there are no elements to be found, it returns an empty NodeList[]. I'll fix it.

2021-12-16 11:32 UTC, Flurb commented on src/editors/IEDEditor.ts
> +    #iedSearch {
Yes, you can't search indeed :)

2021-12-16 11:38 UTC, Flurb commented on src/editors/IEDEditor.ts
> +                value="${getNameAttribute(ied)}"
Is it safe to say IEDs always have a name?

2021-12-16 11:47 UTC, Flurb commented on src/editors/ied/access-point-container.ts
> +    return `${name} ${desc ? `\u2014 ${desc}` : ''}`;
Using &mdash; in string here would render it to &mdash; and not the character itself.

Would the best solution be to change the return type of header to TemplateResult? Or what is the best solution here?

2021-12-16 12:18 UTC, JakobVogelsang commented on src/editors/IEDEditor.ts
> +                value="${getNameAttribute(ied)}"
Not really it is a required attribute, however I would not relay on it. What do you think about UNDEFINED? This is what I often use in such a case.

2021-12-20 09:53 UTC, Flurb commented on test/integration/editors/ied/IEDEditor.test.ts
> +  describe('with a doc loaded including IED sections', () => {
These tests are already added below. Do you think they can be extended? @JakobVogelsang

2021-12-20 09:54 UTC, Flurb commented on test/unit/editors/ied/ln-container.test.ts
> +      // TODO: Need to test both LN and LN0!
Yes good one! Forgot to edit it :)

2021-12-20 10:33 UTC, Flurb commented on src/editors/ied/ldevice-container.ts
> +  static styles = css``;
Yes I already added it :)

2021-12-20 21:54 UTC, JakobVogelsang requested changes
The icon change would be nice, all the reset is very minor.

2021-12-20 21:54 UTC, JakobVogelsang commented on public/js/plugins.js
> +    icon: 'edit',
Sorry, have overlooked this. Maybe we could reuse the icon we use for the `ied-editor` in the Substation editor type plugin? Or was the icon on purpose?

2021-12-20 21:54 UTC, JakobVogelsang commented on src/editors/ied/ied-container.ts
> +  static styles = css``;
This is not needed. I would remove this.

2021-12-20 21:54 UTC, JakobVogelsang commented on src/editors/ied/ldevice-container.ts
> +    <div id="bayContainer">
`bayContainer` is I guess a copy error. I think it would be better to give it a more precise name.

2021-12-20 21:54 UTC, JakobVogelsang commented on src/editors/ied/ln-container.ts
> +  static styles = css``;
Same here I would remove this

2021-12-20 21:54 UTC, JakobVogelsang commented on src/editors/ied/server-container.ts
> +  static styles = css``;
Same here. I would remove it

2021-12-20 21:54 UTC, JakobVogelsang commented on test/integration/editors/ied/IEDEditor.test.ts
> +  describe('with a doc loaded including IED sections', () => {
Sorry just saw this. LGTM

2022-01-10 20:53 UTC, JakobVogelsang approved these changes
LGTM

2022-01-11 07:11 UTC, merged