feat(SubstationSelectorInSLD): Added selector for Substation in SLD
openscd/open-scd pull request #449
Opened 2021-12-20 13:41 UTC by dlabordus

- Added Substation Selector in the SLD Editor. This was needed, because with multiple substations the elements are overlapping, because all substations start drawing from position 0,0.
- Fixed drawing Connectivity Nodes when there is no SubstationName/VoltgaeLevelName/BayName attribute on the Terminal. These attributes are optional in the XML and should only be check if available.
- Refactoring drawing the SVG for a Substation. 

Pull Request resolves #416

2021-12-20 22:35 UTC, JakobVogelsang requested changes
Some very minor changes would be nice. Other than that LGTM :)

2021-12-20 22:35 UTC, JakobVogelsang commented on src/schemas.ts
> + * Check if the namespace of tjhe passed element is the standard SCL Namespace.
typo

2021-12-20 22:35 UTC, JakobVogelsang commented on src/editors/SingleLineDiagram.ts
> +      .filter(isSCLNamespace)
I don't get why you filter for `isSCLNamespace`. What do I miss?

2021-12-20 22:35 UTC, JakobVogelsang commented on src/editors/SingleLineDiagram.ts
> +    const substationGroup = createVoltageLevelElement(this.selectedSubstation!);
The naming in this line is missleading :)

2021-12-20 22:35 UTC, JakobVogelsang commented on src/editors/SingleLineDiagram.ts
> +      transition: background-color 150ms linear;
This rule is not used as there is no transition.

2021-12-20 22:35 UTC, JakobVogelsang commented on src/editors/SingleLineDiagram.ts
> +    #substationSelector {
I would prefer to have a margin around the selector at least top and left I woudl say

2021-12-21 06:26 UTC, dlabordus commented on src/editors/SingleLineDiagram.ts
> +      .filter(isSCLNamespace)
For this query it can be removed, because at root level there is only SCL Substation possible.

But the reason I'm doing it at other level is because RTE is talking about adding a Compas Extension for Bay/VoltageLevel/.... This means we will get multiple Namespaces using the same Element names. QuerySelector doesn't look at the namespace, so it would be cleaner to only pickup the SCL elements and not all kind of privates that are there with the same name.

2021-12-21 06:26 UTC, dlabordus commented on src/editors/SingleLineDiagram.ts
> +    const substationGroup = createVoltageLevelElement(this.selectedSubstation!);
I saw it also when working at the editors (other issue). Will fix this.

2021-12-21 06:27 UTC, dlabordus commented on src/editors/SingleLineDiagram.ts
> +      transition: background-color 150ms linear;
This is currently copied from the Substation Editor. What example is better?

2021-12-21 06:38 UTC, dlabordus commented on src/schemas.ts
> + * Check if the namespace of tjhe passed element is the standard SCL Namespace.
Fixed

2021-12-21 06:46 UTC, dlabordus commented on src/editors/SingleLineDiagram.ts
> +      transition: background-color 150ms linear;
I just removed the transition. Remark: all editor still contain this style :-)

2021-12-21 06:46 UTC, JakobVogelsang commented on src/editors/SingleLineDiagram.ts
> +      transition: background-color 150ms linear;
Yes I know :). This is not completely clean there too. It is only the one line.

2021-12-21 08:53 UTC, JakobVogelsang approved these changes
LGTM

2021-12-21 15:56 UTC, merged