Add earth-switch symbol
openscd/open-scd pull request #460
Opened 2021-12-29 07:46 UTC by danyill

Closes #459 by providing an earth switch icon and using this in the various editors and wizards.

The logic for ESR detection shouldn't be in multiple places but it may be like this for a very good reason so I have not modified it.

In the SLD:

![image](https://user-images.githubusercontent.com/674783/147638528-78288fe5-f0bd-43cb-af85-3aa40f365601.png)

In the Substation Editor:

![image](https://user-images.githubusercontent.com/674783/147638620-fe3f8120-9e35-4f3d-81d0-660d8ec08162.png)

I'll be happy to take a review and make modifications.

I've tried to keep the icon square while retaining the stroke width but happy to take some feedback as to whether this is visually acceptable. Another option to introduce spacing might be to make the switch portion smaller or the earth symbol smaller.

2022-01-06 16:11 UTC, JakobVogelsang commented
I am wondering where you got the icon from. Initially, the vertical line at the bottom is representing the earth connection. You see that with the voltage transformer for example as well (`VTR`). Like you are proposing it at the moment, I would say it is earthed on both terminals. You said there is a standard for such elements: is it how it is recommended there?

2022-01-06 16:14 UTC, JakobVogelsang commented
Also, as you are on this topic already I also would encourage you to add some more logic into distinguishing earth switches, that is proposed in this issue #267.

2022-01-07 23:09 UTC, danyill commented
> I am wondering where you got the icon from. Initially, the vertical line at the bottom is representing the earth connection.

Ah, that was not at all obvious to me. Perhaps that's a European standard I'm unfamiliar with:

FWIW, IEC 60617 uses the following for a VT:

![image](https://user-images.githubusercontent.com/674783/148461418-a55f13c7-16b8-4d3e-83eb-7361e39ffa32.png)

And for a combined disconnector/earthing switch:

![image](https://user-images.githubusercontent.com/674783/148461502-47968f76-a2b8-466f-be4d-431a16b14e6f.png)

And for a disconnector:

![image](https://user-images.githubusercontent.com/674783/148461616-5e62a34d-4fe8-477f-88a7-3321bff96e66.png)

But I cannot find a clean combined symbol called an "earth switch" or "earthing switch". So the symbol is literally intended to connect the two symbols.

Our in-house standard symbol for an earth switch is:

![image](https://user-images.githubusercontent.com/674783/148462295-4e79bda5-39ba-4421-9d4a-2c9509a162b2.png)

I've combined the existing disconnector icon in open-scd with the standard "earth" symbol but I can see that the bar could be removed.

How do you feel about: 

![image](https://user-images.githubusercontent.com/674783/148462824-3a894a14-31b1-4245-8c95-604db02cb81e.png)

I had a hunt for an international standard for say, "HMI symbols" but couldn't find anything.
 
Possibly there would be something in IEC 60417:2002 DB or ISO 7000 but I don't find anything new here: https://www.iso.org/obp/ui/#iso:pub:PUB400001:en

> already I also would encourage you to add some more logic into distinguishing earth switches, that is proposed in this issue #267.

:+1: I'll take a look.

2022-01-10 07:02 UTC, JakobVogelsang commented
Yeah, sorry that was my bet. Had a look as well, and your proposal is the one most of the world is using. One small thing from my side though. Let's put the grounding symbol at the bottom. This would look better in the Substation editor.

2022-01-12 18:27 UTC, danyill commented
> Let's put the grounding symbol at the bottom. This would look better in the Substation editor.

Sure, will do

2022-01-15 01:14 UTC, danyill commented on src/zeroline/foundation.ts
> +import { typeStr } from '../wizards/conductingequipment.js';
I decided to pick one to pull from the other for this function rather than the current implementation where the function is duplicated but this may be for good reason. Should it go in `src/foundation.ts` instead and be imported from both places?

2022-01-15 01:14 UTC, danyill commented on test/testfiles/conductingequipmentwizard.scd
> +					<SubEquipment name="A" phase="A" virtual="false">
When this scd file is opened in open-scd it fails validation, but I think this `SubEquipment` definition is correct :confused:

2022-01-15 01:14 UTC, danyill commented on test/testfiles/conductingequipmentwizard.scd
> +						<DOI name="SwTyp" desc="Switching-device type">
This has been hand-crafted by me and is not the output of a tool. Please consider if it is a correct or sane thing to write in SCL.

2022-01-15 01:14 UTC, danyill commented on test/testfiles/conductingequipmentwizard.scd
> +								<Val>Earthing Switch</Val>
This has been hand-crafted by me and is not the output of a tool. Please consider if it is a correct or sane thing to write in SCL.

2022-01-15 01:14 UTC, danyill commented on test/testfiles/conductingequipmentwizard.scd
> +				<Val>Earthing Switch</Val>
This has been hand-crafted by me and is not the output of a tool. Please consider if it is a correct or sane thing to write in SCL.

2022-01-15 01:14 UTC, danyill commented on test/testfiles/conductingequipmentwizard.scd
> +	<IED desc="ERS Bay Controller" name="BC1" type="ERS_Bay_Controller" manufacturer="FreedomInc" configVersion="V00.01.00" originalSclVersion="2007" originalSclRevision="B" owner="IEC station 1" origin
I've bodged the output from Siemens DIGSI 5 with a few of my own ideas. Hopefully it makes sense.

2022-01-15 01:14 UTC, danyill commented on src/wizards/conductingequipment.ts
> +  if (daInstantiated) {
I object to my nested `if` statements here but I can't currently see a more elegant approach. Happy to receive instruction.

2022-01-15 01:14 UTC, danyill commented on src/wizards/conductingequipment.ts
> +    const rootNode = <Element>lNode?.getRootNode();
is `getRootNode` safe?
Is it better that I do: `lNode?.ownerDocument;`?

2022-01-15 01:14 UTC, danyill commented on src/wizards/conductingequipment.ts
> +    return swTypVal ? ['Earthing Switch', 'High Speed Earthing Switch'].includes(swTypVal) : false;
Is it acceptable for these values be hard-coded?

2022-01-15 01:15 UTC, danyill commented
I'd be very pleased to take a review of this, please be kind, my TypeScript ability is modest :blush:

2022-01-17 07:33 UTC, JakobVogelsang commented
@danyill I am on the review, please be patient with me. It will take this week, still. Sorry the delay :)

2022-01-21 17:16 UTC, JakobVogelsang reviewed
I have added some some comments but nothing for the functionality, I would like to test it with some files I have. In generall however Looks Good To Me (LGTM)

2022-01-21 17:16 UTC, JakobVogelsang commented on src/wizards/conductingequipment.ts
> +function getDataAttributeValue(lNode: Element, doName: string, sdName: string | undefined, daName: string): string | undefined {
The function works and does that it has to do. I would argue that you have created a very flexible function allowing you to get Val for any give do or sdo, da. This is not really neccassary here. We know from IEC 61850-7-4 that `SwTyp` is a direct child of `XSWI`. This will reduce the complexity in the function a lot. 
If you want to write something more general I thing using recursive functions are better sutted here. 

In this case I would prefer to have a dedicated function for what we want to achive. I don't know something like 

`getSwitchTypeValue(ln:Element): string | null { ... }`

2022-01-21 17:16 UTC, JakobVogelsang commented on test/unit/editors/substation/conductingequipmentwizard.test.ts
> +import { expect } from '@open-wc/testing';
I very much like your test. I this is how I know: A started to review and after 1 min I was done :) Nice job on this one!

2022-01-21 17:16 UTC, JakobVogelsang commented on test/testfiles/conductingequipmentwizard.scd
> +	<IED desc="ERS Bay Controller" name="BC1" type="ERS_Bay_Controller" manufacturer="FreedomInc" configVersion="V00.01.00" originalSclVersion="2007" originalSclRevision="B" owner="IEC station 1" origin
`FreedomInc` love that :)

2022-01-21 17:16 UTC, JakobVogelsang commented on src/wizards/conductingequipment.ts
> +import { getDirections } from '../editors/singlelinediagram/sld-drawing.js';
What is this import for?

2022-01-22 09:00 UTC, danyill commented
Thank you for this review and your constructive comments. I shall improve over the next few days.

2022-01-23 05:20 UTC, danyill commented on src/wizards/conductingequipment.ts
> +      .map(t => t.getAttribute('cNodeName'))
Nice. Thanks.

2022-01-23 05:53 UTC, danyill commented on src/wizards/conductingequipment.ts
> +function getLNodefromIED(lNode: Element | null): Element | null {
You are so right, I missed this and it was clearly part of 6.3. This is a good distinction to make here.

> NOTE Figure 6 shows with its LNode class the LN object, whose instances can be referenced or represented in
> SCL in two ways. The LNode element resides in the Substation structure, while the LN element resides in the IED
> structure.

2022-01-23 05:57 UTC, danyill commented on src/wizards/conductingequipment.ts
> +function getDataAttributeValue(lNode: Element, doName: string, sdName: string | undefined, daName: string): string | undefined {
It shall be as you wish. I'll avoid writing a perfectly general function as it may stretch my understanding too far and cause other problems.

2022-01-23 05:57 UTC, danyill commented on src/wizards/conductingequipment.ts
> +import { getDirections } from '../editors/singlelinediagram/sld-drawing.js';
Whoops, taken from some other playing around. Good spotting :clap:

2022-01-23 09:24 UTC, danyill commented on src/wizards/conductingequipment.ts
> +  return (<Element>lNode?.getRootNode()).querySelector(`IED[name='${iedName}'] > AccessPoint > Server > LDevice[inst='${ldInst}'] > LN[inst='${lnInst}'][lnType='${lnType}'][lnClass='${lnClass}']`);
> 1.) I would argue it is not complete as the prefix is missing. I don't know if we ca relay the lnInst makes the logical node complete.

Good point. Thanks. :+1: 

Looking at Table 8 of IEC 61850-6, I notice this is discussed:

> The LN prefix used in the IED (if needed; default, if not specified, is the empty string). Can
> be used for more detailed function specification than possible by LN class alone, if the LN
> is not allocated to an IED

But yes, if specified it must be handled. I shall add support for this.

I notice there is also this possibility discussed a little below which this PR really should address:

> For specifications where iedName=”None” everywhere, the combination of the other attributes
> must be unique within the same level. This means e.g. that the prefix or lnInst should be
> different if several LNs with identical lnClass are used within the same substation part (i.e.
> same bay). This should also be the case for IED names, if application related naming (see
> 8.5.4) shall be used. This is NOT checked by the SCL schema, therefore it is the
> responsibility of the project engineer or system tool, if application related naming shall be
> used additionally to product (IED)-related naming.

I will use the rather delightful `crossProduct` to do this also.

> 2.) Taken prefix into account we ususally handele missing prefix null and missing prefix empty string as the same. You can use or in selcetors with , and then [:not(prefix)] [prefix=""]. Chris has writen a nice function crossProduct that creates a nice selector.

It took me some :hourglass: to understand, but it is nice :grinning: 

> 3.) using lNode.ownerDocument saves you the type cast

:+1: 

> 4.) Use a formatter to hadle code formatting for you. I use VSCode and prettier. This is not only bit more readable for reiviews but helps you when working in code. :)

Will do. I also use VSCode and can use prettier.

2022-01-23 15:35 UTC, JakobVogelsang commented on src/zeroline/foundation.ts
> +import { typeStr } from '../wizards/conductingequipment.js';
This is ok for me. I think the function is very specific to `ConductingEqipment` to not be part of faoundation. :)

2022-01-23 15:48 UTC, JakobVogelsang commented on src/icons.ts
> -  xmlns="http://www.w3.org/2000/svg"
There are some question that I see and I'll try to answer those one after the other. If I missed one please give me a hint:
1.) I like your proposal to group CSS rules either within the `icon` or outside. The second one we need to define a class that shall be applied to all `ConductingEquipment` type icon.
2.) We can try to play around with the CSS. I can imagine that it would be very benefitial when icons become small as in the SLD to not have round edges.
For both the questions I would propose to have it in a extra issue and PR. For me it woud be great to have the same rules and code style applied to all icons. I would propese to combine it with adding more icons to the code base. This would be very beneficial for the end user I fully aggree!! I opened an [Issue](#509) for that, hope this is ok for you.

One this within the PR I would like to ask you to change. The ""switch" is the other way around for the CBR and DIS. This jupms into my eye. I don't know which one is correct, but would love to be them in the same direction. 
![grafik](https://user-images.githubusercontent.com/66802940/150686615-71c80854-0cc8-4865-9c96-73e385110d47.png)

2022-01-23 16:40 UTC, JakobVogelsang requested changes
This time I have tested your PR with some files I have found and found some bugs. I don't know if they were introduced triggered by my review :( I fthis is the case sorry for that. Your time is limited and I force you to spend so much time...the more I thank you for comtributing on your free time!!! For me that is a sign that my contribution on a Sunday is worth it.

2022-01-23 16:40 UTC, JakobVogelsang commented on src/wizards/conductingequipment.ts
> +  const lDevicePrefixSelector = [`[prefix="${prefix}"]`, ':not(prefix)'];
Here are two things:
1.) the name is missleading as prefix is an attribute of the logical node
2.) I think the way crossProduct is sopposed to be used is to look for a prefix, if prefix is there and not a empty string than look for the definition. In all other cases allow it to be missing or an empty string.

```
const ... = prefix && prefix !=='' ? [`prefix="${prefix}"`, ['prefix=""',':not(prefix)']]
```

2022-01-23 16:40 UTC, JakobVogelsang commented on test/testfiles/conductingequipmentwizard.scd
> +					<SubEquipment name="A" phase="A" virtual="false">
The order of the elements is defined through the schema as well. For the `complexType` `tConductingEquipment` you have everyting defined within the abstract type `tAbstractConductingEquipment` and the `EqFunction`.

```
<xs:sequence>
                      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0"
                          name="EqFunction" type="scl:tEqFunction">
                          <xs:unique name="uniqueLNodeInFuncForCE">
                              <xs:selector xpath="./scl:LNode"/>
                              <xs:field xpath="@lnInst"/>
                              <xs:field xpath="@lnClass"/>
                              <xs:field xpath="@iedName"/>
                              <xs:field xpath="@ldInst"/>
                              <xs:field xpath="@prefix"/>
                          </xs:unique>
                          <xs:unique name="uniqueChildNameInFuncForCE">
                              <xs:selector xpath="./*"/>
                              <xs:field xpath="@name"/>
                          </xs:unique>
                      </xs:element>
                  </xs:sequence>
```
Lokking deeper into `TAbstractConductingEquipment` we see that we have everything within `tEqipment` and then `Terminal` followed by `SubEquipment`. And this is the reason why the schema validator does alarm you. We have a extra function `getReference` in the foundation to make sure the sequence is correct when adding elements to the SCD. 

```
<xs:complexType abstract="true" name="tAbstractConductingEquipment">
          <xs:complexContent>
              <xs:extension base="tEquipment">
                  <xs:sequence>
                      <xs:element form="qualified" maxOccurs="2" minOccurs="0" name="Terminal"
                          type="tTerminal"/>
                      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0"
                          name="SubEquipment" type="tSubEquipment">
                          <xs:unique name="uniqueLNodeInSubEquipment">
                              <xs:selector xpath="./scl:LNode"/>
                              <xs:field xpath="@lnInst"/>
                              <xs:field xpath="@lnClass"/>
                              <xs:field xpath="@iedName"/>
                              <xs:field xpath="@ldInst"/>
                              <xs:field xpath="@prefix"/>
                          </xs:unique>
                          <xs:unique name="uniqueChildNameInACESubEquipment">
                              <xs:selector xpath="./*"/>
                              <xs:field xpath="@name"/>
                          </xs:unique>
                      </xs:element>
                  </xs:sequence>
              </xs:extension>
          </xs:complexContent>
      </xs:complexType>
```

2022-01-23 16:40 UTC, JakobVogelsang commented on test/unit/editors/substation/conductingequipmentwizard.test.ts
> +    it('has no grounded connectivityNodes but has an XSWI LN and DOI:SWTyp > DOType > DA:stVal defining an "Earthing Switch"', () => {
The description of this test is missleading `DIO:SwType > DOType` especially. I really dont' know what this means. DOType is never a child element of DOI.

2022-01-23 16:40 UTC, JakobVogelsang commented on test/unit/editors/substation/conductingequipmentwizard.test.ts
> +    it('has no grounded connectivityNodes but has an IED with name "None" and an XSWI LN with a prefix and DOI:SWTyp > DAI:stVal defining an "Earthing Switch"', () => {
Tthis test should ne work. The attribute `iedName` can only be `None` if the IED does not exist and then DOI and DAI cannot exist either. What can happen in this case is that `LNode` has a `lnType` defined that is referencing a `LNodeType` element that can have a `SwType` and so on...

2022-01-23 16:40 UTC, JakobVogelsang commented on test/unit/editors/substation/conductingequipmentwizard.test.ts
> +describe('conductingequipmentwizard', () => {
From what I can see you test in all following tests that the Terminal is `grounded` of that the `SwType` is defined within the `IED` section but not within the `DataTypeTemplates` section. Otherwise you would have seen a faulty test.

2022-01-23 22:24 UTC, danyill commented on src/wizards/conductingequipment.ts
> +  const lDevicePrefixSelector = [`[prefix="${prefix}"]`, ':not(prefix)'];
Thanks, I understand better now.

2022-01-23 22:52 UTC, danyill commented on test/unit/editors/substation/conductingequipmentwizard.test.ts
> +    it('has no grounded connectivityNodes but has an XSWI LN and DOI:SWTyp > DOType > DA:stVal defining an "Earthing Switch"', () => {
It should have been:

```diff
- 'has no grounded connectivityNodes but has an XSWI LN and DOI:SWTyp > DOType > DA:stVal defining an "Earthing Switch"'
+ 'has no grounded connectivityNodes but has an XSWI LN and LNodeType > DOType > DA:stVal defining an "Earthing Switch"'
```
I've made this more obvious in the test because I think I had left too much information in the scd file for the test to function correctly.

2022-01-23 23:45 UTC, danyill commented on test/unit/editors/substation/conductingequipmentwizard.test.ts
> +    it('has no grounded connectivityNodes but has an IED with name "None" and an XSWI LN with a prefix and DOI:SWTyp > DAI:stVal defining an "Earthing Switch"', () => {
Ah. Good, then we must also support this.

2022-01-23 23:47 UTC, danyill commented on test/unit/editors/substation/conductingequipmentwizard.test.ts
> +describe('conductingequipmentwizard', () => {
I have corrected this.

2022-01-23 23:54 UTC, danyill commented on src/icons.ts
> -  xmlns="http://www.w3.org/2000/svg"
As per separate issue.

2022-01-24 00:15 UTC, danyill commented on src/icons.ts
> -  xmlns="http://www.w3.org/2000/svg"
I think it is probably correct to have the switch arm connected to earth (most ESes that I ever saw "reach out" from the earthed side) and I think whether it is on left or right is "house rules" so that seems good to me.

2022-01-24 02:36 UTC, danyill commented
Thank you for this thorough review. If you have patience I have time :wink: plus it's a holiday today.

I have added support for an `LNode` definition only via a `LNodeType` with a test and made other corrections and improvements as requested, found a few other errors and I hope we're getting close.

2022-01-24 09:36 UTC, JakobVogelsang approved these changes
LGTM! This works perfectly and I like the icon change!

2022-01-24 09:38 UTC, merged