refactor(ied/da-container,do-container): code improvements
openscd/open-scd pull request #464
Opened 2022-01-08 22:47 UTC by JakobVogelsang

@Flurb  as you did not like the toggle function I tried to refactor. What do you think.

I do get snapshot updates that I cannot interpret. Maybe you can have a look.

2022-01-09 12:38 UTC, Flurb commented
Way better! Using standard components instead of your own implementation is always better.
I couldn't find one, but I think I might have searched wrong, mwc-icon-button-toggle is perfect here.

2022-01-09 12:46 UTC, Flurb requested changes
Looks good, but during testing is see that the icon isn't changing when toggling.

2022-01-09 12:47 UTC, Flurb requested changes
Also, the same toggle principle can be added to the ln-container :)

2022-01-09 13:12 UTC, JakobVogelsang commented
> Also, the same toggle principle can be added to the ln-container :)

This was on purpose from my side (see #461). My opinion is that we need some other mechanism here. Do you agree? Do I miss something?

2022-01-09 13:13 UTC, JakobVogelsang commented
> Way better! Using standard components instead of your own implementation is always better. I couldn't find one, but I think I might have searched wrong, mwc-icon-button-toggle is perfect here.

This is bug of this component that only is present in debug mode. Just for you to compare, see the buttons in the log.

2022-01-09 22:18 UTC, Flurb commented
> > Way better! Using standard components instead of your own implementation is always better. I couldn't find one, but I think I might have searched wrong, mwc-icon-button-toggle is perfect here.
> 
> This is bug of this component that only is present in debug mode. Just for you to compare, see the buttons in the log.

Then it's fine, hope it will be fixed soon!

2022-01-09 22:18 UTC, Flurb commented
> > Also, the same toggle principle can be added to the ln-container :)
> 
> This was on purpose from my side (see #461). My opinion is that we need some other mechanism here. Do you agree? Do I miss something?

Why would this functionality be different for a LN container compared to DO/DA containers?

2022-01-10 06:59 UTC, JakobVogelsang commented
> > > Also, the same toggle principle can be added to the ln-container :)
> > 
> > 
> > This was on purpose from my side (see #461). My opinion is that we need some other mechanism here. Do you agree? Do I miss something?
> 
> Why would this functionality be different for a LN container compared to DO/DA containers?

Because rendering the data model for a complicated IED does take some seconds which in my opinion is not a good user experience. The `hidden` attribute is a performance problem, but as is, we still walk through every DO and DA there is in a data model of an IED. We don't need to do that. I think we should on first render only consider the data model up until the logical nodes and only on toggle button trigger should dive into the DOs and DAs. :)

2022-01-10 08:24 UTC, Flurb approved these changes

2022-01-10 08:48 UTC, Flurb requested changes
I'm going to implement a solution for all three the containers, should not be a problem :)

2022-01-10 13:46 UTC, Flurb commented
@JakobVogelsang (or anyone else) please review :)

2022-01-10 20:34 UTC, JakobVogelsang commented on web-test-runner.config.mjs
> +  browserLogs: true,
Just out of curiosity. Why this? Do we need it for something? Due to our plugin architecture, the browser log shows a misleading error when calling `Hosting`. This makes the log hard to read. But if you think we require it for something, I am fine with it.

2022-01-10 20:39 UTC, Flurb commented on web-test-runner.config.mjs
> +  browserLogs: true,
No we don't, I just like to use console.logs during testing. For this we need to set it to true, and it should be reverted which I didn't do :)

2022-01-10 20:46 UTC, JakobVogelsang commented
LGTM @Flurb

2022-01-10 20:46 UTC, Flurb approved these changes

2022-01-10 20:46 UTC, merged