refactor(editor/communication): move wizards to wizard library
openscd/open-scd pull request #489
Opened 2022-01-17 10:50 UTC by JakobVogelsang

- Mainly moved wizards to wizards-library. While doing this also improved code with wizards and added more extensive tests.
- In cooperated `action-pane` with have a similar look and feel like the Substation and IED editor type plug-ins.

2022-02-02 12:28 UTC, ca-d requested changes
I'm still not done with the review, as I noted I have trouble with one of the commits.

As we talked about earlier, this review made clear to me once again how much easier reviewing a branch is when the branch in question does just one thing. If this branch contained *only* the refactor (as it says in the title) and no drive-by fixes and style improvements, the review would have been done in a few minutes. The same would then probably be true for the *separate* `fix:` and `style:` branches containing the fixes.

In general, I don't enjoy this mode of reviewing branches by individual commits. What I want to review is the result of your work, not the process you took to get there.

2022-02-02 12:28 UTC, ca-d commented on src/editors/communication/subnetwork-editor.ts
>    private renderHeader(): TemplateResult {
Why do we still use a `renderHeader` method returning a `TemplateResult` here? Isn't all we need a string? Does the `mdash` thing still work within the attribute?

2022-02-02 12:28 UTC, ca-d commented on src/editors/Communication.ts
> +    }
empty line disappeared here

2022-02-02 12:28 UTC, ca-d commented on src/editors/communication/subnetwork-editor.ts
> +  private renderSubNetworkSpecs(): TemplateResult {
I don't understand this pattern of using `TemplateResult`s and passing them to our components as a `.label` property, where they will be wrapped in a string. I'm really stunned that any of this works, especially the `&mdash;` - does it work in practice or does it render a regular dash?

2022-02-02 12:28 UTC, ca-d commented on src/editors/communication/subnetwork-editor.ts
> +      this.element.querySelectorAll(':scope > ConnectedAP') ?? []
Great idea using `:scope` here! 👍

2022-02-02 12:28 UTC, ca-d commented on src/wizards/subnetwork.ts
> +function getBitRateAction(
I can't currently really review the `update edit wizard` commit, since it moves code it possibly changes, so the diff is not very useful to me. I hope you can help me understand this change later.

2022-02-02 12:28 UTC, ca-d commented on src/editors/communication/subnetwork-editor.ts
> +    const Br = this.element.querySelector('BitRate');
When reading a constant called `Br` and another called `br` I can't tell the difference in meaning from the difference in name.

Also, the idiomatic way to write `BitRate` as a constant name would be `bitRate` and its abbreviation would then be `bR`, since constants that don't refer to constructors always start with a lower-case letter.

2022-02-02 15:06 UTC, ca-d commented on src/wizards/subnetwork.ts
> +function getBitRateAction(
Thanks for clarifying that this change consisted only in introducing `ContentOptions`.

2022-02-02 22:06 UTC, JakobVogelsang commented
> 

This is a good hint, and I get what you mean. I in the future will create one branch per single issue/step to allow you to review faster.

2022-02-02 22:07 UTC, JakobVogelsang commented on src/editors/communication/subnetwork-editor.ts
> +      this.element.querySelectorAll(':scope > ConnectedAP') ?? []
That was @Flurb idea in some of his PRs :)

2022-02-02 22:50 UTC, JakobVogelsang commented on src/editors/communication/subnetwork-editor.ts
> +    return this.element.getAttribute('name') ?? 'UNDEFINED';
I would argue not. The `name` is a required attribute, and normally it should not happen.

2022-02-08 17:24 UTC, ca-d approved these changes
LGTM

2022-02-08 17:35 UTC, merged