feat(wizards/reportcontrol): added new IED wizard to update name/description
openscd/open-scd pull request #494
Opened 2022-01-18 13:06 UTC by dlabordus

Also all SCL elements referencing that IED Name are updated.

2022-01-18 16:11 UTC, JakobVogelsang commented on src/wizards/ied.ts
> +      validationMessage="${translate('textfield.required')}"
I would suggest adding a pattern here. I think it is defined in the issue. For the average user, it might not be so clear what the limitation to this attribute might be.

2022-01-18 16:29 UTC, JakobVogelsang commented on src/wizards/ied.ts
> +    .map(cNode => cNode.getAttribute('name') ?? '')
Why `cNode`? This jumped into my eye. So far, I can see something like `ied` would fit better.

2022-01-18 16:37 UTC, JakobVogelsang commented on src/wizards/foundation/references.ts
> +        .filter(element => isPublic(element))
`element => isPublic(element)` can be shortened down to `isPublic`. This is very picky and not necessary to change. Your solution is working as well.

2022-01-18 16:39 UTC, JakobVogelsang commented on src/wizards/foundation/references.ts
> +        .filter(element => isPublic(element))
The same hint here too.

2022-01-18 17:00 UTC, JakobVogelsang requested changes
In general, look good. Two things I would says might be better:
1. complexAction instead of simpleActions
2. Add pattern to the wizard-textfield. At the moment for example you can type in things like `None` which is not schema valid

2022-01-19 06:21 UTC, dlabordus commented on src/wizards/foundation/references.ts
> +function cloneElement(element: Element, attributeName: string, value: string | null): Element {
The record solution in foundation is not working, because the name can't be passed as variable. The name of the variable 'attributeName' is then used as the name of the attribute in the XML. 
The way cloneElement is used in the other solutions the name of the variable is the name of the attribute.

2022-01-19 06:38 UTC, dlabordus commented on src/wizards/ied.ts
> +    .map(cNode => cNode.getAttribute('name') ?? '')
Solved, copy / paste issue probably :-)

2022-01-19 06:47 UTC, dlabordus commented on src/wizards/ied.ts
> +    return actions;
I couldn't find ComplexAction in ImportIEDs, but found a example in connectedap.ts in wizards.
Is this also a good example?

2022-01-19 06:58 UTC, dlabordus commented on src/wizards/ied.ts
> +    return actions;
Fixed it using example from connectedap.ts :-)

2022-01-19 07:14 UTC, dlabordus commented on src/wizards/ied.ts
> +      validationMessage="${translate('textfield.required')}"
Done. Also added pattern to descr field.

2022-01-19 08:49 UTC, JakobVogelsang approved these changes
LGTM

2022-01-19 08:58 UTC, merged