feat(wizards/settings): Load nsdoc to local storage
openscd/open-scd pull request #502
Opened 2022-01-19 23:54 UTC by Flurb

2022-01-20 14:51 UTC, JakobVogelsang commented
@Flurb I had a first look on your PR and code. I need another round to go through your code, but have two things that I would remark:
1. I would love to have `multi` file import. I think some will want to load all files at once, not one after another.
2. I can imagine that list-item's being `noninteractive` - and maybe even `disabled` - so long there is no file loaded would make it clearer for the user.

2022-01-20 23:04 UTC, Flurb commented
> @Flurb I had a first look on your PR and code. I need another round to go through your code, but have two things that I would remark:
> 
> 1. I would love to have `multi` file import. I think some will want to load all files at once, not one after another.
> 2. I can imagine that list-item's being `noninteractive` - and maybe even `disabled` - so long there is no file loaded would make it clearer for the user.

Implemented both!

2022-01-24 10:18 UTC, JakobVogelsang commented on src/Setting.ts
> +import './Divider.js';
We usuaelly add our imported web-components above our class, function imports

2022-01-24 10:20 UTC, JakobVogelsang commented on src/Divider.ts
> +import {css, customElement, html, LitElement, TemplateResult} from "lit-element";
The files name does not fit to the way other `web-components` are defined. We usuaelly do use the same name as the custem tag. Here it would be `openscd-devicer`. Also but I cannot say that looking at the code purelly if this is desinged to be used within dialogs/wizards. Then we should call it i `wizard-devider`

2022-01-24 10:27 UTC, JakobVogelsang commented on src/Setting.ts
> +        ${nsdSetting ? html`<span slot="secondary">${nsdVersion}${nsdRevision}</span>` :
Is release missing? For the experienced user there is a bit difference between `2007B` and `2007B4`.

2022-01-24 10:28 UTC, JakobVogelsang commented on src/translations/de.ts
> +    selectFileButton: '???',
`Datei auswählen` would be german term here

2022-01-24 10:34 UTC, Flurb commented on src/Setting.ts
> +import './Divider.js';
Where should it be placed then?
I thought it should be added on the bottom of all imports :)

2022-01-24 10:35 UTC, Flurb commented on src/Divider.ts
> +import {css, customElement, html, LitElement, TemplateResult} from "lit-element";
WizardDivider would be more appropriate here :)

2022-01-24 10:47 UTC, Flurb commented on src/Setting.ts
> +        ${nsdSetting ? html`<span slot="secondary">${nsdVersion}${nsdRevision}</span>` :
Added!

2022-01-24 11:15 UTC, Flurb commented on src/translations/de.ts
> +    selectFileButton: '???',
Done!

2022-01-27 13:06 UTC, dlabordus commented on src/editors/IED.ts
> +  nsdoc!: Nsdoc;
Where is this used? Shouldn't it be passed to the ied-container?

2022-01-27 13:08 UTC, dlabordus commented on src/foundation.ts
> +import { iec6185074 } from './validators/templates/foundation.js';
Is this import used? No other code has changed.

2022-01-27 13:22 UTC, Flurb commented on src/editors/IED.ts
> +  /** Query holding the current selected IEDs. */
Probably during merge, good call!

2022-01-27 13:28 UTC, Flurb commented on test/unit/Setting.test.ts
> +    expect(element).shadowDom.to.equalSnapshot();
No doing it like below was intended.
Checking if the file in localStorage is what we expected.

Added it!

2022-01-27 14:01 UTC, Flurb commented on src/Setting.ts
> +        if (!id) return;
Added!

2022-01-31 06:39 UTC, dlabordus requested changes

2022-01-31 06:39 UTC, dlabordus commented on src/foundation/nsdoc.ts
> +  const referenceInfoTags = ['LN', 'LN0'] as const;
referenceInfoTags is maybe not the best name :-)
I think a copy from original.

2022-01-31 08:34 UTC, Flurb commented on src/foundation/nsdoc.ts
> +  const referenceInfoTags = ['LN', 'LN0'] as const;
What about just calling it `iedElementTagNames`?

2022-02-02 22:01 UTC, JakobVogelsang approved these changes
LGTM. Some changes to the NSDoc object that I think are necessary can be done in the pending PR #522

2022-02-03 11:10 UTC, dlabordus approved these changes

2022-02-03 11:32 UTC, merged