Add edit wizard for sampledvaluescontrol
openscd/open-scd pull request #510
Opened 2022-01-23 20:53 UTC by JakobVogelsang

Close #428

2022-01-25 12:19 UTC, dlabordus requested changes

2022-01-25 12:19 UTC, dlabordus commented on src/wizards/sampledvaluecontrol.ts
> +      helper="${translate('scl.desc')}"
Some description field have a pattern and some not. Should there always be a pattern, because all description are the same type?

2022-01-25 12:19 UTC, dlabordus commented on src/zeroline-pane.ts
> +      newSubWizardEvent(() =>
Is this not a normal Wizard? zeroline-pane.ts is used by the Substation Editor, correct?

2022-01-25 12:19 UTC, dlabordus commented on src/zeroline/ied-editor.ts
> +      newSubWizardEvent(() => selectSampledValueControlWizard(this.element))
Same here, is this not a normal Wizard?

2022-01-25 14:05 UTC, JakobVogelsang commented on src/zeroline-pane.ts
> +      newSubWizardEvent(() =>
True! It is cleaner. Thanks!! In this particular case it does not make a difference, but I will adapt.

2022-01-25 14:05 UTC, JakobVogelsang commented on src/zeroline/ied-editor.ts
> +      newSubWizardEvent(() => selectSampledValueControlWizard(this.element))
True!

2022-01-25 15:09 UTC, JakobVogelsang commented on src/wizards/sampledvaluecontrol.ts
> +      helper="${translate('scl.desc')}"
It is true. For readablility reasos there should. For this particular attribute pattern is `xs:nomalizedString` and therefore I thinks it does not mattern if we forget to set it. Still thanks for the hint. The wizards library need some clean up anyway and this is one such point.

2022-01-26 06:37 UTC, dlabordus approved these changes

2022-01-26 12:30 UTC, merged