Added Nsdoc plugin + Show LN names
openscd/open-scd pull request #516
Opened 2022-01-25 09:05 UTC by Flurb

2022-01-25 12:31 UTC, dlabordus requested changes

2022-01-25 12:31 UTC, dlabordus commented on src/editors/ied/ldevice-container.ts
> +            .lnClassElement=${nsdoc.get74NsdLNClass(ln.getAttribute('lnClass')!)}
Why do this lookup here? We are passing the LN Element to the LNContainer.

2022-01-25 12:31 UTC, dlabordus commented on src/Setting.ts
> +      return parsedNsdoc74.querySelector(`NSDoc > Doc[id="${id}"]`);
Why not combine these two functions? Pass a LNClass Name, use that to search in NSD and next in NSDoc.

And maybe in state of adding 74 to the function name, pass some kind of constant which can be used to get the correct NSD/NSDOC variables.

2022-01-26 13:08 UTC, JakobVogelsang commented
I will merge this as there are some changes that revert changes in the merging branch. Hope this does not block you from reviewing @dlabordus

2022-01-26 13:09 UTC, JakobVogelsang approved these changes
Will be riewed in load-nsdoc-settings directly

2022-01-26 13:09 UTC, merged