feat(wizard/sampledvaluecontrol): allow removing incl. referenced elements
openscd/open-scd pull request #536
Opened 2022-02-08 11:14 UTC by JakobVogelsang

Closes #431

2022-02-09 06:54 UTC, dlabordus requested changes

2022-02-09 06:54 UTC, dlabordus commented on src/wizards/sampledvaluecontrol.ts
> +            deleteActions.forEach(deleteAction =>
Shouldn't this be a Complex Action to make the Redo work as 1 unit?

2022-02-09 07:46 UTC, JakobVogelsang commented on src/wizards/sampledvaluecontrol.ts
> +            deleteActions.forEach(deleteAction =>
Yeah I was thinking that too yesterday. I deceded to not do it, because we don't have a diff view right now in the log and complex actions a bit hide what has changed in detail. 

In any case I would love to do it for all control blocks or non of them. Report and GOOSE control block removal at the moment works with up to 3 SimpleActions as well. 

I will open a [Issue](https://github.com/openscd/open-scd/issues/540) for it to not forget this. Is this a way to proceed for you?

2022-02-14 08:19 UTC, dlabordus approved these changes

2022-02-14 08:59 UTC, merged