feat(wizards/smvopts): add edit wizard
openscd/open-scd pull request #547
Opened 2022-02-17 16:16 UTC by JakobVogelsang

Closes #429

2022-02-18 23:30 UTC, Flurb requested changes

2022-02-18 23:30 UTC, Flurb commented on test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts
> +        await new Promise(resolve => setTimeout(resolve, 100)); // await animation
Why isn't `await editSmvOptsButton.updateComplete;` enough here, instead of a sleep (which is not recommended).

Using this should be enough and is a better solution compared to a sleep:
```
await editSmvOptsButton.updateComplete;
editSmvOptsButton.click();
await editSmvOptsButton.requestUpdate();
await editSmvOptsButton.updateComplete;
```

Too bad we need an extra `requestUpdate()`, I think because of the way tests are being set up and a `click()` doesn't automatically triggers a render?

2022-02-21 07:39 UTC, JakobVogelsang commented on test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts
> +        await new Promise(resolve => setTimeout(resolve, 100)); // await animation
The reason is that we need to await an animation frame. With this test on button click one of the wizards closes and the other opens. We have that all over our tests and we have to found a solution to that until now.

I think the solution you have proposed would not work in all cases. It would cause timing issues depending on the power of the mchanine the tests are run on. The line `editSmvOptsButton.requestsUpdate()` eats up some time as this button disapears shotsly after clicking on this button (edit SampledValueControl wizards closes to make room or the edit SMV wizard).

2022-02-24 08:45 UTC, danyill requested changes
A few minor translation comments.
Some of the comments on ReportControlBlocks are applicable here.

2022-02-24 08:45 UTC, danyill commented on src/translations/en.ts
>      nofASDU: 'Samples per paket',
```suggestion
    nofASDU: 'Samples per packet',
```

2022-02-24 08:45 UTC, danyill commented on src/translations/en.ts
> +    synchSourceId: 'Add identity of sync source to SMV telegram',
```suggestion
    SmvOpts: 'Optional Information',
    refreshTime: 'Add timestamp to SMV packet',
    sampleRate: 'Add sample rate to SMV packet',
    dataSet: 'Add DataSet name to SMV packet',
    security: 'Potential future use. e.g. digital signature',
    synchSourceId: 'Add sync source id to SMV packet',
```

2022-02-24 10:42 UTC, JakobVogelsang commented on src/translations/en.ts
> +    synchSourceId: 'Add identity of sync source to SMV telegram',
Thanks for those hints. Sorry I am not really good at these things :) But together we will make it work :)

2022-02-24 12:58 UTC, merged