feat(plugins/Subscription): Create 'Subscription' plugin for GOOSE subscriptions
openscd/open-scd pull request #549
Opened 2022-02-21 21:35 UTC by Flurb

2022-02-22 20:37 UTC, danyill commented
This is exciting! :tada: 

 I'm not familiar with ABB IEDs. I thought I'd have a play anyway.

When there are many devices or transmit messages in the left pane, then it would be convenient if the right pane was "sticky" such that when the left-hand side is scrolled, and a new IED is selected then the right-hand side remains in view (the user doesn't have to scroll to the top on the RHS).

Otherwise, if I understand correctly, the user must constantly scroll up and down if working with IEDs at the bottom of the stack.

Here's an example file: [ArcFlash_IEC61850_GOOSE_2-section.scd.zip](https://github.com/openscd/open-scd/files/8120007/ArcFlash_IEC61850_GOOSE_2-section.scd.zip)

2022-02-23 09:35 UTC, Flurb commented
> This is exciting! 🎉
> 
> I'm not familiar with ABB IEDs. I thought I'd have a play anyway.
> 
> When there are many devices or transmit messages in the left pane, then it would be convenient if the right pane was "sticky" such that when the left-hand side is scrolled, and a new IED is selected then the right-hand side remains in view (the user doesn't have to scroll to the top on the RHS).
> 
> Otherwise, if I understand correctly, the user must constantly scroll up and down if working with IEDs at the bottom of the stack.
> 
> Here's an example file: [ArcFlash_IEC61850_GOOSE_2-section.scd.zip](https://github.com/openscd/open-scd/files/8120007/ArcFlash_IEC61850_GOOSE_2-section.scd.zip)

Hi @danyill , good suggestion! I can take a quick look at that!

2022-02-23 23:41 UTC, Flurb commented
@danyill I implemented the scrollable lists, I would love to have your feedback!

2022-02-24 03:27 UTC, danyill commented
Scrollabe lists are the :bomb: :+1: 
That makes this feel very usable.

I'm not sure what's in scope for this feature. Should we be showing additional fields? e.g. for all dataset items which are subscribed? For SEL relays it is useful to know the `intAddr` parameter (and I think ABB too).

2022-02-24 04:07 UTC, danyill reviewed
I thought I should read the code and as I did I had a  few minor comments, use as you wish :wink:

2022-02-24 04:07 UTC, danyill commented on src/editors/subscription/subscriber-ied-list.ts
> +        selected: this.gseName ? this.iedName+'>'+this.gseName : 'IED'
Also I think we should put a space in here to facilitate wrapping.

```suggestion
        selected: this.gseName ? this.iedName + ' > ' + this.gseName : 'IED'
```

2022-02-24 04:07 UTC, danyill commented on src/editors/subscription/subscriber-ied-list.ts
> +      text-overflow: ellipsis;
If we're going to treat text-overflow like this can we add a tooltip.
I would prefer not to use an ellipsis because the end information is quite useful to the end user (I don't think its optional):

![image](https://user-images.githubusercontent.com/674783/155456078-c11bf97b-2550-4584-b4c4-70d8b4a94f84.png)

2022-02-24 08:05 UTC, JakobVogelsang commented on src/editors/Subscription.ts
> +export default class SubscriptionABBPlugin extends LitElement {
This is how I know it from PCM600 where you do not connect individually. We had the discussion how to combine different types of subscriber processes. We decided to separate those through plugins. That means that the way you are used to working - with individual FCDA connecting to individual ExtRef I guess. And the other one called `later binding`

2022-02-24 08:25 UTC, JakobVogelsang commented
I have tried it out for the first time and have some UI remarks before diving into the code:
1. The two lists are not so visible. Having them in a slightly different color like we do with the `action-pane`s would be a helper already, I think
2. The header for the source would sound better `Publicher: GOOSE` or `GOOSE publisher`. The right side of the sink I would add a `of` making it `Subscriber IED of GOOSE: ....`
3. I also think the headers should not be clipped. I, this has to be you can clip at the beginning not at the end as the valuable information is at the end
4. Using `filtered-list` could be a nice option to reduce complexity. You have to imagine that there are project that have 250+ IED in the file. There you see that you don't see.
5. Maybe reuse the `gooseIcon` for the list-items that represent a `GSEControl` :)
6. This plugin can be a default from the beginning. When we add other subscriber plugins later, we can decide to change that. But for now!

2022-02-24 09:14 UTC, Flurb commented on src/editors/subscription/publisher-goose-list.ts
> +   * Get all the published GOOSE messages, ABB method.
Can be removed here, no added value indeed.

2022-02-24 09:15 UTC, Flurb commented on src/translations/en.ts
> +      noGooseMessageSelected: 'No GOOSE message selected.'
Fine for me!

2022-02-24 09:17 UTC, Flurb commented on src/editors/Subscription.ts
> +export default class SubscriptionABBPlugin extends LitElement {
Did this answer your question @danyill ?

2022-02-24 09:21 UTC, danyill commented on src/editors/Subscription.ts
> +export default class SubscriptionABBPlugin extends LitElement {
Yes, thanks both.

2022-02-24 09:26 UTC, Flurb commented on src/editors/subscription/subscriber-ied-list.ts
> +        selected: this.gseName ? this.iedName+'>'+this.gseName : 'IED'
Putting a space at the beginning and end of the `>` is nice, but not consistent.
I would also suggest to do that, but then we need to do it in the entire OpenSCD application.

@JakobVogelsang worth an issue?

2022-02-24 10:13 UTC, Flurb commented on src/editors/subscription/subscriber-ied-list.ts
> +          }`)) {
Good suggestion! Makes the code a bit more clean :)

2022-02-24 11:02 UTC, Flurb commented on src/editors/subscription/subscriber-ied-list.ts
> +      text-overflow: ellipsis;
This is also something we use throughout the OpenSCD application.
If we want to change this, it needs to be changed consistently. 

@JakobVogelsang , worth an issue?

2022-02-25 09:13 UTC, Sander3003 commented
As @Flurb mentioned small improvements and bugs can be solved in this pull-request. Bigger improvements require a seperate issues. By doing so we have small improvements (more easy to review).

2022-02-27 15:59 UTC, JakobVogelsang requested changes
The plugin is nice!! Thank you for that. I found a bug and would love to have the german translation added. Everything else are comments.

2022-02-27 15:59 UTC, JakobVogelsang commented on src/translations/de.ts
> +    none: '???',
Keine Verbindung vorhanden

2022-02-27 15:59 UTC, JakobVogelsang commented on src/translations/de.ts
> +      title: '???'
GOOSE-Publizierer

2022-02-27 15:59 UTC, JakobVogelsang commented on src/translations/de.ts
> +      title: '???',
Verbunden mit {{ selected }}

2022-02-27 15:59 UTC, JakobVogelsang commented on src/translations/de.ts
> +      subscribed: '???',
Verbunden

2022-02-27 15:59 UTC, JakobVogelsang commented on src/translations/de.ts
> +      availableToSubscribe: '???',
Kann verbunden werden

2022-02-27 15:59 UTC, JakobVogelsang commented on src/translations/de.ts
> +      partiallySubscribed: '???',
Teilweise verbunden

2022-02-27 15:59 UTC, JakobVogelsang commented on src/translations/de.ts
> +      noGooseMessageSelected: '???'
Keine GOOSE ausgewählt

2022-02-27 15:59 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-ied-list.ts
> +      const inputs = ied.querySelector(`LN0[lnClass="LLN0"] > Inputs`);
I think this is not completely correct. `GSEControl` are limited to `LN0` as parent, but they can be stored in any of the `LN0`. Basically, you can store them in any of the logical devices. The query down below takes the first `LN0` that has a `Input` not misses others that potentially are allocated to another logical device in the same IED.

2022-02-27 15:59 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-ied-list.ts
> +        if(inputs.querySelector(`ExtRef[iedName=${event.detail.iedName}][serviceType="GOOSE"]` +
I would leave out the limitation `[serviceType="GOOSE"]`. This is not present in Ed1 and logically not neccassery here. When the user clicks on one of the GOOSEs, he wants to see all valid connections, not only those taged as GOOSE.

2022-02-27 15:59 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-ied-list.ts
> +    const openScdElement = document.querySelector('open-scd');
Why do you dispatch and listen on open-scd? My gud feeling would say we can dispatch in the object where we click on, and we can listen on the GOOSE tab/Subscriber.

We do use `open-scd` with menu type plugin as well or better we have to as on re-render the connection to `open-scd` gets lost. Is this an issue as well here? If so I would ask you to add a comment `TODO: ...`

2022-02-27 15:59 UTC, JakobVogelsang commented on src/foundation.ts
> +export interface GOOSEDataSetDetail {
1. Do we need to define this event in foundation? So far I think we have events defined that are use globally be the whole application. However, I am not sure if we can move it to `editors/subscriber/foundation`.

2. The name is bothering me. The other event can of tell what they do or have been triggered by. I cannot think of a better name than `GOOSeSelectEvent` - not perfect either :(

2022-02-27 15:59 UTC, JakobVogelsang commented on src/foundation.ts
> +  gseName: string;
I would make it gseControl: Element. The name is part of it, and we can use it for other purposes later in the application.

2022-02-27 15:59 UTC, JakobVogelsang commented on src/foundation.ts
> +    ['goose-dataset']: GOOSEDataSetEvent;
I am not sure if we can declare this somewhere else. So far we need it only within the `Subscriber` plugin and so log it is the case we should try to define it there. However, not sure it this can be done. @ca-d can you help out?

2022-02-28 08:24 UTC, Flurb commented on src/editors/subscription/subscriber-ied-list.ts
> +      const inputs = ied.querySelector(`LN0[lnClass="LLN0"] > Inputs`);
Ah I thought every IED only has 1 LN0 element. This is not correct?

2022-02-28 09:16 UTC, Flurb commented on src/editors/subscription/subscriber-ied-list.ts
> +    const openScdElement = document.querySelector('open-scd');
I don't think we want to listen in the plugin itself, because the SubscriberIEDLIst is the only element it's interested in. How can I add an EventListener here without using the open-scd element?

2022-02-28 10:49 UTC, Flurb commented on src/foundation.ts
> +    ['goose-dataset']: GOOSEDataSetEvent;
I also wanted it somewhere within the `subscription` plugin for example, but it only works if it's placed here :)
A prefer a better solution!

2022-02-28 10:54 UTC, Flurb commented on src/foundation.ts
> +  gseName: string;
Good idea, in the manage goose services I also changed iedName to full IED element :)

2022-02-28 11:27 UTC, Flurb commented on src/foundation.ts
> +export interface GOOSEDataSetDetail {
I see the interfaces always ends with `-Detail`, why should this be different? `GOOSESelectDetail` is fine by me as well.

2022-02-28 17:31 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-ied-list.ts
> +      const inputs = ied.querySelector(`LN0[lnClass="LLN0"] > Inputs`);
You must have one LN0 per LDevice but you can have multiple LDevices per Server and thus multiple LN0 per Server

2022-02-28 17:31 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-ied-list.ts
> +      const inputs = ied.querySelector(`LN0[lnClass="LLN0"] > Inputs`);
True Inputs is a single element within one LN0

2022-02-28 19:30 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-ied-list.ts
> +      const inputs = ied.querySelector(`LN0[lnClass="LLN0"] > Inputs`);
I think to fix it you need something like `ied.querySelectorAll(LN0 > Inputs)` the `[lnClass="LLN0" ]` is not neccassery as is always the case for `LN0`

2022-03-07 08:43 UTC, danyill commented
Thanks for this @Flurb this seems like a very important feature :tada: :trumpet: 

Should I review this or #569?

Off the top of my head from a UI point of view

* I would like to see a little edit option for each GSEControl so that I can look for further information from the same screen. That doesn't seem too difficult since the Edit GSEControl wizard I think already does this.
* Perhaps that's sufficient, but I also wonder if we should the description field in a tooltip or beneath the GSEControl in the UI?
* Should the scroll bars of the GOOSE Publisher and Subscriber be invisible/width zero?
* How do we show partial subscriptions of a GOOSE dataset?

I'm quite interested in having a subscription plugin for SEL relays where the `intAddr` would need to be visible/settable for the dataset item which is subscribed.

2022-03-07 10:53 UTC, Flurb commented
> Thanks for this @Flurb this seems like a very important feature 🎉 🎺
> 
> Should I review this or #569?
> 
> Off the top of my head from a UI point of view
> 
> * I would like to see a little edit option for each GSEControl so that I can look for further information from the same screen. That doesn't seem too difficult since the Edit GSEControl wizard I think already does this.
> * Perhaps that's sufficient, but I also wonder if we should the description field in a tooltip or beneath the GSEControl in the UI?
> * Should the scroll bars of the GOOSE Publisher and Subscriber be invisible/width zero?
> * How do we show partial subscriptions of a GOOSE dataset?
> 
> I'm quite interested in having a subscription plugin for SEL relays where the `intAddr` would need to be visible/settable for the dataset item which is subscribed.

I think @JakobVogelsang already reviewed both, am I right Jakob?
For your other suggestions:

> I would like to see a little edit option for each GSEControl so that I can look for further information from the same screen. That doesn't seem too difficult since the Edit GSEControl wizard I think already does this.

This was already the plan, I'm not sure if we already have an issue for that. Can you check this? :)

> Perhaps that's sufficient, but I also wonder if we should the description field in a tooltip or beneath the GSEControl in the UI?

Good suggestion, create an issue for that :)

> Should the scroll bars of the GOOSE Publisher and Subscriber be invisible/width zero?

You mean while still being scrollable? Why do you want that? Or maybe I'm not getting it :)

> How do we show partial subscriptions of a GOOSE dataset?

This is already implemented, we have 3 lists on the right: Fully subscribed, partially subscribed and not subscribed. IEDs that are inside the not subscribed/partially subscribed can be fully subscribed. IEDs in the Fully subscribed section can be unsubscribed.

I hope this answers all your questions :)

2022-03-07 17:53 UTC, danyill commented
Thanks @Flurb I have created some issues. @JakobVogelsang asked me to review... but I may have missed the moment.

Anyway, from a style/user-facing perspective:

>>    Should the scroll bars of the GOOSE Publisher and Subscriber be invisible/width zero?
>You mean while still being scrollable? Why do you want that? Or maybe I'm not getting it :)

The height of the GOOSE publisher on Chrome is greater than the contained elements.

![image](https://user-images.githubusercontent.com/674783/157084261-0ecaa1a5-dd1c-436d-9149-516ce7409c12.png)

This gives us a scrollbar on the publisher where we don't need it _and_ a scrollbar on the overall window which is too many scrollbars. They are also the default scrollbars which are intrusive. Perhaps not zero width but less width might be nice.

Probably a CSS change is required which would remove the scrollbars for this case.
Perhaps a calc function should be used to subtract the height of the `mwc-top-app-bar-fixed` element...

Even so, there is the case with more IEDs/GSEControls it will extend.

In this case:
* the scrollbar appears to start partway done the publisher pane and abruptly so it doesn't "look right" to my (somewhat unkind) :eye: 
* Scrollbars as shown here are used in OpenSCD so this is consistent with the overall UI. In the wider world there is flamewars around scrollbars (do you need them, are they a good UI element etc.). Material Design [suggests](https://material.io/components/menus#behavior) there should be scrollbars but the modern take is much more minimalist than the scrollbars we have here.
** Browser support for CSS scrollbars is still weak https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars
** But neither do we (at least me) want IE 5.5 scrollbars!
** And the [webkit option](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) is not on a standards track but is the only viable option

To be very concrete, what I was thinking of was something less visually intrusive, i.e.

```css  
    mwc-list::-webkit-scrollbar {
      width: 5px;
      height: 8px;
      background-color: var(--base3);
    }
    
    mwc-list::-webkit-scrollbar-thumb {
        background: var(--primary);
    }
```

This way the scrollbars blend into the selection at the top and for the subscribing pane (I may not have the colours exactly right).

![image](https://user-images.githubusercontent.com/674783/157089155-1444633c-8262-47f9-8b1a-d87a4fc5b064.png)

I accept that I am a pedant and apologise and beg forgiveness :pray: 

A reasonable person will simply respond to this feedback with, "You didn't do that in #568 so why should I?"

2022-03-08 09:48 UTC, JakobVogelsang commented
> 

There will be an extra plugin for that, that will be similar but will allow you to connect single `FCDA` elements to one `ExtRef`. Combining all approaches people got used to with different vendors is too difficult. At least starting with it. When we see synergies later and think we can merge with one or the other together, we will do that.

2022-03-08 10:04 UTC, JakobVogelsang commented
> Thanks @Flurb I have created some issues. @JakobVogelsang asked me to review... but I may have missed the moment.
> 
> Anyway, from a style/user-facing perspective:
> 
> > > Should the scroll bars of the GOOSE Publisher and Subscriber be invisible/width zero?
> > > You mean while still being scrollable? Why do you want that? Or maybe I'm not getting it :)
> 
> The height of the GOOSE publisher on Chrome is greater than the contained elements.
> 
> ![image](https://user-images.githubusercontent.com/674783/157084261-0ecaa1a5-dd1c-436d-9149-516ce7409c12.png)
> 
> This gives us a scrollbar on the publisher where we don't need it _and_ a scrollbar on the overall window which is too many scrollbars. They are also the default scrollbars which are intrusive. Perhaps not zero width but less width might be nice.
> 
> Probably a CSS change is required which would remove the scrollbars for this case. Perhaps a calc function should be used to subtract the height of the `mwc-top-app-bar-fixed` element...
> 
> Even so, there is the case with more IEDs/GSEControls it will extend.
> 
> In this case:
> 
>     * the scrollbar appears to start partway done the publisher pane and abruptly so it doesn't "look right" to my (somewhat unkind) 👁️
> 
>     * Scrollbars as shown here are used in OpenSCD so this is consistent with the overall UI. In the wider world there is flamewars around scrollbars (do you need them, are they a good UI element etc.). Material Design [suggests](https://material.io/components/menus#behavior) there should be scrollbars but the modern take is much more minimalist than the scrollbars we have here.
>       
>       * Browser support for CSS scrollbars is still weak https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars
>       * But neither do we (at least me) want IE 5.5 scrollbars!
>       * And the [webkit option](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) is not on a standards track but is the only viable option
> 
> 
> To be very concrete, what I was thinking of was something less visually intrusive, i.e.
> 
> ```css
>     mwc-list::-webkit-scrollbar {
>       width: 5px;
>       height: 8px;
>       background-color: var(--base3);
>     }
>     
>     mwc-list::-webkit-scrollbar-thumb {
>         background: var(--primary);
>     }
> ```
> 
> This way the scrollbars blend into the selection at the top and for the subscribing pane (I may not have the colours exactly right).
> 
> ![image](https://user-images.githubusercontent.com/674783/157089155-1444633c-8262-47f9-8b1a-d87a4fc5b064.png)
> 
> I accept that I am a pedant and apologise and beg forgiveness 🙏
> 
> A reasonable person will simply respond to this feedback with, "You didn't do that in #568 so why should I?"

Thanks again for the very detailed review!!! As often, I think you are making a very good point. The scroll bares in windows are a pain. With iOS it is not a problem...don't know how it is with Linux based operating systems. 

I also think this should be handled globally in the `normalized.ts` as you pointed out already, the look and feel is the same in all plugins up until now. I know I am saying this a lot lately, but this should be an extra issue with an extra PR. In the PR especially, the complexity is already to big to be handled properly. I will open an issue with your comments as a starter :)

2022-03-08 17:07 UTC, danyill approved these changes
I reviewed it from a UI/functionality point of view. This is a super important feature which I expect to be looking at in detail in future, thanks! :tada:

2022-03-17 13:10 UTC, dlabordus approved these changes

2022-03-17 13:12 UTC, merged