feat(plugins/IED): Add icon set to IED editor containers
openscd/open-scd pull request #570
Opened 2022-03-02 22:32 UTC by Flurb

Resolves #439

2022-03-03 08:31 UTC, dlabordus commented
Strange that the Snapshots haven't changed?

2022-03-04 13:00 UTC, JakobVogelsang commented
Hi @dlabordus you can set a SVG by using the slot `icon` instead of the property `icon` with `action-pane` likeso:

```
<action-pane label="myLabel">
    <mwc-icon label="icon">${someSVG}</mwc-icon>
</action-pane>
```

The thing with the label property is correct. That was my mistake. I triggered rob to use &mdash and can not be done as a string. This could be refactored using `—` directly in the string.

2022-03-04 13:05 UTC, JakobVogelsang requested changes

2022-03-04 13:05 UTC, JakobVogelsang commented on src/editors/ied/access-point-container.ts
> +    return html`<action-pane .icon=${accessPointIcon} .label="${this.header()}">
The same for the other cases. The reason your snapshot won't show any difference is that you have set the property, not the attribute. The snapshot test do test attributes. `lit-element` does write the attribute based on the property, but only for defined types. One such kind is a String, Boolean, Array and others. 

The way we intended to use `svg` within the `action-pane` header is liek so

```
<action-pane label="myLabel">
    <mwc-icon label="icon">${someSVG}</mwc-icon>
</action-pane>
```

Sorry for the missing documentation for that!!!

2022-03-04 23:06 UTC, Flurb commented
> Hi @dlabordus you can set a SVG by using the slot `icon` instead of the property `icon` with `action-pane` likeso:
> 
> ```
> <action-pane label="myLabel">
>     <mwc-icon label="icon">${someSVG}</mwc-icon>
> </action-pane>
> ```
> 
> The thing with the label property is correct. That was my mistake. I triggered rob to use &mdash and can not be done as a string. This could be refactored using `—` directly in the string.

I implemented the solution for the IED container, but I don't think the icon alignment is as nice as the others. What do you guys think?

<img width="749" alt="Schermafbeelding 2022-03-05 om 00 03 15" src="https://user-images.githubusercontent.com/16406106/156853982-39d294f3-6285-4938-b76f-2d25ec54a6fd.png">

2022-03-07 08:22 UTC, Sander3003 commented
@Flurb it looks good to me!

2022-03-07 08:38 UTC, Flurb commented
Let's fully compare them:

Old implementation:
![Schermafbeelding 2022-03-07 om 09 36 54](https://user-images.githubusercontent.com/16406106/156996420-ca9d5105-4641-403f-af5f-669735f1ba47.png)

Suggested implementation from Jakob:
![Schermafbeelding 2022-03-07 om 09 36 25](https://user-images.githubusercontent.com/16406106/156996396-8c8a57f1-f9a4-4ba5-bf5b-79de0468e265.png)

It's not completely aligned, @JakobVogelsang do I need to do something in order to align it? I hope I don't need some custom CSS for this :)

2022-03-07 16:59 UTC, danyill commented
I'm not sure whose suggestion we're on now, but visually the alignment on the current commit looks excellent to me with my :eye: and my :eyeglasses: 

![image](https://user-images.githubusercontent.com/674783/157080991-490de591-75a0-4472-8615-f50dfa97efc4.png)

2022-03-08 09:29 UTC, JakobVogelsang commented
Hi @Flurb, this is a CSS issue in the `action-pane`. We should not resolve it here. You can open an extra issue for this that can be resolved in an extra step. @danyill the changed have not been made in this PR. I think @Flurb has tested it on his machine and found the issue.

2022-03-08 12:48 UTC, Flurb commented
Implemented it, and created an issue: #584

2022-03-08 15:25 UTC, JakobVogelsang commented
Thanks!!

2022-03-09 13:09 UTC, JakobVogelsang approved these changes
LGTM

2022-03-09 14:18 UTC, merged