fix(plugins/Subscription): Empty 'Inputs' element after unsubscribing GOOSE should be deleted
openscd/open-scd pull request #588
Opened 2022-03-09 09:48 UTC by Flurb

2022-03-15 09:05 UTC, JakobVogelsang requested changes

2022-03-16 11:35 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-ied-list.ts
> +      if (!inputsMap[id]) inputsMap[id] = inputs;
The inputs used here are no copies. Don't we remove the ExtRef forever and short circuit the action events? Or in other works undo would not work, isn't it?

2022-03-16 11:37 UTC, JakobVogelsang reviewed
I in my opinion still not working is should. Or do I miss something?

2022-03-16 12:06 UTC, Flurb commented
@JakobVogelsang 

With the current solution, Inputs element is removed when no ExtRefs are available anymore.
When there are ExtRefs left, the Inputs element is not removed.

I do see that undo / redo doesn't work, but the same applies to the subscribing action.
Does using cloneNode fix this?

2022-03-16 22:50 UTC, Flurb commented
Now works with `cloneNode()` :)

2022-03-16 23:13 UTC, JakobVogelsang approved these changes
LGTM

2022-03-16 23:20 UTC, merged