feat(wizard-dialog): wizard-dialog content definition through `WizardInput` objects
openscd/open-scd pull request #596
Opened 2022-03-14 16:54 UTC by JakobVogelsang

Hi all, finally the PR that will extend the `Wizard` API to allow content definition through `WizardInput` objects definition instead of `TemplateResult`. 

The advantage is that a plug-in author in JavaScript can trigger a wizard-dialog in without loading lit-element. 
The disadvantage is that with `WizardInput` you can only define `Select`, `TextField` and `Checkbox` kind inputs. With `TemplateResult` we can add list, buttons .... basically all kind of web-components. This is why we added the WizardInput content definition on top of the old API.

2022-03-16 06:42 UTC, dlabordus requested changes

2022-03-16 06:42 UTC, dlabordus commented on test/unit/wizard-dialog.test.ts
> +    });
Should there be a test to see that there are 2 options available for the "values" passed. (There are 2 'mwc-list-item' under 'wizard-select')

2022-03-16 06:42 UTC, dlabordus commented on src/foundation.ts
> +export type WizardInputElement =
Isn't the WizardCheckbox missing here?

2022-03-16 11:28 UTC, JakobVogelsang commented on test/unit/wizard-dialog.test.ts
> +    });
I think this is covered with the snapshot test above. Here the list-items reflect the selection.

2022-03-16 11:33 UTC, JakobVogelsang commented on src/foundation.ts
> +export type WizardInputElement =
True it is missing I will create an extra PR that points to this on. For now I think for others easier to review, if not mixed with the changes here :) We can keep it open until the PR is merged.

2022-03-17 12:34 UTC, dlabordus approved these changes

2022-03-18 17:57 UTC, danyill reviewed
Christopher Robbin once patted my head and said "You are only a :bear: with a very small :brain:, so let's imagine, for now, that the review process is more for your education than feedback".

On such a basis I can say I like this idea.

2022-03-18 17:57 UTC, danyill commented on test/unit/wizard-dialog.test.ts
> +  describe('with content definition throught WizardInput s', () => {
```suggestion
  describe('with content definition throught WizardInputs', () => {
```

I'm better with spelling than code.

2022-03-18 17:57 UTC, danyill commented on test/unit/wizard-dialog.test.ts
> +    describe('for a specific WizardInputs of the kind Checkbox', () => {
```suggestion
    describe('for a specific WizardInput of the kind Checkbox', () => {
```

2022-03-22 09:15 UTC, merged