Edit DAI values
openscd/open-scd pull request #687
Opened 2022-04-14 08:43 UTC by Flurb

2022-04-18 10:24 UTC, JakobVogelsang requested changes
This review is code based. I would like to play around with some files as well tomorrow

2022-04-18 10:24 UTC, JakobVogelsang commented on src/editors/ied/da-container.ts
> +          <div id="value">
`id` should be used with care. I know this is used  a lot in the code base, due to pending refactors. We learned that on the way as well. `id` should be used for something unique in the dom. In this case, due to the encapsulated style within the web-compoentent `da-container` this does not have an drastic effect here. Theoretically, you could imagine a scenario where someone style an element in the light DOM and by accident uses the same `id`. This could affect another element in the light DOM using the same `id`. There are a lot of discussion online about this topic. I personally like this rule of thumb: 

```
1. IDs reference unique elements. There should only be 1 instance of any 1 ID. Classes can be applied to many elements and an element can have multiple classes
2. A CSS rule using an ID will override a CSS rule with a class if they both try to assign the same properties.
3. IDs are used for all sorts of native applications: anchor references, forms, iframes, whereas classes are used purely for styling with CSS.
```

2022-04-18 10:24 UTC, JakobVogelsang commented on test/testfiles/wizards/ied.scd
> +								<DAI name="integer">
I would not use `Beh` as CDC INS. This has been replaced by `ENC` in Ed.2 and therefore is only part of Ed.1 projects. I would not recommend to use Ed.1 at all,  Ed.2.1 being published. I would certainly not use it in your test files as we say on the first page README we concentrate in Ed.2 and upwards

2022-04-18 10:24 UTC, JakobVogelsang commented on test/testfiles/wizards/ied.scd
> +								<DAI name="integer">
Sorry, I just see you are using it with some randow DA.

2022-04-18 10:24 UTC, JakobVogelsang commented on test/unit/editors/ied/foundation/foundation.test.ts
> +      expect(element).shadowDom.to.equalSnapshot();
Missing `await` an all ...equalSnapshot()

2022-04-18 10:24 UTC, JakobVogelsang commented on test/unit/editors/ied/foundation/foundation.test.ts
> +  function getValue(daiName: string) {
Why not putting the function before the tests?

2022-04-19 05:24 UTC, Flurb commented on src/editors/ied/foundation/foundation.ts
> +export function getCustomField(): Record<DaiValidationTypes, CustomField> {
Thank you!

2022-04-19 05:40 UTC, Flurb commented on test/unit/editors/ied/foundation/foundation.test.ts
> +      expect(element).shadowDom.to.equalSnapshot();
@JakobVogelsang 
Why is this? `element` is already fully loaded, and equalSnapshot is not a `Promise` or something.
Using `await` here has no effect.

2022-04-19 09:01 UTC, Flurb commented on test/unit/editors/ied/foundation/foundation.test.ts
> +      expect(element).shadowDom.to.equalSnapshot();
I already see why it's needed!
[Testing: Semantic Dom Diff](https://open-wc.org/docs/testing/semantic-dom-diff/)

2022-04-21 08:47 UTC, JakobVogelsang approved these changes
LGTM

2022-04-21 10:21 UTC, merged