feat(wizards): Changed label of rptID
openscd/open-scd pull request #697
Opened 2022-04-21 10:51 UTC by dlabordus

closes #636

2022-04-21 11:45 UTC, JakobVogelsang requested changes
Other than the german translation very ok. Thanks for this!

2022-04-21 11:45 UTC, JakobVogelsang commented on src/translations/de.ts
> +    rptID: '???'
```suggestion
    rptID: 'Report-Kontrolblock Kennung'
```

2022-04-21 14:28 UTC, dlabordus commented on src/translations/de.ts
> +    rptID: '???'
Fixed

2022-04-21 14:34 UTC, Flurb approved these changes

2022-04-22 06:46 UTC, JakobVogelsang approved these changes
LGTM

2022-04-24 10:02 UTC, merged