bug(Subscription): Select by Subscriber in Subscriptions Editor
openscd/open-scd pull request #717
Opened 2022-05-01 19:59 UTC by Flurb

Closes #592

2022-05-01 22:00 UTC, JakobVogelsang commented on src/translations/en.ts
> +      publisherView: "GOOSE Publisher view",
The names are not descriptive enough if you ask me. I would rather suggest something like:
`publisherView:  Show subscriber IED(s) per selected GOOSE`
`subscriberView:  Show subscribed GOOSE publisher for selected IED`

2022-05-01 22:02 UTC, JakobVogelsang commented on src/translations/de.ts
> +      publisherView: "???",
publisherView:  Zeigt verbundene IED(s) der ausgewählten GOOSE
subscriberView: Zeigt verbundene GOOSE(s) des ausgewählten IED

2022-05-01 22:09 UTC, JakobVogelsang commented on src/translations/en.ts
> +      publisherTitle: 'Publisher {{ selected }}'
GOOSE(s) subcriber by {{selected}}

2022-05-01 22:10 UTC, JakobVogelsang commented on src/translations/de.ts
> +      publisherTitle: '??? {{ selected }}'
GOOSE(s) verbunden mit {{selected}}

2022-05-02 08:22 UTC, Flurb commented
@JakobVogelsang is the review done besides the translations?

2022-05-02 08:49 UTC, JakobVogelsang commented on src/translations/en.ts
> +      publisherTitle: 'GOOSE(s) subscriber by {{selected}}'
```suggestion
      publisherTitle: 'GOOSE(s) subscribed by {{selected}}'
```

2022-05-02 08:54 UTC, dlabordus submitted a review, later dismissed

2022-05-02 08:54 UTC, dlabordus commented on test/unit/editors/subscription/subscriber-ied-list.test.ts
>  import { html, fixture, expect } from '@open-wc/testing';
Shouldn't this test be renamed to 'subscriber-list.test.ts' and also re-generated the snapshot file.

2022-05-02 08:54 UTC, dlabordus commented on test/unit/editors/subscription/__snapshots__/subscriber-ied-list.test.snap.js
>  snapshots["subscriber-ied-list initially looks like the latest snapshot"] =
Test is only creating 1 snapshot, there are 2 in here.

2022-05-02 08:54 UTC, dlabordus commented on test/unit/editors/subscription/goose-subscriber-list.test.ts
> +  it('looks like the latest snapshot without a doc loaded', async () => {
The before each is now also execute, but nothing is used from it. 
Maybe but two extra describe('') to the test, one called 'without document' and the other 'with document'.

2022-05-02 08:54 UTC, dlabordus commented on src/editors/subscription/elements/goose-publisher-list.ts
> +import '../../../filtered-list.js';
Why put these files in the directory elements and subscriber-list.ts is not there?

The test files are also not in there.

2022-05-02 09:24 UTC, Flurb commented on test/unit/editors/subscription/subscriber-ied-list.test.ts
>  import { html, fixture, expect } from '@open-wc/testing';
Correct!

2022-05-02 09:28 UTC, Flurb commented on test/unit/editors/subscription/__snapshots__/subscriber-ied-list.test.snap.js
>  snapshots["subscriber-ied-list initially looks like the latest snapshot"] =
A leftover, now it's removed

2022-05-02 09:29 UTC, JakobVogelsang commented on test/integration/editors/subscription/Subscription.test.ts
> +      describe('and you subscribe a non-subscribed IED', () => {
the description up until now reads like this: 
`Subscription Plugin -> in GOOSE publisher view -> when selecting a GOOSE message -> and you subscribe a non-subscribed IED`. The last description would read better like so `and subscribing a unsubscribed IED`.

This is true also for the next two descriptions :)

2022-05-02 09:32 UTC, Flurb commented on test/unit/editors/subscription/goose-subscriber-list.test.ts
> +  it('looks like the latest snapshot without a doc loaded', async () => {
Done

2022-05-02 09:35 UTC, Flurb commented on test/integration/editors/subscription/Subscription.test.ts
> +      describe('and you subscribe a non-subscribed IED', () => {
Done!

2022-05-02 10:04 UTC, Flurb commented on src/editors/subscription/elements/goose-publisher-list.ts
> +import '../../../filtered-list.js';
Done!

2022-05-02 10:57 UTC, JakobVogelsang commented on test/integration/editors/subscription/Subscription.test.ts
> +          await expect(
The snapshot test is nice here. I would however prefer to have a check in the doc as well. Meaning an additional ```ts
it('add required connections (ExtRef) to the subscriber IED',()=>{
...     
expect(doc.querySelector...).to.equal(...)
}) 

```

2022-05-02 10:59 UTC, JakobVogelsang requested changes
Some additional tests. Other than that 👍

2022-05-03 07:45 UTC, Flurb commented on test/integration/editors/subscription/Subscription.test.ts
> +          await expect(
Done!

2022-05-03 08:27 UTC, JakobVogelsang approved these changes
LGTM

2022-05-03 09:50 UTC, merged