feat(Subscription): Add edit button or hyperlink to GSEControl dialog in the Subscription Editor
openscd/open-scd pull request #718
Opened 2022-05-01 20:45 UTC by Flurb

2022-05-02 11:00 UTC, JakobVogelsang commented on src/editors/subscription/subscriber-list.ts
> +    this.currentSelectedIed = undefined;
Should this not be part of the upstream branch?

2022-05-02 11:07 UTC, Flurb commented on src/editors/subscription/subscriber-list.ts
> +    this.currentSelectedIed = undefined;
It depends on the select-by-subscriber branch, but it's a feature on it's own.

Ideally, merge the select-by-subscriber first and this one after.

2022-05-03 08:40 UTC, JakobVogelsang commented
I have tested this PR with some files and have some very basic remarks:
1. the button is allocated to the subscriber list. I do not think this is very intuitive. I would have expected those in the list item on the left-hand side. 
2. I do not think we need to edit the IED here. I cannot think of any case where it makes sense to change the IED name halfway through the process of subscription.

2022-05-03 08:50 UTC, Flurb commented
> I have tested this PR with some files and have some very basic remarks:
> 
> 1. the button is allocated to the subscriber list. I do not think this is very intuitive. I would have expected those in the list item on the left-hand side.
> 2. I do not think we need to edit the IED here. I cannot think of any case where it makes sense to change the IED name halfway through the process of subscription.

Removing the IED edit here is fine for me, but the allocation of the edit button is as refined in the issue. Why is this not correct anymore?

2022-05-03 09:06 UTC, JakobVogelsang commented
@Flurb I is my fault, I am sorry. If you look into the issue @danyill 's proposal was putting it next to the GOOSE element. That would be my preferred solution as well. I however, missed the comment of @Sander3003 putting it in the place you have putted it in. During the refinement we were talking about different thing therefore. Sorry for that!

How about making it a topic for next Monday. The implementation is good so far. It is just about the location.

2022-05-03 09:51 UTC, Flurb commented
> @Flurb I is my fault, I am sorry. If you look into the issue @danyill 's proposal was putting it next to the GOOSE element. That would be my preferred solution as well. I however, missed the comment of @Sander3003 putting it in the place you have putted it in. During the refinement we were talking about different thing therefore. Sorry for that!
> 
> How about making it a topic for next Monday. The implementation is good so far. It is just about the location.

Good idea!

2022-05-07 08:19 UTC, danyill commented
Thanks for this feature, I am very grateful. Some brief feedback:

1. I agree that changing the IED name within a GOOSE subscription is confusing. I think we should just remove this. I'm sorry I also didn't comment on this earlier (this occurs when I have the radio button on "Show subscribed GOOSE publisher for selected IED").
2. When I have "Show subscriber IED(s) per selected GOOSE" the edit button allows the GSEControl to be edited. The aspect that I find a little confusing about this is that I would expect editing to be on the Publisher side.

2022-05-10 11:15 UTC, JakobVogelsang requested changes
Thanks for moving it. I really do think it is more intuitive like that. 
I still would request one change 
1. Use `mwc-icon-button` instead of `mwc-icon`. To make sure it is still centered, there is a nice CSS rule: `--mdc-list-item-meta-size` that must be set to the same size as the mwc-icon-button default 48px. The reason here is we have something indicating around the icon that it is clickable.

...and suggest one other:
2. Use CSS to hide the non-selected meta. 
```ts
<mwc-icon-button
     class="${classMap({
          hidden: gseControl !== selectedGseControl,
        })}"
        slot="meta"
        icon="edit"
        @click=${() => this.openEditWizard(gseControl)}
     ></mwc-icon-button>

...

static styles = css`
    ${styles}
   ...
    mwc-icon-button.hidden {
      display: none;
    }
  `;
```

2022-05-10 12:18 UTC, Flurb commented
> Thanks for moving it. I really do think it is more intuitive like that. I still would request one change
> 
> 1. Use `mwc-icon-button` instead of `mwc-icon`. To make sure it is still centered, there is a nice CSS rule: `--mdc-list-item-meta-size` that must be set to the same size as the mwc-icon-button default 48px. The reason here is we have something indicating around the icon that it is clickable.
> 
> ...and suggest one other: 2. Use CSS to hide the non-selected meta.
> 
> ```ts
> <mwc-icon-button
>      class="${classMap({
>           hidden: gseControl !== selectedGseControl,
>         })}"
>         slot="meta"
>         icon="edit"
>         @click=${() => this.openEditWizard(gseControl)}
>      ></mwc-icon-button>
> 
> ...
> 
> static styles = css`
>     ${styles}
>    ...
>     mwc-icon-button.hidden {
>       display: none;
>     }
>   `;
> ```

What is the advantage of using CSS here instead of the proposed solution?

2022-05-10 12:24 UTC, dlabordus approved these changes

2022-05-10 12:59 UTC, dlabordus approved these changes

2022-05-10 14:39 UTC, JakobVogelsang approved these changes

2022-05-10 15:21 UTC, merged