Show eqfunction and subeqfunction
openscd/open-scd pull request #720
Opened 2022-05-02 18:45 UTC by JakobVogelsang

The first of three requests that cover the issue #707 
1. transform CondunctingEquipment and PowerTransformer to action-pane on function filter disabled
2. show `EqFunction` element within ConductingEquipment and PowerTransformer
3. show `SubEqFunction` within `EqFunction`

2022-05-03 10:16 UTC, dlabordus requested changes

2022-05-03 10:16 UTC, dlabordus commented on src/editors/substation/conducting-equipment-editor.ts
Shouldn't there be some extra imports for MWC Components?

This also applies to others editors where mwc-icon and mwc-icon-button are added.

2022-05-03 10:16 UTC, dlabordus commented on src/editors/substation/bay-editor.ts
> +    .content.actionicon {
Is it not possible to use the prtContent way, like doen in Substation and VoltageLevel?
Bay is the only one handling powertransformer-editor differently.

2022-05-03 10:16 UTC, dlabordus commented on src/editors/substation/powertransformer-editor.ts
> +  /** Wheter `EqFunction` and `SubEqFunction` are rendered */
Small typo, wheter, should be Whether.

2022-05-03 10:19 UTC, dlabordus commented
More a general question,
How does this PR relates to EqFunction and SubEqfunction? 
It looks more like there was a PowerTransformer problem when showing functions....

2022-05-03 22:59 UTC, ca-d commented
I really like the user interface overall. Just a few comments:

- `h6` looks too small on my screen to be readable. I'd consider stopping the size reduction at `h5` or even `h4` for deeply nested editors.
- Now that the action icons transform into action panes, I distinctly notice that Equipment doesn't have the "Duplicate" and "Add children" buttons yet. Which of these might make sense to add?
- If we find the dotted outline without focus to be a disturbance, we could think about making the unfocused heading and/or the secondary colour.

Otherwise, LGTM!

2022-05-04 06:28 UTC, JakobVogelsang commented on src/editors/substation/conducting-equipment-editor.ts
True!! Thanks I missed it!

2022-05-04 06:29 UTC, JakobVogelsang commented on src/editors/substation/powertransformer-editor.ts
> +  /** Wheter `EqFunction` and `SubEqFunction` are rendered */
Thanks :)

2022-05-04 06:31 UTC, JakobVogelsang commented on src/editors/substation/bay-editor.ts
> +    .content.actionicon {
I was wondering a bit too, but at the end did like it. The `PowerTransformer` otherwise does take up too much space. Meaning, I kind of like that `PowerTransformer` within a Bay is handled like a `...Equipment`. Is this ok with you or does it bother you this way?

2022-05-04 07:13 UTC, dlabordus commented on src/editors/substation/bay-editor.ts
> +    .content.actionicon {
Fine for me.

2022-05-04 11:14 UTC, JakobVogelsang commented
> More a general question, How does this PR relates to EqFunction and SubEqfunction? It looks more like there was a PowerTransformer problem when showing functions....

Within the `Substation` editor we did on purose hide the children of `ConductingEquipment`, `PowerTransformer` and in the future `GeneralEquipment` to reduce the complexity a user sees. For function naming not usable as the elements `EqFunction` is a direct child of `ConductingEquipment`, `PowerTransformer` and others ... thus we need to be able to show those children and that is why I started to do this :)

2022-05-06 07:42 UTC, merged