feat(editors/subtation): allow instationtion of LNode from LNodeTypes
openscd/open-scd pull request #766
Opened 2022-05-22 19:16 UTC by JakobVogelsang

Closes #740 

This wizard is straight forward, as are its test. 

At the moment the other `LNode` type wizard is used both as edit and as create wizard. With this PR it will be an edit wizard only. I do think it is logically correct as for a top-down procedure usually engineers will instantiate from LNodeType first, which create the `LNode` initially, and in the process of creating an instantiated virtual IED will complete the `LNode` pointing to both the LNodeType and the LN/LN0. 

However, I am very open for discussion here :)

2022-05-24 08:22 UTC, ca-d requested changes

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +  for (let i = 1; i < 99; i++) {
Why use `<= 98` here? How many iterations do we need? This and the next line seem buggy.

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +    if (lnInsts[i - 1] !== i) return i;
I don't understand this escape condition.

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +  return NaN;
Is this how we signal failure here? Why not throw?

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +    const clonedParent = <Element>parent.cloneNode(true); //for multiple selection of same lnClass
Thanks for the comment! Somehow I still don't quite understand the line. Could you explain in a bit more detail?

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +        if (isNaN(uniqueLnInst) || uniqueLnInst > 99) return null;
Again: why use `99` here? If it's an SCL significant constant guaranteed to stay the same forever regardless of edition, it belongs in foundation, otherwise at least at the top of the file. Scattering literal constants throughout source code is considered a code smell.

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +        const existLLN0 =
Could we call this `hasLLN0` or `lLN0Exists` to read more like English?

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +          prefix: null,
Why do these need to be set to `null` explicitly here?

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +            const isDesabled =
Should be `isDisabled`

2022-05-24 08:22 UTC, ca-d commented on src/wizards/lnode.ts
> +function lNodeInstanceWizard(parent: Element): Wizard {
As discussed, let's change Instance and Reference to InstRef and TypeRef, respectively.

2022-05-24 12:08 UTC, JakobVogelsang commented on src/translations/de.ts
> +      reference: 'Reference auf bestehenden logischen Knoten erstellen',
It was a mistake :) Thanks for spotting

2022-05-24 12:13 UTC, JakobVogelsang commented on src/translations/de.ts
> +      subscriberView: 'Zeigt verbundene GOOSE(s) des ausgewählten IED',
I just opened a new issue and a new PR just to have it right there. #776

2022-05-24 12:13 UTC, JakobVogelsang commented on src/translations/en.ts
> +      uniquewarning: 'Logical node class already exist',
True

2022-05-24 12:23 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +    if (lnInsts[i - 1] !== i) return i;
The array `lnInsts` is a sorted array containing integers of existing `lnInst`'s.  This excape function makes sure to take the first not used integer between 1 and 99. Say `lnInsts` is `[1, 2, 3, 5, 10, 13, 15]` then the return value would be `4`. 

Sorry, I did not find a more compact and elegant way to implement this.

2022-05-24 12:24 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +  return NaN;
This is how we indicate that no unique `lnInst` can be found in the parent element for the specific `lnClass`. But you are right, we should dispatch a log event.

2022-05-24 12:28 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +    const clonedParent = <Element>parent.cloneNode(true); //for multiple selection of same lnClass
When importing, say three `CSWI` type logical nodes to a parent that has already two included with `lnInst`'s say 1 and 3. What we need is the algorithm to give the first to be imported `lnInst` 2 the second 4 and the first 5. 

If the do the check on the parent element itsself the algorithm would give all the three `lnInst` 2. As we can add LNode element to the cloned parent we can do the correct check for multiple imports of the same `lnClass`

2022-05-24 13:00 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +        if (isNaN(uniqueLnInst) || uniqueLnInst > 99) return null;
Ahhh, I see you would like this to be a constant and not hard coded with the function itself. This makes sense, I will change it

2022-05-24 13:03 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +          prefix: null,
`ldInst` must be `null` as not pointing to any IED that has logical device as child element. 
`prefix` can be `null` and will be in lots of cases. I think it is a good default. Users can change with the to be developed edit wizard.

2022-05-24 13:05 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +          prefix: null,
This is not really necessary here. It was more or less for me to see it directly in the code. But we do not do that in other parts of the create wizard I will kick it out.

2022-05-24 13:40 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +            const isDesabled =
True

2022-05-25 11:14 UTC, JakobVogelsang commented
The last commit LGTM. Thanks for your effort :)

2022-05-30 07:55 UTC, ca-d approved these changes
LGTM

2022-05-30 08:00 UTC, merged