feat(wizards/lnode): add edit wizard
openscd/open-scd pull request #778
Opened 2022-05-24 21:58 UTC by JakobVogelsang

Closes #777

2022-05-25 10:05 UTC, ca-d requested changes
LGTM apart from the 'wizard-textfield` bug.

2022-05-25 10:05 UTC, ca-d commented on src/wizards/lnode.ts
> +      disabled
The combination of `nullable` and `disabled` is currently dangerous due to a bug in `wizard-textfield`:

Even when it's `disabled`, as long as it's `nullable` the null switch can be toggled, and by toggling it back and forth we even enable the TextField itself, allowing the user to enter arbitrary values.

2022-05-25 10:05 UTC, ca-d commented on src/translations/de.ts
> +    lnInst: 'Instanz des logischen Knoten',
I'd use "des Knotens" here instead of "des Knoten", I think that's the more common form.

2022-05-25 11:09 UTC, JakobVogelsang commented on src/translations/de.ts
> +    lnInst: 'Instanz des logischen Knoten',
True! Thanks for the hint

2022-05-25 11:42 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +      disabled
Thanks for the thorough review. I did not see that...
Me, I'd not really want to have attributes like `ldInst` be editable and therefore would like to have the fix upfront and rebase on this one rather than removing the `disabled` attribute from the `wizard-textfield`s at this point.

What would you say be the best procedure?

2022-05-25 15:45 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +      disabled
Is fixed with #781

2022-05-27 08:45 UTC, Flurb commented on src/wizards/lnode.ts
> +      helperPersistent
When do we want to have a persistent helper text, and when do we not want to have it?
I'm not using the persistent helper text at all, is there a common rule for this?

2022-05-27 09:30 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +      helperPersistent
This is needed here as we have pure read only text field. The helper text usually only appears when text fields are focused, and this for a reason. In this particular case they cannot be focused and that is why I decided to show the helper text permanently.

2022-05-27 09:31 UTC, Flurb commented on src/wizards/lnode.ts
> +      helperPersistent
Good point, thanks for the explanation!

2022-05-27 09:31 UTC, Flurb approved these changes

2022-05-27 09:32 UTC, JakobVogelsang commented on src/wizards/lnode.ts
> +      helperPersistent
I think we do not need a common rule here. I depend on the importance of the helper text to understand the input. If so and it is read-only - set to `disabled` - we show permanently show the helper. Otherwise, the component is doing its job just fine :)

2022-05-30 07:55 UTC, ca-d approved these changes
LGTM

2022-05-30 08:22 UTC, merged