refactor: remove OpenSCD as dispatcher
openscd/open-scd pull request #802
Opened 2022-06-01 22:08 UTC by JakobVogelsang

After having the ability to load plugins synchronously, we can not get rid of OpenSCD as the dispatcher within the plugins.
In addition to that this PR removes OpenSCD as dispatcher form Settings as well which was not necessary from the beginning.

2022-06-02 06:56 UTC, dlabordus requested changes

2022-06-02 06:56 UTC, dlabordus commented on src/editors/ied/da-wizard.ts
> -      secondary: {
This changes the label from 'Close' to 'Cancel'. Because these dialogs don't have any action related, close is better. The user is not cancelling anything.

2022-06-02 06:56 UTC, dlabordus commented on src/editors/ied/do-wizard.ts
> -      secondary: {
This changes the label from 'Close' to 'Cancel'. Because these dialogs don't have any action related, close is better. The user is not cancelling anything.

2022-06-02 06:57 UTC, dlabordus commented
@JakobVogelsang: small remark, watch out to change the formatting to much, this makes reviewing much harder, because there are a lot of changes and the ones that really matter can be missed.

2022-06-02 10:40 UTC, ca-d commented on src/editors/ied/do-wizard.ts
> -      secondary: {
I suggest we fix this by switching the translation from "Cancel" to "Close" in general. Many wizards don't cancel something when you close them.

2022-06-02 11:59 UTC, ca-d requested changes

2022-06-02 11:59 UTC, ca-d commented on test/unit/validators/ValidateTemplates.test.ts
> +            .pluginId="${'/src/validators/ValidateTemplates.js'}"
Why do we need to set a `pluginId` here? Why didn't we need to do this before? Why set this string as a property rather than as an attribute?

2022-06-07 05:23 UTC, dlabordus commented on src/editors/ied/do-wizard.ts
> -      secondary: {
I think it depends how a user looks at it. When I click on something like "Edit Substation", it's quit normal to press "Cancel" if you want to stop editing the substation. 
But in these cases the user click on "Show Info" or something like that. So in these 2 cases for me "Cancel" seems a little bit strange, because I just want to close the info wizard.

2022-06-07 06:18 UTC, ca-d commented on test/unit/validators/ValidateTemplates.test.ts
> +            .pluginId="${'/src/validators/ValidateTemplates.js'}"
We used to set this lower down. It's needed for the current validation API. We can probably change this in `open-scd-core` along the lines of the new `Setting` API.

2022-06-07 06:35 UTC, ca-d commented on src/editors/ied/do-wizard.ts
> -      secondary: {
I have been wanting to change the wording in wizards from "cancel" to "close" for quite a while, because we really can't assume that closing a wizard in general will cancel some action. At least some of the time, an action will have already been committed by an interactive element in the wizard or a subwizard at the point where the dialog is closed. This has lead to confusion before. I just added a commit with this suggested change. Please let me know what you think about the result!

2022-06-14 06:16 UTC, dlabordus approved these changes

2022-06-14 06:30 UTC, dlabordus approved these changes

2022-06-14 06:52 UTC, merged