feat(): Switch publisher and subscriber in SV subscription editor
openscd/open-scd pull request #830
Opened 2022-06-22 12:48 UTC by Flurb

closes #767

2022-06-24 15:58 UTC, Sander3003 commented
Is this ready for review?

2022-06-27 12:02 UTC, Sander3003 commented
closes #780

2022-06-28 19:15 UTC, JakobVogelsang commented on src/editors/SampledValues.ts
> +import { translate } from 'lit-translate';
A minor thing: import are grouped to be a bit better readable. This one is usuaelly in the first block together with lit-element imports

2022-06-28 19:19 UTC, JakobVogelsang commented on src/editors/SampledValues.ts
> +import { RadioListItem } from '@material/mwc-list/mwc-radio-list-item.js';
A minor thing: we usually group all mwc type imports before importing internals.

2022-06-28 19:47 UTC, JakobVogelsang commented on src/editors/SampledValues.ts
>  export default class SampledValuesPlugin extends LitElement {
I feel this name does not fit anymore. Maybe something like `SampledValueSubscriberPlugin`. The same applies for the now `SubscriberABBPlugin` that might be better named as `GSEControlSubscriberPlugin`

2022-06-28 20:16 UTC, JakobVogelsang commented on src/editors/Subscription.ts
>  import { translate } from 'lit-translate';
Move import statement below `lit-element` imports

2022-06-28 20:36 UTC, JakobVogelsang commented on src/editors/subscription/goose/goose-list.ts
>  import { classMap } from 'lit-html/directives/class-map';
Minor thing: lit related imports to the top.

2022-06-28 21:12 UTC, JakobVogelsang commented on src/editors/subscription/goose/ied-list.ts
> +export class IedList extends LitElement {
Why do you need two web components that do the same thing but only differ in the title? See ied-list-smv

2022-06-28 21:29 UTC, JakobVogelsang commented on src/editors/subscription/sampledvalues/smv-list.ts
> +  renderSmv(smvControl: Element): TemplateResult {
Render methods are usually grouped together like so

```ts

otherMethods ...

renderSomeElse()...

render() ....

static styles = ...

```

2022-06-28 21:40 UTC, JakobVogelsang commented on src/translations/de.ts
> +        title: '???',
```suggestion
        title: 'SampledValue-Publizierer',
```

2022-06-28 21:40 UTC, JakobVogelsang commented on src/translations/de.ts
> +        subscriberTitle: '??? {{ selected }}',
```suggestion
        subscriberTitle: 'Verbunden mit {{ selected }}',
```

2022-06-28 21:46 UTC, JakobVogelsang commented on src/translations/de.ts
> +        title: 'IED-Publizierer',
```suggestion
        title: 'IEDs',
```

2022-06-28 21:47 UTC, JakobVogelsang commented on src/translations/de.ts
> +        title: '???',
```suggestion
        title: 'IEDs',
```

2022-06-28 21:47 UTC, JakobVogelsang commented on src/translations/en.ts
> +        title: 'GOOSE Subscriber',
```suggestion
        title: 'IEDs',
```

2022-06-28 21:47 UTC, JakobVogelsang commented on src/translations/en.ts
> +        title: 'Sampled Values Subscriber',
```suggestion
        title: 'IEDs',
```

2022-06-28 21:52 UTC, JakobVogelsang commented on test/unit/editors/subscription/sampledvalues/smv-list.test.ts
> +  it('sends a newSmvSelectEvent on first update', async () => {
Is it async?

2022-06-28 21:52 UTC, JakobVogelsang commented on test/unit/editors/subscription/sampledvalues/smv-list.test.ts
> +  it('triggers a newSmvSelectEvent when a list item is clicked', async () => {
Is it async?

2022-06-28 21:54 UTC, JakobVogelsang requested changes
Mostly minor thing and translations. However, I would also ask you to run the linter and formatter. Some new files are not formatted. You can easily see it by a line longer than 80 characters.

2022-06-28 21:57 UTC, Flurb commented
> Mostly minor thing and translations. However, I would also ask you to run the linter and formatter. Some new files are not formatted. You can easily see it by a line longer than 80 characters.

Will do tomorrow!
When I run `npm run-script format:prettier` (which is probably what you mean), I get 183 changed files. This is not what we want right? Or do you mean something else?

2022-06-28 22:16 UTC, Flurb commented
> > Mostly minor thing and translations. However, I would also ask you to run the linter and formatter. Some new files are not formatted. You can easily see it by a line longer than 80 characters.
> 
> @JakobVogelsang Will do tomorrow! When I run `npm run-script format:prettier` (which is probably what you mean), I get 183 changed files. This is not what we want right? Or do you mean something else?
> 
> When you run this, you are formatting everything. That would blow this PR. But for the new files you have created in this PR, I would like them to be formatted. There are tools that do it for you on saving the file. In VSCode I use prettier for example. I am sure for you IDE there is something similar as well.

Actually worked pretty well with Prettier :)
Going to refactor the rest tomorrow!

2022-06-29 08:04 UTC, Flurb commented on src/editors/subscription/goose/ied-list.ts
> +export class IedList extends LitElement {
Ah this is not mandatory right? I was a bit confused about two elements having the same name at the same time in the DOM, but these IED lists are never at the same time in the DOM. So this will work correctly with the same name :)

2022-06-29 15:48 UTC, JakobVogelsang approved these changes
LGTM Thanks!

2022-06-29 16:13 UTC, merged