fix: Adding Subnetwork to a configuration without a Communication Ele…
openscd/open-scd pull request #875
Opened 2022-07-14 14:21 UTC by pascalwilbrink

…ment failed for the first time

When creating a `Communication` Element in Communication.ts, the created Element is also returned to use it as a parent for the wizard

The `Should create a Communication Element` integration test is extended to also check that the Wizard is closed properly

Signed-off-by: Pascal Wilbrink <pascal.wilbrink@alliander.com>

2022-07-14 16:14 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          expect(parent.wizardUI.dialogs.length).to.equal(1);
Has been checked in the test before. I would skip it :)

2022-07-14 16:15 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          const dialog: Dialog = parent.wizardUI.dialogs.item(0);
There is a property called `parent.wizardUI.dialog` that does the same

2022-07-14 16:22 UTC, JakobVogelsang requested changes

2022-07-14 16:22 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          expect(parent.wizardUI.dialogs.length).to.equal(0);
The important check is missing. What you want to see is that the `Communication` section including the `SubNetwork[name="Test"]` has been created. So something like this 

`expect(doc.querySelectot('Communication > SubNetwork[name="Test"]').to.exist`

2022-07-14 16:22 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          expect(parent.wizardUI.dialogs.length).to.equal(0);
This test is check that the wizard closed is not needed here, I would suggest.

2022-07-14 16:22 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +
I would use empty lines with care. I usually use them to tell the reader of the code that something new is happening. If you have an empty line after each line that does not make the test any more readable than leaving the empty line out completely is my feeling.

2022-07-14 16:22 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          const nameInput: WizardTextField = dialog.querySelector<WizardTextField>('wizard-textfield[label="name"]')!;
You formatter in not working. This line should break otherwise :)

2022-07-18 08:02 UTC, pascalwilbrink commented on test/integration/editors/communication/Communication.test.ts
> +          expect(parent.wizardUI.dialogs.length).to.equal(0);
Fixed

2022-07-18 08:02 UTC, pascalwilbrink commented on test/integration/editors/communication/Communication.test.ts
> +          const nameInput: WizardTextField = dialog.querySelector<WizardTextField>('wizard-textfield[label="name"]')!;
Fixed

2022-07-18 08:02 UTC, pascalwilbrink commented on test/integration/editors/communication/Communication.test.ts
> +
I deleted some empty lines

2022-07-18 08:09 UTC, JakobVogelsang requested changes
Some line in the test are not needed and make the test less readable. I would suggest refactoring a bit more.

2022-07-18 08:09 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          await new Promise(resolve => setTimeout(resolve, 100)); // await animation
I don't think we need those. They are there for debugging. Also try to get rid of any `element.updateComplete` and use them only where you need it :)

2022-07-18 08:09 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          expect(parent.wizardUI.dialogs.length).to.equal(0);
This is tested with the test before. Try to reduce the line in the test to what you want to show with the test. It makes the test more readable :)

2022-07-18 08:09 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          const dialog: Dialog = parent.wizardUI.dialog!;
This is not the purpose of the test. The dialog is just a thing that you need to use here. We wanne see that the `Communication` was not in the doc and after the both `Communication` and a specific `SubNetwork` is in the doc :)

2022-07-18 08:09 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          await new Promise(resolve => setTimeout(resolve, 100)); // await animation
Debug leftover?

2022-07-18 08:09 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          await new Promise(resolve => setTimeout(resolve, 100)); // await animation
Degug leftover?

2022-07-18 08:57 UTC, pascalwilbrink commented on test/integration/editors/communication/Communication.test.ts
> +          expect(parent.wizardUI.dialogs.length).to.equal(0);
Fixed

2022-07-18 11:10 UTC, pascalwilbrink commented on test/integration/editors/communication/Communication.test.ts
> +          await new Promise(resolve => setTimeout(resolve, 100)); // await animation
This one is needed for the dialog to open, checked it in the test

2022-07-18 11:30 UTC, pascalwilbrink commented on test/integration/editors/communication/Communication.test.ts
> +          await new Promise(resolve => setTimeout(resolve, 100)); // await animation
This one is needed because the Subnetwork Element is created asynchronously (checked it in the test)

2022-07-18 14:31 UTC, JakobVogelsang commented on test/integration/editors/communication/Communication.test.ts
> +          await new Promise(resolve => setTimeout(resolve, 100)); // await animation
I am not so sure. Creating such an element is really not time-consuming. I think it will work without any awaits here :)

2022-07-19 07:11 UTC, pascalwilbrink commented on test/integration/editors/communication/Communication.test.ts
> +          await new Promise(resolve => setTimeout(resolve, 100)); // await animation
when i removed it, the test failed. because an event is risen, it needs to wait

2022-07-19 11:54 UTC, JakobVogelsang approved these changes
LGTM

2022-07-20 07:50 UTC, merged