feat(editors/publisher): add sampled-value-control-element-editor
openscd/open-scd pull request #920
Opened 2022-08-03 21:14 UTC by JakobVogelsang

The last read-only part. From now on it becomes interesting :)

2022-08-04 05:42 UTC, dlabordus requested changes

2022-08-04 05:42 UTC, dlabordus commented on src/editors/publisher/sampled-value-control-editor.ts
> +        ) ?? null;
Is this part (?? null) needed? QuerySelector returns (Element |  null) by default.

2022-08-04 05:42 UTC, dlabordus commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +  get sMV(): Element | null | undefined {
Why return both null and undefined? Is it really needed and I prefer to choose one of the two.

2022-08-04 05:42 UTC, dlabordus commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +      ${multicast === 'true'
Isn't a little bit strange to only show the checkbox when multicast is false?

2022-08-04 05:42 UTC, dlabordus commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +        <div class="headersubtitle">No connection to SubNetwork</div>
Shouldn't this be done through lit-translate?

2022-08-04 05:42 UTC, dlabordus commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +          sMV.querySelector(`Address > P[type="${key}"]`)?.innerHTML.trim() ??
Why not use ".textContent", ".innerHTML" looks a little strange for a XML Document.

2022-08-04 05:42 UTC, dlabordus commented on test/unit/editors/publisher/sampled-value-control-element-editor.test.ts
> +  describe('with multicast attribute set to false - deprecated', () => {
deprecated? Shouldn't just be removed?

2022-08-04 11:49 UTC, JakobVogelsang commented on src/editors/publisher/sampled-value-control-editor.ts
> +        ) ?? null;
I would argue yes: with the `DataSet` I use the undefined to either render or not render the element editor. Undefined means that something not control block is selected. Null means that a control block an item is selected but it is an empty control block. That is why the `data-set-element-editor` has an element property `Element | null`. That is for example not the case for the control block itself where it can be undefined or must be an element.

2022-08-04 11:49 UTC, JakobVogelsang commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +  get sMV(): Element | null | undefined {
That is true I will change that :)

2022-08-04 11:52 UTC, JakobVogelsang commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +      ${multicast === 'true'
Yea, that is the result from a discussion we had on the edit wizard for `SampledValueControl`. We agreed there that highlighting that multicast is not set to true should be done to allow users to a potential configuration error. Other that that is just disturbing to have as that thing is deprecated. My guess is that nobody will ever see it :)

2022-08-04 11:52 UTC, JakobVogelsang commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +        <div class="headersubtitle">No connection to SubNetwork</div>
That is true. That is the case for all the other header. I will correct it. Thx for the hint

2022-08-04 11:53 UTC, JakobVogelsang commented on src/editors/publisher/sampled-value-control-element-editor.ts
> +          sMV.querySelector(`Address > P[type="${key}"]`)?.innerHTML.trim() ??
True! Thx

2022-08-04 11:54 UTC, JakobVogelsang commented on test/unit/editors/publisher/sampled-value-control-element-editor.test.ts
> +  describe('with multicast attribute set to false - deprecated', () => {
See comment above. I think it is valid to highlight potential errors in the file. If today a file with multicast error appears, that is rather an error.

2022-08-08 05:39 UTC, dlabordus commented on test/unit/editors/publisher/sampled-value-control-element-editor.test.ts
> +  describe('with multicast attribute set to false - deprecated', () => {
I would prefer to not just use the term 'deprecated' like this, because most of the time it means cleaning up the code to developers.
Maybe change the text to 'with "deprecated" multicast attribute set to false'. This way it's more clear that the attribute is deprecated and not the software itself.

2022-08-08 06:55 UTC, JakobVogelsang commented on test/unit/editors/publisher/sampled-value-control-element-editor.test.ts
> +  describe('with multicast attribute set to false - deprecated', () => {
I see that is true. Will cahnge that :)

2022-08-08 09:58 UTC, dlabordus approved these changes

2022-08-08 13:32 UTC, merged