Refactor logging history
openscd/open-scd pull request #922
Opened 2022-08-08 13:51 UTC by juancho0202

Closes #916

2022-08-08 14:02 UTC, dlabordus commented on src/menu/History.ts
> +  get sclHistory(): SclhistoryEntry[] {
Why not just return a Element Array and use the createMessage in the render function?
This way the object SclHistoryEntry can probably also be removed, because it isn't used any more.

2022-08-08 14:05 UTC, dlabordus commented on src/menu/History.ts
> +        class="${entry.kind}"
Is always 'sclhistory', so maybe move the styling to this dialog and just hard-coded the class here?

2022-08-08 14:06 UTC, dlabordus commented on src/menu/History.ts
> +        <mwc-icon
I don't think this is needed like this anymore, because there is no toggle anymore.

2022-08-11 06:11 UTC, dlabordus requested changes

2022-08-11 06:11 UTC, dlabordus commented on CHANGELOG.md
> +## [0.21.0](https://github.com/openscd/open-scd/compare/v0.20.0...v0.21.0) (2022-08-08)
What happened here? This should be a change.
Also for the files manifest.json and package*.json

There are all changes here that are already in main since yesterday. 
So maybe first look what happened here before starting the review again.

2022-08-11 06:22 UTC, dlabordus commented on src/translations/de.ts
> +    viewSclHistory: 'View SCL history',
Where is this label used?

2022-08-11 06:28 UTC, dlabordus commented on src/menu/SclHistory.ts
> +        <span>${translate('sclHistory.noEntries')}</span>
This label is not there (anymore).
I think something went wrong in the merge.

Because you are using two labels 'sclHistory.noEntries' and 'history.name'.

2022-08-11 09:52 UTC, JakobVogelsang commented on src/translations/de.ts
> +    name: '????',
```suggestion
    name: 'SCL History',
```

2022-08-11 09:52 UTC, JakobVogelsang commented on src/translations/de.ts
> +    noEntries: '????',
```suggestion
    noEntries: 'Keine Einträge in der SCL History',
```

2022-08-11 09:58 UTC, JakobVogelsang commented on src/menu/SclHistory.ts
> +        <span>${translate('sclHistory.noEntries')}</span>
```suggestion
        <span>${translate('history.noEntries')}</span>
```

2022-08-11 10:12 UTC, dlabordus commented on src/menu/SclHistory.ts
> +        <span>${translate('sclHistory.noEntries')}</span>
I suggested sclHistory, because history is so general.

2022-08-11 10:14 UTC, JakobVogelsang commented on src/menu/SclHistory.ts
> +        <span>${translate('sclHistory.noEntries')}</span>
My bet sorry!!!! My remark is that with no history it shows me sclHistor.noEntries in the UI.

2022-08-11 10:15 UTC, JakobVogelsang commented on src/menu/SclHistory.ts
> +        <span>${translate('sclHistory.noEntries')}</span>
The translation files to not meet the string here yet.

2022-08-11 12:43 UTC, dlabordus approved these changes

2022-08-11 14:58 UTC, JakobVogelsang approved these changes
LGTM

2022-08-12 07:50 UTC, merged