Feature: Added the possibility to ignore attributes and/or elements w…
openscd/open-scd pull request #926
Opened 2022-08-09 13:58 UTC by pascalwilbrink

…hen checking for differences between 2 elements.

Signed-off-by: Pascal Wilbrink <pascal.wilbrink@alliander.com>

2022-08-10 17:38 UTC, JakobVogelsang commented on src/menu/CompareIED.ts
> +      label="Filter mutables">
Please translate! My suggestion:

en: `Filter preject specific settings`
de: `Projektspzifische Unterschiede ausblenden`

2022-08-10 17:39 UTC, JakobVogelsang commented on src/menu/CompareIED.ts
> +    const filterToIgnore: DiffFilter<Element> = {
I would make it a global variable for now. If in a later stage we make this user configurable we can change. But here it makes the render method be hard to read.

2022-08-10 17:40 UTC, JakobVogelsang commented on test/testfiles/VS737-template.scd
> +<SCL xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
I would change the name of the SCD file to be more descriptive. The issue number in Allianders Jira is not so much :)

2022-08-10 17:40 UTC, JakobVogelsang commented on test/testfiles/VS737-withchanges.scd
> +<SCL xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
I would change the name of the SCD file to be more descriptive. The issue number in Allianders Jira is not so much :)

2022-08-11 06:06 UTC, dlabordus requested changes

2022-08-11 06:07 UTC, dlabordus commented on test/testfiles/VS737-template.scd
> +<SCL xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
Our maybe see if we can do something with the two existing files, because there are already two files used.
Copy some extra IED's in there to do the trick.

2022-08-11 06:31 UTC, dlabordus commented on src/foundation/compare.ts
> +      ? ':root'
Shouldn't this be ':scope'?

2022-08-11 09:08 UTC, pascalwilbrink commented on test/testfiles/VS737-template.scd
> +<SCL xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
fixed: Moved it into the existing file

2022-08-11 09:08 UTC, pascalwilbrink commented on test/testfiles/VS737-withchanges.scd
> +<SCL xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
fixed: Moved it into the existing file

2022-08-11 09:09 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +  rootElementToBeCompared = rootElementToBeCompared || elementToBeCompared;
Fixed: removed it.

2022-08-11 09:09 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +  rootElementToBeCompared = rootElementToBeCompared || elementToBeCompared;
fixed: Removed it

2022-08-11 09:11 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +  rootElementToBeCompared?: Element,
1) Because of the question mark, the root/search elements are optional.
2) I renamed them to searchElement

I can extract the rendering function like this:

```code
function render(elementA, elementB) { return internalRender(elementA, elementB, elementA, elementB); }

function internalRender(elementA, elementB, searchElementA, searchElementB) { ... }
```

2022-08-11 09:11 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +      ? ':root'
Fixed: changed to scope (i saw that :root and :scope did the same thing)

2022-08-11 10:35 UTC, dlabordus commented on src/foundation/compare.ts
> +  rootElementToBeCompared?: Element,
This is better, because then the API is more clear if used in plugins.

2022-08-11 10:45 UTC, dlabordus commented on src/foundation/compare.ts
> +      ? ':root'
I'm not full sure. 
Searching on the internet I think they are only the same when used in a Style Sheet File.
But in this case :root is the root document of the XML and for the IED that is the SCL Element. 
And :scope is the element on which the querySelector is executed, so here IED for instance.

```
14.1. :root pseudo-class
The :root pseudo-class represents an element that is the root of the document.

For example, in a DOM document, the :root pseudo-class matches the root element of the Document object. In HTML, this would be the html element (unless scripting has been used to modify the document).
```

```
8.6. The Reference Element Pseudo-class: :scope
In some contexts, selectors can be matched with an explicit set of :scope elements. This is a (potentially empty) set of elements that provide a reference point for selectors to match against, such as that specified by the querySelector() call in [DOM].

The :scope pseudo-class represents any element that is a :scope element. If the :scope elements are not explicitly specified, but the selector is scoped and the scoping root is an element, then :scope represents the scoping root; otherwise, it represents the root of the document (equivalent to :root). Specifications intending for this pseudo-class to match specific elements rather than the document’s root element must define either a scoping root (if using scoped selectors) or an explicit set of :scope elements.
```

2022-08-11 11:04 UTC, pascalwilbrink commented on src/menu/CompareIED.ts
> +      label="Filter mutables">
Fixed

2022-08-11 11:05 UTC, pascalwilbrink commented on src/menu/CompareIED.ts
> +    const filterToIgnore: DiffFilter<Element> = {
Fixed, moved outside class. Should this be in a different file as well?

2022-08-11 11:06 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +    return html` ${
I don't know what happened. I used the standard prettier formatter

2022-08-15 08:43 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +  rootElementToBeCompared?: Element,
Fixed

2022-08-22 20:32 UTC, JakobVogelsang approved these changes
LGTM

2022-08-22 20:33 UTC, merged