859 subscriber later binding goose plugin
openscd/open-scd pull request #945
Opened 2022-08-18 22:05 UTC by juancho0202

Refactor to have a single Later Binding left panel with filterable FCDA list that may be used either for SVC or GSEControl elements

(WIP)

Missing:

- Adding Later Binding Goose tests
- Updating Later Binding Sample Value tests
- Removing unused code once the team approves the refactor

2022-08-23 06:44 UTC, dlabordus commented on src/editors/SMVSubscriberLaterBinding.ts
> -import './subscription/smv-laterbinding/svc-laterbinding-list.js';
Shouldn't we cleanup this old file, including translations?

2022-08-23 06:48 UTC, dlabordus commented on src/editors/GooseSubscriberLaterBinding.ts
> +    .container {
I think @JakobVogelsang likes the list be the full width for this issue and when picking up the next issue to add the second list make it 50%.

So for now that means removing 'display' and 'height' from the class 'container' and also the class 'column' isn't needed for now. When picking up issue #865, these lines can be added again.

2022-08-23 06:50 UTC, JakobVogelsang commented on src/editors/GooseSubscriberLaterBinding.ts
> +    .container {
That is very true :)

2022-08-25 09:07 UTC, dlabordus requested changes

2022-08-25 13:25 UTC, dlabordus approved these changes

2022-08-25 13:29 UTC, juancho0202 commented
Closes #860

2022-08-25 13:29 UTC, merged