Naming in GOOSE/SMV Subscriber plugins
openscd/open-scd pull request #991
Opened 2022-09-03 02:49 UTC by danyill

Closes #729 

This is in response to #729 and partially resolves #958 (slightly different terminology used than what was proposed there).

I know this is just wording and possibly doesn't seem that important :grey_question:. However, just a few words can make things more or less intuitive. I will be happy to receive a review, and if this is not helpful, I will be happy for it to be closed. :shrug: 

GOOSE/Sampled Value Control:

* Simplify the radio buttons to "Publisher | Subscriber" and "Subscriber | Publisher". They are too hard to parse and users must learn by doing in any case.
* Reword the headings for IED lists to be more explicit about what is happening in the two parts of the screen

Later Binding:

* If we are going to describe the source, we need to qualify it with not just the DA but the LDevice and LNode to be meaningful
* This is a lot of information, so an overflow should wrap to be responsive because this title can be pretty important
* Generally avoid technical language (like FCDAs and ExtRefs) and replace them with Messages and Inputs. I think this is better for users, although less precise.
* I decided not to include the IED name because I think applying the `activated` attribute to the filtered list will be adequate to provide this context (arguably removes a need for the title at all but in many ways looking up to more significant text is better than looking left)

The German is Google Translate and possibly no good; happy for it to be reverted or improved.

Here are some screenshots:

### GOOSE

**Publisher**

**Before**
![image](https://user-images.githubusercontent.com/674783/188252598-7b65e33f-9d14-47d3-ab80-727c5831650a.png)

**After**
![image](https://user-images.githubusercontent.com/674783/188252526-950d902e-be7a-4d34-b58b-86e29db47eff.png)

Subscriber

**Before**
![image](https://user-images.githubusercontent.com/674783/188252608-2082eabe-2346-4a87-b033-a98b550c5e99.png)

**After**
![image](https://user-images.githubusercontent.com/674783/188252541-98e9992f-9eb0-4e90-a9eb-0b4b0ffe0f05.png)

SMV is similar.

### SMV (Later Binding) 

**Before**
![image](https://user-images.githubusercontent.com/674783/188252618-73013924-fb4e-40a1-bb55-f73d9da5b3ba.png)

**After**
![image](https://user-images.githubusercontent.com/674783/188252495-640b54eb-af4e-420d-abf5-bd262d4673ec.png)

2022-09-06 12:25 UTC, JakobVogelsang submitted a review, later dismissed
Thanks for this very important contribution! There are some little details that need to be changed, but it is on a good track. Before fixing any of it I would like to ask for a rebase on the current main. As we worked on the Later binding GOOSE in parallel you will have merge conflicts otherwise

2022-09-06 12:25 UTC, JakobVogelsang commented on src/translations/de.ts
> +          noControlBlockFound: 'Keine GOOSE-Nachrichten gefunden',
```suggestion
          noControlBlockFound: 'Keine GOOSEs gefunden',
```

2022-09-07 19:55 UTC, danyill commented on src/editors/subscription/smv-laterbinding/ext-ref-laterbinding-list.ts
> +          lNodeName: lNodeName ?? '-',
Yes, it is even longer after the rebase because it includes the control block name. We could rely on the activatable property to provide context for the selection on the LHS? WDYT?

2022-09-07 19:55 UTC, danyill commented on test/unit/__snapshots__/Setting.test.snap.js
> -    <div style="overflow: hidden;">
This is to allow that thing which, above is "a bit too long" to provide context even on small form factors.

2022-09-07 19:59 UTC, danyill commented on test/unit/__snapshots__/Setting.test.snap.js
> -    <div style="overflow: hidden;">
Oh whoops, this is not meant to be here. Somehow when regenerating snapshots, items which are unchanged by my code still regenerate and occasionally I incorrectly commit them.

2022-09-07 20:02 UTC, danyill commented on src/translations/de.ts
> +        title: 'GOOSE-Verlag',
Reverted

2022-09-07 20:50 UTC, danyill commented
Thank you for your review. I have (I hope) done as requested. Just the outstanding issue about how to treat the title, I am interested in your thoughts and a further review. Particularly I hope to have taken your advice on the German translation but it is easy to make mistakes...

2022-09-08 06:34 UTC, JakobVogelsang commented on src/editors/subscription/smv-laterbinding/ext-ref-laterbinding-list.ts
> +          lNodeName: lNodeName ?? '-',
Yes, that is actually a suggestion from other contributors as well. So long we can permanently see the selected `FCDA` there is no need for a title here:

2022-09-08 06:34 UTC, JakobVogelsang commented on src/editors/subscription/smv-laterbinding/ext-ref-laterbinding-list.ts
> +          lNodeName: lNodeName ?? '-',
But then I would add this feature in this PR directly and get rid of the title :)

2022-09-13 22:06 UTC, danyill commented
I had a go at adding activatable.

The follow on from this is that in the GOOSE and Subscriber plugins prior to this PR the list selection gets lost when changing between editors.

Either we should retain a reference and restore it or we should make it deselected on first entry to the plugin (which is what I think I have done using `firstUpdated` but I am unsure if this is a good approach).

Note that the radio button in the GOOSE and Subscriber plugins has slightly odd behaviour. Toggling the radio button is one thing but when you click on it the selection is lost. I could not figure out exactly the cause of this (I was hoping to use the events triggered by the radio button to remove the selection references).

2022-09-15 07:14 UTC, JakobVogelsang requested changes
In general LGTM. I fixed some German translations, and you need to merge main, and I think update the snapshots as @juancho0202 was working on the same code. 

Nice @danyill very clean and nice changes

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        publisherView: 'Herausgeber | Teilnehmer',
```suggestion
        publisherView: 'Publisher | Subscriber',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        subscriberView: 'Teilnehmer | Herausgeber',
```suggestion
        subscriberView: 'Subscriber | Publkisher',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        iedListTitle: 'Sampled Value-Abonnenten',
```suggestion
        iedListTitle: 'Verbunden mit Sampled Values',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        publisherTitle: 'Sampled Value Messages abonniert bei {{ selected }}',
```suggestion
        publisherTitle: 'Sampled Value  verbunden mit {{ selected }}',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        publisherTitle: 'GOOSE Messages abonniert bei {{ selected }}',
```suggestion
        publisherTitle: 'GOOSE Nachricht verbunden mit {{ selected }}',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        iedListTitle: 'GOOSE-Abonnenten',
```suggestion
        iedListTitle: 'Verbunden mit GOOSE Meldungen',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        title: 'Für Ausgewählte Daten-Attribut Verfügbare Eingaben',
```suggestion
        title: 'Für Ausgewählte Daten-Attribut Verfügbare Verbindung',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        noSubscribedExtRefs: 'Keine abonnierten Eingänge',
```suggestion
        noSubscribedExtRefs: 'Keine bestehenden Verbindungen',
```

2022-09-15 07:14 UTC, JakobVogelsang commented on src/translations/de.ts
> +        noAvailableExtRefs: 'Keine verfügbaren Eingaben zum Abonnieren',
```suggestion
        noAvailableExtRefs: 'Keine verfügbaren Eingänge vorhanden',
```

2022-09-15 08:47 UTC, danyill commented
Thank you for this review :bow:, for the German translations and for accepting this slightly fiddly PR. I have made these changes and merged `main` to this branch, no snapshots needed updating.

2022-09-16 08:50 UTC, JakobVogelsang approved these changes
LGTM

2022-09-16 08:53 UTC, JakobVogelsang commented
I am sorry but I have to trigger you again @danyill. @juancho0202 has pushed last changes in the Later binding plugin and that is conflicting you work. Could you do another merge? We have nothing conflicting in the pipeling at the moment so this will not be wasted time :D

2022-09-16 08:56 UTC, juancho0202 commented
Sorry @danyill 😅

2022-09-16 20:16 UTC, merged

2022-09-16 20:17 UTC, danyill commented
No problem. This time we courageously use the merge button though our :heart: trembles.