Subscriber Later Binding (GOOSE): Show connected and available ExtRef on FCDA selection
openscd/open-scd pull request #995
Opened 2022-09-05 07:25 UTC by juancho0202

2022-09-05 08:21 UTC, dlabordus requested changes

2022-09-05 08:21 UTC, dlabordus commented on src/editors/subscription/later-binding/ext-ref-laterbinding-list.ts
> +  get version(): string | null {
Use a function call 'getSclSchemaVersion' to check if it's a 2003 version.

2022-09-05 08:21 UTC, dlabordus commented on src/editors/subscription/later-binding/ext-ref-laterbinding-list.ts
> +  private checkSuscribedGooseRequirements(extRefElement: Element): boolean {
I think this method should also be implemented for SampledValueControl, @JakobVogelsang?
So then only the difference is in 'serviceType', I think between 'SMW' and 'GOOSE'.

2022-09-05 09:04 UTC, JakobVogelsang commented on src/editors/subscription/later-binding/ext-ref-laterbinding-list.ts
> +  private checkSuscribedGooseRequirements(extRefElement: Element): boolean {
Oh yes, we should do that. I was missing that for the SampledValueControl element type subscribing when defining the issue.

2022-09-05 14:15 UTC, juancho0202 commented on src/editors/subscription/later-binding/ext-ref-laterbinding-list.ts
> +  private checkSuscribedGooseRequirements(extRefElement: Element): boolean {
would this be the solution?

`extRefElement.getAttribute('serviceType') === this.controlTag !== 'GSEControl'? 'GOOSE':'SMV' &&`

2022-09-05 14:16 UTC, juancho0202 commented on src/editors/subscription/later-binding/ext-ref-laterbinding-list.ts
> +  private checkSuscribedGooseRequirements(extRefElement: Element): boolean {
are there any other differences aside from serviceType attribute for SMV?

2022-09-06 05:15 UTC, dlabordus requested changes

2022-09-06 05:15 UTC, dlabordus commented on src/editors/subscription/later-binding/ext-ref-laterbinding-list.ts
> +  private checkSuscribedGooseRequirements(extRefElement: Element): boolean {
Change the name of the function, because it's not anymore about Goose Only :-)

2022-09-06 07:19 UTC, dlabordus approved these changes

2022-09-06 07:19 UTC, merged