919 compare view more clear
openscd/open-scd pull request #996
Opened 2022-09-05 07:49 UTC by pascalwilbrink

2022-09-05 13:10 UTC, dlabordus submitted a review, later dismissed

2022-09-05 13:10 UTC, dlabordus commented on test/unit/plain-compare-list.test.ts
> +        element.leftHandSubtitle = 'subtitle';
Why not add a rightHandSubtitle?

2022-09-05 13:10 UTC, dlabordus commented on test/unit/menu/__snapshots__/dist/CompareIED.test.snap.dev.js
> +"use strict";
What is this for kind of file?

2022-09-05 13:10 UTC, dlabordus commented on test/unit/menu/CompareIED.test.ts
>  import { expect, fixture, html } from '@open-wc/testing';
Maybe check the snapshots being made, because they are all the same now, because of the use of a component.

2022-09-05 13:10 UTC, dlabordus commented on test/unit/foundation/__snapshots__/dist/compare.test.snap.dev.js
> +"use strict";
What is this for kind of file?

2022-09-06 07:02 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +      renderDiff(
renderDiffInternal is needed so that renderDiff still has the same contract as before (2 elements, 1 diffFilter)

2022-09-06 07:04 UTC, pascalwilbrink commented on src/menu/CompareIED.ts
> +  @property({ attribute: false })
Fixed

2022-09-06 07:04 UTC, pascalwilbrink commented on test/unit/plain-compare-list.test.ts
> +        element.leftHandSubtitle = 'subtitle';
Fixed

2022-09-06 07:15 UTC, pascalwilbrink commented on test/unit/menu/__snapshots__/dist/CompareIED.test.snap.dev.js
> +"use strict";
removed, i get these files when i run the tests. compiled js files

2022-09-06 07:15 UTC, pascalwilbrink commented on test/unit/foundation/__snapshots__/dist/compare.test.snap.dev.js
> +"use strict";
Removed

2022-09-06 07:51 UTC, pascalwilbrink commented on src/foundation/compare.ts
> +import { automationLogicalNode, controlLogicalNode } from '../icons/lnode.js';
Fixed

2022-09-06 09:01 UTC, pascalwilbrink commented on test/unit/menu/CompareIED.test.ts
>  import { expect, fixture, html } from '@open-wc/testing';
I'm not sure what you mean with this. There are seperate tests in plain-compare-list.test.ts for this?

2022-09-06 09:21 UTC, dlabordus commented on test/unit/menu/CompareIED.test.ts
>  import { expect, fixture, html } from '@open-wc/testing';
A lot of Snapshots are made to show different compare windows, but because this is now a component the snapshot is always the same in this test file (see CompareIED.test.snap.js), so I'm wondering if some of these tests can be removed.
And as you already say, these tests are moved/copied to plain-compare-list.test.ts.

2022-09-06 11:01 UTC, pascalwilbrink commented on test/unit/menu/CompareIED.test.ts
>  import { expect, fixture, html } from '@open-wc/testing';
Fixed, removed some duplicate tests

2022-09-06 12:03 UTC, pascalwilbrink commented
Fixed, removed snap.dev.js and added rule to .gitignore

2022-09-07 19:55 UTC, JakobVogelsang commented
There is one quick fix that I would ask you to do. When rendering the two lists of IEDs the querySelectAll for the element `IED`. With the vendor `ABB` there are elements within the private element that are `eComm:IED`. Those need to be filtered. There is a function in foundation called `isPublic` that we need to apply in line 102 like so: `..filter(isPublic).` and in line 109.

2022-09-07 19:58 UTC, JakobVogelsang commented
One more thing: You have defined some properties in the web component `plain-compare-list` that a violated in the call. To identify this, you can add the VSCode extension `lit-plugin` :)

2022-09-07 19:59 UTC, JakobVogelsang requested changes
Filter for private `IED` elements and follow your property type definition the the new web component

2022-09-13 07:44 UTC, JakobVogelsang approved these changes
LGTM

2022-09-13 07:45 UTC, JakobVogelsang approved these changes
LGTM

2022-09-13 07:49 UTC, JakobVogelsang approved these changes
LGTM

2022-09-13 10:53 UTC, merged